chef/ohai

- lib/ohai/version.rb
Reason for 8.1.0 vs 8.0.2 was because of https://github.com/chef/ohai/commit/f0b89f760099e5d773b6dd815245123ae412b30e
> Bump version to 8.1.0

- ohai.gemspec
1.x still works fine, so leaving the lower floor in place.
> bumping ffi-yajl to pick up 2.x

- lib/ohai/plugins/linux/network.rb
This is a fix for #397 where any Gentoo based OS does not get IP information.  The root cause is the detection logic for the ip command.  Even though shellout to IP on those platforms would work we first check to see if IP exists by looking for ip in specific paths.  We didn't include /bin/ip where Gentoo stores it.  This simply adds that path which should magically make it all work on Gentoo.  I'm not really sure how to write a test for this, but if anyone has ideas/examples I'm open to writing something.
> Update ip binary detection logic to work on Gentoo/CoreOS

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
Right now, ohai will return v4 addresses and routes for v6, rather than
just not returning anything. Fixes #380
> Work correctly when IPv6 is disabled on Linux

- lib/ohai/plugins/kernel.rb
- lib/ohai/plugins/windows/drivers.rb
- spec/unit/plugins/kernel_spec.rb
With the introduction of minimal-ohai in chef, we don't want to
grab a bunch of garbage
cc @danielsdeleo @btm @smurawski @thommay @adamedx 
This needs to go out with minimal-ohai so that it's not a breaking change
> Move windows drivers out of kernel

- CHANGELOG.md
- lib/ohai/system.rb
- ohai.gemspec
replaces invalid characters in the rendered JSON and avoids throwing
an exception at that stage.
> force ohai output to UTF-8

- CHANGELOG.md
- RELEASE_NOTES.md
- lib/ohai/plugins/linux/filesystem2.rb
- spec/unit/plugins/linux/filesystem2_spec.rb
Benefits:
* Can handle multiple virtual FSes with the same "device" (none)
* Can handle a device mounted multiple places
* Is resilient to mtab being a symlink to /proc/mounts
* Provides multiple views for ease of use
* Provides a mechanism that has gauranteed lack of overwritten data
* Forks far fewer times than it's predecessor
How it works:
* It provides 3 views:
* by_pair is the primary one and what most users are expected to use. It
gaurantees no loss of data from conflict and has an entry in the hash for
each pair of $device,$mountpoint (or "$device," for unmounted devices).
* by_device a similar layout to the original filesystem plugin which is
indexed by device, except that 'mount' entry is now 'mounts' and is an array.
While this solves many of the problems users can encounter by …
> Provide a new and improved linux filesystem plugin

- lib/ohai/plugins/hostname.rb
On Windows 2008 R2 (and possibly other versions of Windows), `node['hostname']` returns only the first 15 characters of the hostname--this breaks for machines with hostnames longer than 15 chars. This commit changes the WMI attribute that populates `node['hostname']` to be one that provides the full hostname. The truncated version is preserved in `machinename`.
> Fix windows 2008 hostname truncation 

- lib/ohai/plugins/darwin/virtualization.rb
- lib/ohai/plugins/linux/virtualization.rb
- lib/ohai/plugins/windows/virtualization.rb
- spec/unit/plugins/darwin/virtualization_spec.rb
- spec/unit/plugins/linux/virtualization_spec.rb
- spec/unit/plugins/windows/virtualization_spec.rb
Parallels Desktop is product for desktop virtualization for Mac such as VMware fusion.
This PR adds the support of detection Parallels Desktop as host system on Mac and as guest system on Mac, Windows and Linux.
> The detection of Parallels virtualization added.

- CHANGELOG.md
- lib/ohai/plugins/darwin/filesystem.rb
- spec/unit/plugins/darwin/filesystem_spec.rb
Recent versions of Darwin change default 'df' output to have '-i' by default,
which broke parsing by the filesystem plugin. This passes -i in all the time so
we always get consistent output.
There were no tests for this... and even though I'm trying deprecate this plugin
with filesystem2, I still wrote some for ya. :)
> Fix darwin filesystem plugin on newer OSX.

- RELEASE_NOTES.md
- lib/ohai/plugins/darwin/filesystem2.rb
- lib/ohai/plugins/linux/filesystem2.rb
- spec/unit/plugins/darwin/filesystem2_spec.rb
- spec/unit/plugins/linux/filesystem2_spec.rb
The same trick for by_device to list multiple pointpoints should be in
by_mounpoint for multiple devices.
Add tests for both alternative views.
> Fix my_mountpoint view in filesystem2; add tests

- lib/ohai/plugins/linux/filesystem2.rb
- spec/unit/plugins/linux/filesystem2_spec.rb
This is a forwardport of 2cb36823b173aa45736d32194db2ae8365fdad53 (which fixes
some lsblk parsing in filesystem) to filesystem2.
This also fixes a bug in the related unittests for filesystem2
> Forward port fix for #469

- lib/ohai/plugins/linux/filesystem2.rb
We were dropping 'device' for entries only in /proc/mounts
> [filesystem2] Minor linux bug

- lib/ohai/plugins/linux/filesystem2.rb
This makes 'mounts' in by_device and 'devices' in by_mount always get
initialized as an empty array instead of not existing. if the data doesn't
exist. This prevents callers from having to do
```
if foo and foo['mounts'] and foo['mounts'].emtpy?
```
to determine if something is mounted.
> filesystem2 bugfix

- lib/ohai/plugins/linux/virtualization.rb
Properly detect KVM using DMI, which is useful when the CPU vendor/model is masked (e.g. when mirroring the host CPU).
> better KVM virtualization detection

- Gemfile
- ohai.gemspec
Remove pinning.
Also clean up .gemspec for domain name, etc.
> rspec_junit_formatter has been released with RSpec3 support

- CHANGELOG.md
- DOC_CHANGES.md
- Gemfile
- lib/ohai/application.rb
- lib/ohai/config.rb
- lib/ohai/dsl/plugin.rb
- lib/ohai/hints.rb
- lib/ohai/loader.rb
- lib/ohai/log.rb
- lib/ohai/system.rb
- ohai.gemspec
- spec/spec_helper.rb
- spec/unit/application_spec.rb
- spec/unit/config_spec.rb
- spec/unit/dsl/plugin_spec.rb
- spec/unit/hints_spec.rb
- spec/unit/system_spec.rb
Implements the following from [rfc053](https://github.com/chef/chef-rfc/blob/master/rfc053-ohai-config.md):
- Create config context `Ohai::Config.ohai`
- Create shortcut `Ohai.config` for `Ohai::Config.ohai`
- Deprecates top-level attributes of `Ohai::Config`
@chef/client-maintainers @chef/client-core
> Deprecate Ohai::Config in favor of Ohai::Config.ohai

- ohai.gemspec
Fixing things that I broke...
Chef will always depend on [an unreleased version of `chef-config`](https://github.com/chef/chef/blob/master/chef.gemspec#L18). Chef also depends on `ohai`. To prevent dependency conflicts we have to ensure the version of `chef-config` that Ohai depends on is compatible with whatever the current version of Chef is on master. This will be fine and good until we start working on Chef 13.
Yay.
Apparently, the desire is to keep the `chef-config` version the same as the Chef version, so we can't relax the constraint there.
@chef/client-core 
PS: Working on omnibus changes to get this to build correctly.
> Update the chef-config dependency version to be compatible with chef

- ohai.gemspec
I've just released chef-config 12.5.0.alpha.1, which includes changes needed for ohai config.
> Grab alpha release of chef-config gem

- CHANGELOG.md
- DOC_CHANGES.md
- lib/ohai/application.rb
- lib/ohai/system.rb
- spec/functional/application_spec.rb
- spec/unit/application_spec.rb
- spec/unit/system_spec.rb
Replaces https://github.com/chef/ohai/pull/582, which has the requisite number of :+1:s, but I'd like to wait until https://github.com/chef/ohai/pull/587 is in and rebase.
> Ohai::Application loads configuration file

- lib/ohai/plugins/solaris2/network.rb
Remove definition of `ETHERNET_ENCAPS` as a constant and move it into the plugin body as a frozen array to avoid annoying warnings during test runs.
> remove "warning: already initialized constant ETHERNET_ENCAPS"

- lib/ohai/config.rb
- lib/ohai/system.rb
- spec/unit/system_spec.rb
Two things I discovered while plugging the new ohai config system into chef (https://github.com/chef/chef/pull/3689):
1. It's unnecessary to set `ChefConfig.logger = Ohai::Log`. Chef sets this logger to `Chef::Log` for [reasons which aren't applicable to ohai](https://github.com/chef/chef/blob/master/lib/chef/config.rb#L25-L27), IMO. Ohai will only use the configuration settings in its config context, none of which use a logger. Besides, setting `ChefConfig.logger` in ohai will override the setting by chef. Removing this setting reduces headache.
2. Chef allows an `:auto` log-level, which gets [resolved when `chef-client` runs](https://github.com/chef/chef/blob/master/lib/chef/application.rb#L141). Test Kitchen [explicitly configures log_level to …
> Remove config logging, resolve :auto log-level.

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
Cisco's upcoming Nexus platform has a native Wind River Linux userland and a
CentOS-based guestshell that runs in a container over the host operating system.
This patch supports the following platform/platform_family combinations:
CentOS 7.1: centos/rhel (unchanged)
guestshell: nexus/rhel
WRL: nexus/cisco-wrlinux
> Correct platform, platform_family and version detection on Cisco's Nexus platforms.

- lib/ohai/plugins/solaris2/memory.rb
- spec/unit/plugins/solaris2/memory_spec.rb
Memory plugin does not return correct output.
Running ohai memory on a solaris machine gives output as
{
"total": 0
}
This is because memory plugin on solaris uses "prtconf -m" to get memory which does not seem to be valid.
This pull request attempts to fix this. (Reference http://docs.oracle.com/cd/E23824_01/html/821-1451/gkkwk.html#enflm on how to get memory on a solaris machine)
> Fix memory plugin output on solaris

- lib/ohai/plugins/aix/memory.rb
- spec/unit/plugins/aix/memory_spec.rb
Memory plugin does not return any memory attributes on aix due to a minor bug in definition of memory Mash. This pull request is to fix that and also adds unit tests for aix memory plugin
> Fix aix memory plugin output

- lib/ohai/plugins/solaris2/memory.rb
- spec/unit/plugins/solaris2/memory_spec.rb
This PR adds swap space attributes for solaris memory plugin. Swap space is computed using "swap -s" command and converted to megabytes to be consistent with memory[total] which is also in megabytes.
> Add swap space attributes for solaris memory plugin

- CHANGELOG.md
- Gemfile
- lib/ohai/mixin/softlayer_metadata.rb
- lib/ohai/plugins/cloud.rb
- lib/ohai/plugins/softlayer.rb
- spec/unit/mixin/softlayer_metadata_spec.rb
- spec/unit/plugins/softlayer_spec.rb
Add support for Softlayer cloud
> Add support for Softlayer cloud

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
I had to refactor the `linux/network.rb` to understand what's going on and how to fix the issue with the openvz-guest ipaddress. 
But finally I fixed it @ line 92
> return correct ipaddress for openvz guests (fixes #415)

- lib/ohai/plugins/solaris2/cpu.rb
- spec/unit/plugins/solaris2/cpu_spec.rb
Solaris cpu plugin does not return correct per processor data on systems that have sparc processor as the current plugin is targeted towards systems that have x86 processor. From solaris 11.2 documentation (https://docs.oracle.com/cd/E36784_01/html/E36819/frcbd.html#ADSYSeqbug), output of  "psrinfo -p -v"  is different based on sparc vs x86 systems. This PR adds support for sparc based systems.
> Add support for sparc based processors in solaris cpu plugin

- lib/ohai/plugins/aix/network.rb
- spec/unit/plugins/aix/network_spec.rb
Currently on AIX if ifconfig is run against interfaces that are down it will bring that interface up. This fix will only run ifconfig against available interfaces.
> Only run ifconfig against active interfaces

- DOC_CHANGES.md
- lib/ohai/config.rb
- lib/ohai/dsl/plugin/versionvii.rb
- lib/ohai/exception.rb
- lib/ohai/plugin_config.rb
- spec/unit/config_spec.rb
- spec/unit/dsl/plugin_spec.rb
- spec/unit/plugin_config_spec.rb
Implement the remaining tasks of [rfc053](https://github.com/chef/chef-rfc/blob/master/rfc053-ohai-config.md), namely:
* Add support for `ohai.plugin` in configuration files.
* Add `configuration` method to plugin DSL.
> Plugin configuration

- lib/ohai/plugins/windows/memory.rb
- spec/unit/plugins/windows/memory_spec.rb
This PR builds on top of #452 and adds tests. All memory attributes are converted to MB to be consistent with other platforms like Solaris,Unix. Thanks to @webframp for the initial pull request.
> Windows memory plugin

- lib/ohai/plugins/aix/cpu.rb
- spec/unit/plugins/aix/cpu_spec.rb
1. Change cpu["total"] to give the total number of virtual processors a.k.a number of threads as in other  platforms.
2. Change processor index to be cpu["0"] instead of cpu["proc0"].
3. Move vendor_id,frequency and processor model attribute to within processor index output and give them same names as other platforms. Frequency is called mhz and model is called model_name.
4. Add cores attribute to be consistent with solaris cpu plugin.
> Make AIX cpu plugin's output consistent with Solaris cpu plugin

- lib/ohai/plugins/solaris2/cpu.rb
- spec/unit/plugins/solaris2/cpu_spec.rb
* psrinfo -p does not work across all platforms.  Oracle T4-1 platforms
* Converted the CPU detection to use kstat, tested/validated on Solaris 8,9,10,11, and across SPARC and x86 architectures 
* Generalized CPU attribute support - SPARC and X86 are now consistent
* Added cpustate counters to count CPU states - useful for software license restrictions for on-line CPUs 
* Kept all previous Key/Value pairs to align with other OSs
> Convert Solaris OHAI CPU detection to kstat from psrinfo

- .gitignore
- lib/ohai/plugins/aix/network.rb
- spec/unit/plugins/aix/network_spec.rb
Previously `ohai` running within a WPAR completely failed to detect any networking information. Now it does. /cc @chef/client-aix @scotthain 
Before:
```
bash-4.2# ohai network
{
"interfaces": {
}
}
```
After:
```
bash-4.2# ohai network
{
"interfaces": {
"en0": {
"state": "up",
"flags": [
"UP",
"BROADCAST",
"NOTRAILERS",
"RUNNING",
"SIMPLEX",
"MULTICAST",
"GROUPRT",
"64BIT",
"CHECKSUM_OFFLOAD(ACTIVE)",
"CHAIN"
],
"addresses": {
"172.31.10.211": {
"family": "inet",
"prefixlen": null,
"netmask": "255.255.252.0",
"broadcast": "172.31.11.255"
}
},
"tcp_sendspace": "262144",
"tcp_recvspace": "262144",
"rfc1323": "1"
},
"lo0": {
"state": "up",
"flags": [
"UP",
"BROADCAST",
"LOOPBACK",
"RUNNING",
"SIMPLEX",
"MULTICAST",
"GROUPRT",
"64BIT",
"LARGESEND",
"CHAIN"
],
"addresses": {
"127.0.0.1": { …
```
> Properly detect WPAR networking

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
WRL7 is used by Cisco on the IOS-XR platform.  This PR adds
additional checks to the os-release and cisco-release files
to properly detect this new platform.
> Adding support for Wind River Linux 7.

- CHANGELOG.md
- lib/ohai/runner.rb
- spec/unit/plugins/abort_spec.rb
Fix for https://github.com/chef/ohai/issues/516
Ensure that we re-raise SystemExit from plug-in run.
cc @chef/client-core @danielsdeleo @mcquin
> Fix behavior of Ohai plug-in abort

- lib/ohai/plugins/linux/cpu.rb
- spec/unit/plugins/linux/cpu_spec.rb
Add a cores attributes to get total number of cores on linux machines.
> Add total cores to linux cpu plugin

- lib/ohai/plugins/windows/cpu.rb
- spec/unit/plugins/windows/cpu_spec.rb
Windows CPU enumeration was only looking at the first CPU. Hence the core and CPU counts were incorrect. This change also adds unit tests for the Windows CPU plug-in. This fixes issue#623 (https://github.com/chef/ohai/issues/623)
@adamedx @mcquin @thommay @chef/client-core
> Fix Windows cpu enumeration, add tests

- lib/ohai/plugins/windows/cpu.rb
- spec/unit/plugins/windows/cpu_spec.rb
1. Change cpu[:total] to return total number of logical processors instead of cores as in other platforms like Linux,Solaris
2. Add cpu[:cores] to return total number of cores
3. Add spec tests for the cpu plugin on windows
> Change windows cpu plugin to be consistent with other plaforms, add spec test

- lib/ohai/plugins/network_listeners.rb
When proc_state is called for the second and all future times on a
single sigar instance, it fails to throw an exception, resulting in
invalid memory access during ohai reporting of process names. This
workaround causes an invalid pid (0) to be caught and prevent the
invalid access.  Closes #423 and will be unnecessary and should be
reverted when hyperic/sigar#48 is resolved.
> Workaround for hyperic/sigar#48, throw on 0 pid

- lib/ohai/plugins/freebsd/cpu.rb
- spec/unit/plugins/freebsd/cpu_spec.rb
The comment block and the tests had an incorrect sample of what
dmesg.boot looked like.  I got 68 different people to send me samples of
what the output looks like, with about 100 samples total.  The Origin
line is always indented and the spacing around the equals
signs differ.  On 10.2+ there are not spaces, but on 10.1 and earlier there are 
spaces.  I updated the regex to properly detect the existing fields and
also added family/model values, which we already gathered on Linux.
> Fix and extend CPU detection on FreeBSD

- lib/ohai/plugins/freebsd/filesystem.rb
- lib/ohai/plugins/freebsd/os.rb
- spec/unit/plugins/freebsd/filesystem_spec.rb
Modified version of the inode collection code from the Linux plugin.
Also add a filesystem spec for FreeBSD which is about 1/3 the specs from
the Linux filesystem spec, but modified for command output on FreeBSD
> Collect inode data on FreeBSD and add filesystem specs

- CHANGELOG.md
- lib/ohai/plugins/linux/virtualization.rb
- spec/unit/plugins/linux/virtualization_spec.rb
chef-12.1.1-1.el6 (but also tested with https://github.com/chef/ohai/blob/ae08e09da6d96b7977584ca42dd14c45b51f6e5e/lib/ohai/plugins/linux/virtualization.rb)
RHEL 6 server virtual machine running under RHEV hypervisor
Detect running in a VM via the `node[:virtualization]` attribute
Run `ohai` in a Linux VM running under RHEL and see that `virtualization` is empty
Ok. This is bit up for debate I suppose.  To have the least ripple and the most compatiblity with existing cookbooks, I would think the expected result should be the same when running under the RHEV hypervisor as running under KVM (this is what I implemented).  But I could see some interest it differentiating KVM and RHEV even though the RHEV hypervisor is KVM.  However, someone interested in RHEV specifically can still check for …
> Add detection for RHEV (on Linux guests) to virtualization plugin

- lib/ohai/plugins/virtualbox.rb
- spec/unit/plugins/virtualbox.rb
Grabs data from the guest additions if the CLI tool works.  That provides us with the guest additions version/revision and vbox version/revision/lang on the host.
> Add a plugin for Virtualbox details

- ohai.gemspec
This was released on the 2015-11-21.
> mime-types 3 is Ruby 2.0+ only

- ohai.gemspec
We don't use this gem and pinning it is causing problems
with other things (chef-server). The issue is that
chef-server-ctl things are using rest-client, which requires
mime-types < 3.
cc @chef/client-core
> The mime must die

- lib/ohai/plugins/vmware.rb
- spec/unit/plugins/vmware_spec.rb
This will prevent Azure guests that contain the vmware toolbox CLI from being identified as vmware hosts.  We shouldn't even try to grab vmware values unless dmidecode has identified the host as vmware.  Added specs for when the CLI is missing and when we're not running on vmware.
> Only poll vmware attributes when on vmware

- lib/ohai/plugins/darwin/cpu.rb
- spec/unit/plugins/darwin/cpu_spec.rb
We were counting CPUs wrong.  See #671 for details
> Correctly count real vs. total vs. cores on darwin

- lib/ohai/plugins/freebsd/cpu.rb
- spec/unit/plugins/freebsd/cpu_spec.rb
Use dmesg to correctly determine the number of real CPUs, the number of
real cores, and the number of HT cores.  This aligns CPU count data with
what we collect on Linux.
> Determine real, total, and cores for BSD

- lib/ohai/plugins/aix/cpu.rb
- lib/ohai/plugins/aix/filesystem.rb
- lib/ohai/plugins/aix/kernel.rb
- lib/ohai/plugins/aix/memory.rb
- lib/ohai/plugins/aix/network.rb
- lib/ohai/plugins/aix/os.rb
- lib/ohai/plugins/aix/platform.rb
- lib/ohai/plugins/aix/virtualization.rb
- lib/ohai/plugins/hostname.rb
- spec/unit/plugins/aix/cpu_spec.rb
- spec/unit/plugins/aix/filesystem_spec.rb
- spec/unit/plugins/aix/hostname_spec.rb
- spec/unit/plugins/aix/kernel_spec.rb
- spec/unit/plugins/aix/memory_spec.rb
- spec/unit/plugins/aix/network_spec.rb
- spec/unit/plugins/aix/os_spec.rb
- spec/unit/plugins/aix/platform_spec.rb
- spec/unit/plugins/aix/uptime_spec.rb
- spec/unit/plugins/aix/virtualization_spec.rb
I think that's everything from my shortlist.
/cc @chef/engineering-services @chef/client-aix
> Improvements to filesystem and wpar detection on AIX

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
Get speed, duplex, transceiver type, etc.
As suggested here by @thommay 
https://github.com/chef/ohai/issues/507#issuecomment-161395056
> Add support for collecting ethernet layer one information from ethtool on linux

- lib/ohai/plugins/init_package.rb
- spec/unit/plugins/init_package_spec.rb
New kernels will always have /proc/1/comm, but older kernels don't.
Those systems are all init based (debian 6, ubuntu 10.04, centos 5.11).
A good number of these systems are EoL, but some like CentOS 5.11 are
going to be around for several more years.  We should probably support
detecting init on them properly.
> Handle old kernels where we can't determine the init system

- lib/ohai/plugins/kernel.rb
- spec/unit/plugins/kernel_spec.rb
An important distiction on solaris servers is x86 vs. sparc processor
architecture.  Using uname -m to report the machine type does make that
distinction explicitly.  The uname -p value is explicit about the
difference.
> Create kernel[:processor] from uname -p output

- lib/ohai/mixin/network_constants.rb
- lib/ohai/plugins/linux/network.rb
- lib/ohai/plugins/network.rb
- spec/unit/plugins/linux/network_spec.rb
- spec/unit/plugins/network_spec.rb
Fixes #685.
Builds on and replaces #689.
@jaymzh @tas50
> Fix detection of mac address on IPv6 only systems

- lib/ohai/plugins/rackspace.rb
- spec/unit/plugins/rackspace_spec.rb
Hello,
It's a really useful information to correlate a Chef node with a Rackspace Server. 
It's the only way to be 100% sure a Chef node is the one you can see in your Rackspace cloud.
It would help for Chef deleted nodes cleaning jobs by example.
It will prevent to have to play with IP/Hostname to identify a node.
> Add instance_id to rackspace plugin

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
* read default route table name from hints file
* default to `main` table to maintain current behavior
fixes #696
> Allow route table override

- lib/ohai/plugins/linux/block_device.rb
- spec/unit/plugins/linux/block_device_spec.rb
I considered adding `queue_depth` as a custom extension instead of opening this PR since it's not a super common thing to care about. 
Heads up @aww-yiss - these tests could easily be modified to cover your code changes too.
> Add tests and queue_depth to block_device

- lib/ohai/plugins/ec2.rb
- spec/unit/plugins/ec2_spec.rb
This allows us to detect Linux hosts based on the DMI data as it includes amazon specific strings.  The present method of looking for an arp address fails when hosts are in a VPC, which they all are by default now.
> Improve EC2 detection when hint isn't present

- lib/ohai/plugins/packages.rb
- spec/unit/plugins/packages_spec.rb
This is a hack. We can make this into a proper
DSL thing where specifying something like `default_enabled false`.
For now, this could be enabled through
```ruby
ohai[:plugins][:packages][:enabled] = true
```
I want to make sure we don't back ourselves into a situation where we want/need to make a breaking change. This is a possible alternative to completely reverting the change, though I feel it may conflict with the idea of `disabled_plugins`.
> Don't enable packages plugin by default

- lib/ohai/plugins/windows/drivers.rb
Makes the windows `Drivers` plugin opt-in via a config setting, similar to the packages plugin (see: https://github.com/chef/ohai/pull/717 ). This is technically a breaking change, but we decided in this case that the plugin was delivering too much negative value so it's worth it. The plugin can be re-enabled by setting `ohai.plugins[:drivers][:enabled] = true` in the Chef config file.
> Make pnp plugin opt-in via config

- lib/ohai/mixin/dmi_decode.rb
- lib/ohai/plugins/azure.rb
- spec/unit/plugins/azure_spec.rb
Azure has no metadata endpoint and we pass in everything we stick in the mash via the hint, but there's still value in detecting azure when we didn't knife bootstrap. Users still want to do different things on their cloud hosts and this gives them that ability.
1) Detect hosts as being on azure when the waagent is present (windows and linux)
2) Detect hosts as being on azure when we find unknown-245 dhcp option which is used by Azure (linux only)
3) Fix the specs for the lack of hint file or presence of rackspace hint file so they actually run.  This confused me for a while until I realized they were expecting nil and not running the plugin so they got nil. Ouch.
And a bonus commit: switch the order or MS virtualization detection since 99.9% of the time it's hyper-v. No point in checking …
> Detect Azure using the Azure agent and DHCP options

- lib/ohai/plugins/ec2.rb
- spec/unit/plugins/ec2_spec.rb
Official AMIs ship with the ec2metadata binary which we can look for. With this change we should be detecting the majority of scenarios without a hint file.
has_ec2_mac has been renamed has_xen_mac since we're actually looking for a xen mac.  Due to that the attempt to connect to the metadata only needs to happen when we only find the mac address since that can be either AWS or Xen.  If we find dmi data, a hint, or the metadata binary we can safely assume the metadata endpoint will respond.
I also consolidated the "no hints or signs of AWS" scenario into a single spec since it seems to make more sense that way.
> Detect paravirt amazon instances without hint files

- lib/ohai/plugins/java.rb
- spec/unit/plugins/java_spec.rb
This changes the regex to support the openjdk 1.8 version string change.
> OHAI-726 Regex to support openjdk 1.8

- lib/ohai/mixin/command.rb
These aren't used anywhere and seem to be pre-mixlib shellout. They should go away, but for now someone might be using them in a plugin so we'll just throw a warn and then remove them in Ohai 9.
> Deprecate run_command and popen4 in the command mixin

- lib/ohai/plugins/network_listeners.rb
- lib/ohai/plugins/sigar/network_route.rb
These two plugins run on every system and spam debug logs. There are other plugins that use sigar, but they're confined to HPUX where you need sigar for ohai to operate.
> Log sigar gem load failures

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
```
bash-4.3# ifconfig
Gi0_0_0_0 Link encap:Ethernet  HWaddr 52:46:0b:98:d2:51  
inet addr:192.168.122.222  Mask:255.255.255.0
inet6 addr: fe80::5046:bff:fe98:d251/64 Scope:Link
UP RUNNING NOARP MULTICAST  MTU:1514  Metric:1
RX packets:30965 errors:0 dropped:0 overruns:0 frame:0
TX packets:3 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000 
RX bytes:45928110 (43.8 MiB)  TX bytes:210 (210.0 B)
Mg0_RP0_CPU0_0 Link encap:Ethernet  HWaddr 52:46:07:10:c6:14  
inet addr:10.1.1.1  Mask:255.255.255.0
inet6 addr: fe80::5046:7ff:fe10:c614/64 Scope:Link
UP RUNNING NOARP MULTICAST  MTU:1514  Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:3 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000 
RX bytes:0 (0.0 B)  TX bytes:210 (210.0 B)
fwd_ew …
```
> ipaddress on Linux - default route pointing to unaddressed interface, with route src

- .travis.yml
Without this ohai can't handle Chef's need for a newer bundler than
Travis has
> Update bundler in travis to fix broken builds

- lib/ohai/plugins/digital_ocean.rb
- spec/unit/plugins/digital_ocean_spec.rb
IpHelper's loopback? method fails when you pass it a MAC address, so we
should check for this first
> Fix digital ocean ip address detection

- appveyor.yml
- lib/ohai/loader.rb
For ruby >= 2.2, Dir.glob behaves differently than ruby 2.0
and breaks in more places when backslashes are used when globbing.
This means that Windows is sad and will not load any plugins with
Ruby >= 2.2 in a lot of cases. This is the safest thing to do
because it will use forward slashes.
> Use escape_glob_dir instead of escape_glob

- lib/ohai/mixin/ec2_metadata.rb
- lib/ohai/plugins/ec2.rb
- spec/unit/plugins/ec2_spec.rb
Be extra sure we're on EC2 in the first place
Timeout querying the metadata quicker. Without this Ohai runs on Rackspace will take 2 minutes
> Handle mis-identifying Rackspace as EC2 better

- lib/ohai/plugins/linux/sessions.rb
- spec/unit/plugins/linux/sessions_spec.rb
Add a new plugin to expose session information on systemd hosts using loginctl. This could be extended to support consolekit and other backends as well if needed.
I'm a Facebook employee and @jaymzh will do the final merge.
> add plugin to detect user sessions using loginctl

- lib/ohai/plugins/linux/virtualization.rb
- spec/unit/plugins/linux/virtualization_spec.rb
Before we detected KVM hosts via kvm modules, which are actually loaded for both guests and hosts.  Instead use /sys/devices/virtual/misc/kvm to determine if the system is KVM in anyway.  From there look for a hypervisor cpu feature flag to determine if we're a guest.  If that isn't there we're on a host.
> Improve KVM host and guest detection

- lib/ohai/plugins/linux/virtualization.rb
- lib/ohai/util/file_helper.rb
- spec/unit/plugins/linux/virtualization_spec.rb
- spec/unit/util/file_helper_spec.rb
Detect openstack hosts by the presence of the nova binary.
This includes the changes in #750 so ignore everything, but the last commit
> Detect Openstack hosts

- lib/ohai/plugins/virtualization.rb
This is an early plugin that hasn't received any work since it's creation.  I seriously doubt anyone is using it, but this provides some minor cleanup
1) remove the hpricot dependency and all the commented out hpricot code. This plugin would fail unless it was installed, but it's not actually used
2) Stop storing XML data on the node. This is a horrible horrible thing to do. We're storing the exact same data in JSON. Why 2 formats?
3) Change the debug message to make it clean what plugin fails if the gems aren't there
4) Add a comment telling anyone reading this what gem to use.  The libvirt gem is deprecated and fails to load.
It's a bummer we need this gem to use this because the data is actually pretty useful once it's loaded, but I doubt anyone installs the gem.
> Remove XML output in VirtualizationInfo and need for hpricot gem

- lib/ohai/plugins/bsd/virtualization.rb
- spec/unit/plugins/bsd/virtualization_spec.rb
Add debug output for everything we detect
Detect bhyve hosts when /dev/vmm exists (vmm module)
Detect jail hosts with jails in the dying state. They still count
Detect guests with sysctl -n kern.vm_guest output. This detects vmware, xen, hyper-v, and bhyve guests even when dmidecode isn't present (it's not installed by default so big win here)
> Improve FreeBSD guest virtualization detection

- lib/ohai/mixin/dmi_decode.rb
- lib/ohai/plugins/solaris2/virtualization.rb
- spec/unit/plugins/solaris2/virtualization_spec.rb
Detect additional paravirt KVM CPU strings:
- Common KVM processor
- Common 32-bit KVM processor
Use the same node[:virtualization][:systems] multiple virtualization system attribute structure we use on other systems
Use our shared DMI Decode library for detection virtualization systems. This adds detection for Solaris running on the following systems:
- VirtualBox
- OpenStack
- Hyper-V
- KVM
- Xen
- VirtualServer
> Improve virtualization detection on Solaris

- lib/ohai/mixin/gce_metadata.rb
- spec/unit/plugins/gce_spec.rb
Use the non-beta metadata URL. This requires setting the header on all requests so there's a bit of changes to how the http connection is initialized
Fail better if the google internal DNS name can't be resolved
> Update GCE metadata API version and fail better

- ohai.gemspec
Something in our Rakefile is using a deprecated API, but it doesn't seem to be breaking anything:
```
bundle exec rake -T
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
rake build               # Build ohai-8.12.0.gem into the pkg directory
rake changelog           # Generate a Change log from GitHub
rake clean               # Remove any temporary products
rake clobber             # Remove any generated files
rake install             # Build and install ohai-8.12.0.gem into system gems
rake install:local       # Build and install ohai-8.12.0.gem into system gems without network access
rake release[remote]     # Create tag v8.12.0 and build and push ohai-8.12.0.gem to …
```
> Rake is a dev dep

- Gemfile
When ohai is `bundle installed` without the development group, bundler
doesn't install the development gems but it still includes them in the
gemfile solution. When chef-client is on an unreleased version, this
results in the unreleased version of chef-client ending up in the
Gemfile.lock. Because chef-client has an exact equality pin on
chef-config, which ohai also uses, this results in ohai's Gemfile.lock
pinning ohai to the unreleased version of chef-config. When the ohai
executable is created by appbundler, this results in a broken executable
that tries to load a version of chef-config that doesn't exist.
> Don't pull chef from master

- ohai.gemspec
Both 3.1 and 3.2 seem to work. Currently Chef is pinned to 3.1.x, so I
set the pin there to avoid conflict with Chef.
> Lock plist to 3.x

- lib/ohai/plugins/packages.rb
- spec/unit/plugins/packages_spec.rb
Windows packages plugin uses Win32_Product WMI class to get list of installed packages. This causes  reconfiguration of all installed windows packages in win2008r2/win2012r2 as per https://support.microsoft.com/en-us/kb/974524, spewing windows event log with 'Package reconfigured messages'. The PR removes the query to Win32_Product WMI class  and uses windows registry to get list of all installed packages.
cc @johnbellone
> Windows packages plugin - Get packages from registry

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
It's different then opensuse or suse.  Platform family is still suse.
This is a modified version of #745 based on the discussion in the PR
> Detect openSUSE Leap as platform opensuseleap

- lib/ohai/plugins/ec2.rb
- spec/unit/plugins/ec2_spec.rb
It's not a reliable detection method
> Remove ec2metadata CLI as a EC2 detection method

- lib/ohai/mixin/command.rb
- lib/ohai/plugins/c.rb
- lib/ohai/plugins/rackspace.rb
- spec/unit/mixin/command_spec.rb
- spec/unit/plugins/c_spec.rb
- spec/unit/plugins/rackspace_spec.rb
Modify ohai's shell_out to provide basic logging of command exit status and failures. Adds a default 30s timeout to all commands. 
Replaces https://github.com/chef/ohai/pull/732
> Ohai shell_out logging, timeouts, and error handling

- lib/ohai/plugins/solaris2/network.rb
- spec/unit/plugins/solaris2/network_spec.rb
PHYSRUNNING is now a valid flag for an interface.
The Solaris 11 zones "route -n get default” command output returns the
interface name, net0, but not the specific instance net0:2. The output
changed from Solaris 10 to Solaris 11. Use the verbose output
"route -v -n get default" to find the interface index and use the
name and index to find the full interface name from the ifconfig -a
output.
OHAI network is sort of incomplete for solaris 11 zone network interfaces.  The flags are not reported because PHYSRUNNING might be in the status.   The default_ipaddress isn't returned because output from the "route -n get default" command changed between solaris 10 and solaris 11.   
I changed a couple of things to fix default rubocop alerts before I figured out chef-style. The modules do pass …
> solaris11_network: Handle solaris 11 zone interfaces

- lib/ohai/plugins/ec2.rb
- spec/unit/plugins/ec2_spec.rb
Remove the Xen MAC address detection method, which we previously deprecated
Detect Windows hosts based on Kernel owner information
Detect Linux hosts based on the Xen UUID starting with ec2
> Improve Linux EC2 detection, fix false detection, and add Windows detection

- lib/ohai/hints.rb
- spec/unit/plugins/azure_spec.rb
- spec/unit/plugins/digital_ocean_spec.rb
- spec/unit/plugins/ec2_spec.rb
- spec/unit/plugins/eucalyptus_spec.rb
- spec/unit/plugins/gce_spec.rb
- spec/unit/plugins/linode_spec.rb
- spec/unit/plugins/rackspace_spec.rb
- spec/unit/plugins/softlayer_spec.rb
Adds some basic logging to .hint? and breaks up a large method before making it even larger with debug logging.  Also cleanup how we test  use of hints.  We're already testing the Hint class in its own spec.  There's no need to mock out hint files on the filesystem and test it again in each cloud provider. Instead we should just mock the call to the hint? method itself and save some time. While I was in there I cleaned up the specs, improved some wording, and removed a bunch of specs that didn't actually work.
> Add debug logging to hints and improve cloud specs

- lib/ohai/plugins/c.rb
- spec/unit/plugins/c_spec.rb
This fixes an issue where evaluating the C plug-in causes Windows to issue spurious DNS calls because the file path can get evaluated as a UNC in some cases.  We should not be trying to shell out and execute .so files in a non-Unix environment.
> Don't execute .so libs for Windows

- lib/ohai/plugins/scala.rb
- spec/unit/plugins/scala_spec.rb
There were several problems with the scala plugin:
1) scala -version is returned on stderr not stdout so we were never setting this and thus the plugin never ran
2) If sbt or scala weren't installed it threw exceptions
3) we were storing shell outs return in the output value for no real reason
4) if scala failed for some reason, but sbt succeeded we weren't setting the sbt values since were relied on scala[:version] being set
5) the specs incorrectly mocked scala output to stdout
6) the specs that checked to make sure values weren't set didn't actually run the plugin so they would always no find scala's key
While I was here I moved the version key for sbt into it's own key.  This would allow us to add other sbt values in the future if we found them. If we make version to top level value …
> Fix the scala plugin

- lib/ohai/plugins/mono.rb
- spec/unit/plugins/mono_spec.rb
We weren't capturing the builddate right based on the latest output.  I don't have an example of the old output to know if something changed or if this ever worked right.  We didn't have specs that included the data or a check for the attribute.  Those are added now.
> Fix mono builddate capture and add debug logging

- lib/ohai/plugins/elixir.rb
- spec/unit/plugins/elixir_spec.rb
Add specs for the new format + error logging + general fixes
Old output that incorrectly identifies the Erlang version as the Elixir version:
```javascript
"languages": {
"elixir": {
"version": "18"
},
```
New correct output:
```javascript
"languages": {
"elixir": {
"version": "1.2.4"
},
```
> Fix Elixir version detection on newer Elixir releases

- lib/ohai/plugins/erlang.rb
- spec/unit/plugins/erlang_spec.rb
We weren't correctly identifying the erlang version.  Instead we were detecting the erts version.
Old result:
```javascript
"erlang": {
"version": "7.3",
"options": [
"SMP",
"ASYNC_THREADS",
"HIPE"
],
"emulator": "BEAM"
},
```
New result
```javascript
"erlang": {
"version": "18",
"erts_version": "7.3",
"nif_version": "2.10",
"options": [
"SMP",
"ASYNC_THREADS",
"HIPE"
],
"emulator": "BEAM"
},
```
> Correct the version detection in erlang plugin

- lib/ohai/plugins/packages.rb
This has the added benefit of preventing a very very very very large number of warnings in test output once https://github.com/chef/chef/pull/4841 is merged. So we'll need to do a patch release.
> Avoid defining WINDOWS_ATTRIBUTE_ALIASES multiple times

- lib/ohai/dsl/plugin.rb
- spec/unit/dsl/plugin_spec.rb
Resolves https://github.com/chef/ohai/issues/794 by extending the `attribute?` and `get_attribute` DSL methods to apply to sub-attributes. Attributes can be specified as a `/`-delimited string, a list of string keys, a list of symbol keys, or a combination thereof.
Open to suggestions like:
1) Only supporting a list of strings and symbols (get rid of that `/`-delimiter stuff, that's too fancy)
2) Adding similar support to `set_attribute` in this PR (was gonna do it separate since the implementation is different).
3) ___________________________________________________________________________.
> Safely get or check the existence of attributes

- lib/ohai/plugins/c.rb
- lib/ohai/plugins/elixir.rb
- lib/ohai/plugins/go.rb
- lib/ohai/plugins/groovy.rb
- lib/ohai/plugins/java.rb
- lib/ohai/plugins/lua.rb
- lib/ohai/plugins/mono.rb
- lib/ohai/plugins/nodejs.rb
- lib/ohai/plugins/perl.rb
- lib/ohai/plugins/php.rb
- lib/ohai/plugins/powershell.rb
- lib/ohai/plugins/python.rb
- lib/ohai/plugins/ruby.rb
- lib/ohai/plugins/rust.rb
- lib/ohai/plugins/scala.rb
- spec/unit/plugins/erlang_spec.rb
- spec/unit/plugins/go_spec.rb
- spec/unit/plugins/groovy_spec.rb
- spec/unit/plugins/java_spec.rb
- spec/unit/plugins/lua_spec.rb
- spec/unit/plugins/mono_spec.rb
- spec/unit/plugins/nodejs_spec.rb
- spec/unit/plugins/perl_spec.rb
- spec/unit/plugins/powershell_spec.rb
- spec/unit/plugins/python_spec.rb
it's a big change, but it's basically the same thing over and over again for each plugin
> Language plugins: Improve failure logging, update specs, general cleanup

- lib/ohai/application.rb
- lib/ohai/loader.rb
- lib/ohai/system.rb
- spec/unit/dsl/plugin_spec.rb
- spec/unit/loader_spec.rb
Pretty simple stuff here. Add the plugin paths and the discovered plugins to debug logging. Add the config too so you can see where we're getting the paths from.  Then if you pass in a bogus dir make sure we warn instead of silently continuing like we do now.
> Extra debug logging and error handling in plugin loading

- spec/unit/plugins/darwin/virtualization_spec.rb
This spec was taking 1.8 secs since it was looking for this binary in
all the specs.  Now it takes .282 secs.
> Prevent parallels spec from checking the filesystem

- spec/unit/plugins/linux/virtualization_spec.rb
This adds a spec to the work in #786
> Add detection of bhyve guests running Linux/*BSD

- lib/ohai/plugins/cloud.rb
- lib/ohai/plugins/cloud_v2.rb
- lib/ohai/plugins/openstack.rb
- spec/unit/plugins/openstack_spec.rb
The existing Openstack metadata logic failed as it was hardcoded to use metadata from 2013 that doesn't seem to exist in standard installs. Instead lets use the logic in the EC2 metadata mixin to find the latest version we support.
Wrap metadata fetching around  socket connection check from the EC2 metadata plugin. This prevents hung Ohai runs on providers that don't support the metadata endpoint
Grab the Openstack data correctly in the Cloud plugins
Detect a system as being on Openstack based on DMI data
Remove HP cloud logic since that's dead
Add debug logging so we can follow what's happening in the logs better
Previously nil data we now have:
```json
"cloud": {
"public_ips": [
"172.16.20.52"
],
"private_ips": [
"192.168.1.203"
],
"public_ipv4": "172.16.20.52",
"public_hostname": …
```
> Properly poll Openstack detection + other Openstack improvements

- lib/ohai/plugins/kernel.rb
- spec/unit/plugins/linux/kernel_spec.rb
Hi,
I wonder if getting the module version for linux in the 'kernel.modules' could be possible?
I have created the Pull Request to get those.
Let me know if it is good feature or not.
Regards,
JM
> Adding version for linux module when avalaible

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
We're looking at the gentoo release file to identify the version currently which is 2.2. It's been 2.2 for years since that's just the Gentoo Base System version which never changes. We should do what we do on Arch and use the kernel version string.  This is a copy / paste of that code.
> Switch to kernel version to identify Gentoo versions

- lib/ohai/plugins/ec2.rb
- lib/ohai/plugins/openstack.rb
Use get_attribute to simplify code in places where we previously had to rescue NoMethodError
> Cleanup attribute access in cloud plugins

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
Extend the network plugin to expose interface ring parameters using ethtool.
I'm a Facebook employee and @jaymzh will do the final merge.
> expose ring parameters in the network plugin

- lib/ohai/plugins/timezone.rb
- spec/unit/plugins/timezone_spec.rb
We have an internal plugin where we are doing the same thing, and we were a little surprised that this didn't exist yet. I didn't think there was a better namespace place to shove this under.
> Add a simple plugin to get the local timezone.

- Gemfile
- lib/ohai/plugins/powershell.rb
- spec/unit/plugins/powershell_spec.rb
> Update PowerShell Version Compat Detection / Unblock bundler on Appveyor

- lib/ohai/plugins/timezone.rb
- spec/unit/plugins/timezone_spec.rb
This prevents us from breaking the various timezone cookbooks that
already use that namespace. Attributes are hard. Good thing lamont is
going to fix this all ;)
> Move timezone value under time

- .travis.yml
- ohai.gemspec
Also test on more specific Ruby versions since the rbenv aliases don't
point to current.
> Remove support for Ruby 2.0

- lib/ohai/plugins/php.rb
- spec/unit/plugins/php_spec.rb
PHP 7 strings have changed and our old regex broke as the build date is no longer included. Update the regex to make the build data optional and add tests for the new strings
> Properly detect PHP 7

- lib/ohai/dsl/plugin.rb
- lib/ohai/plugins/bsd/virtualization.rb
- lib/ohai/plugins/darwin/virtualization.rb
- lib/ohai/plugins/linux/sessions.rb
- lib/ohai/plugins/linux/virtualization.rb
- lib/ohai/plugins/solaris2/virtualization.rb
> Avoid global mutation.

- lib/ohai/plugins/shells.rb
- spec/unit/plugins/shells_spec.rb
The exact shell paths vary by OS so it would be really nice to have a list of the shells so you could find the path to bash by walking the array.
> Add a plugin for collecting available shells

- lib/ohai/plugins/solaris2/network.rb
- spec/unit/plugins/solaris2/network_spec.rb
The current regex in place does not properly catch the interfaces. Updating this regex allows for the network information to actually populate.
> fixing solaris2 ohai plugin regex

- ohai.gemspec
- spec/spec_helper.rb
Bump github changelog generator the the latest, constrain rack to < 2 and fix a require in the spec helper that is causing failures in rspec 3.5. Get the build green again basically
> Fix installs on Ruby 2.1 and rspec testing with rspec 3.5

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
Arista EOS can be detected based on the /etc/Eos-release file which includes the EOS version string.
> Add platform detection for Arista EOS

- ohai.gemspec
Our use of the configured method now fails if we're not on 1.7.1.
> Require at least mixlib-log 1.7.1

- lib/ohai/plugins/windows/network.rb
Windows Nano exposes the Win32_* WMI classes but they are empty. Instead we should populate network metadata from the newer MSFT_* classes. This PR will continue to use the deprecated classes if they have data and use the new ones if they are empty.
Note that the data in these new schemas is slightly different but I have tried to make the data exposed in the network interfaces as close to identical to that exposed on other versions of windows. Attempts to get an IP address will succeed but some of the subnet metadata is missing since I could not find that in the new classes.
I think this is a good first stab and we should fill in missing data later if needed. The primary objective here is to allow chef client runs to work and not raise an error when trying to use the node's IP.
> Retrofit network plugin to work on Windows Nano Server

- lib/ohai/plugins/linux/virtualization.rb
- spec/unit/plugins/linux/virtualization_spec.rb
Similar to [857](https://github.com/chef/ohai/pull/857/filesl) i.e detect lxd using [/dev/lxd](https://github.com/lxc/lxd/blob/master/doc/dev-lxd.md).  
I have added tests as well as code to say that the current host is an lxd host.
> Detect lxd

- lib/ohai/plugins/kernel.rb
- spec/unit/plugins/solaris2/kernel_spec.rb
Extract the Solaris version update information from /etc/release.
The solaris version update information is not reported by Ohai.  Chef is making decisions about chef-client support based on the version update of the solaris os.   Reporting the os information might make it simpler to find older servers that need to be upgraded.
> Solaris_update_version: Create kernel[:update] for solaris 2

- lib/ohai/plugins/uptime.rb
- spec/functional/plugins/windows/uptime_spec.rb
- spec/unit/plugins/windows/uptime_spec.rb
Ohai uptime plugin hangs in Windows, solution:
1. Changed WMI class to `Win32_OperatingSystem` for newer versions of Windows.
2. Kept the old WMI class `Win32_PerfFormattedData_PerfOS_System` for older versions of Windows.
WMI class is from where we retrieve the system's uptime for Windows platform.
> Ohai uptime plugin hangs in Windows.

- lib/ohai/plugins/shard.rb
- spec/unit/plugins/shard_spec.rb
This adds a shard_seed that people can then shard on ala:
```
def in_shard(node, shard, shard_size)
node['shard_seed'] % shard_size <= shard
end
```
Which then enables:
```
if in_shard(node, 4, 100)
else
end
```
Which is roughly how we shard things. Other code to utilize this to follow.
> Add shard plugin

- lib/ohai/plugins/hostname.rb
This pull request mimics the code from `:linux`.
The current assumption on darwin machines is that there is an entry located in /etc/hosts. Given that most darwin machines are client devices, this more than likely is incorrect.
Issues that this can cause:
- ohai returns a value of `null` in the JSON. In my testing only the fqdn attribute will return this as a value.
- When uploading `null` data to a postgresql database, you will experience table issues.
This change drops the fqdn value if a hostname is not properly returned, but still returns a valid entry if there is an entry in /etc/hosts.
> Add logic to darwin hostname

- lib/ohai/plugins/linux/lsb.rb
- spec/unit/plugins/linux/lsb_spec.rb
There isn't and has never been mention of /etc/lsb-release in the
official LSB universe. The "correct" way to discover LSB data is with
lsb_release, so this uses that facility first, before falling back to
oddball support.
Without this change, some upgraded boxen will have the wrong results
because an outdated /etc/lsb-release may have been left behind with
different contents than what would come from the lsb_release util.
See:
http://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/lsbrelease.html
http://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/etc.html
> Prefer the LSB standard configurator.

- Gemfile
- ohai.gemspec
This removes the need for Rack 1.X which we had to pin due to the old github changelog generator release. We now have a new active support pin to keep Ruby 2.1 support
> Move dev deps to the Gemfile and bump changelog generator

- spec/spec_helper.rb
- spec/support/platform_helpers.rb
> Remove Ruby 1.8 / 1.9 spec helpers

- lib/ohai/plugins/ip_scopes.rb
- spec/unit/plugins/ip_scopes_spec.rb
This modification prevents ip_scopes plugin to return 'tunl' or 'docker' type interfaces' ipaddress as privateaddress.
> ip_scopes update

- lib/ohai/dsl/plugin.rb
- spec/unit/dsl/plugin_spec.rb
Use:
- set_attribute(:attr, value) assigns attribute 'attr' value.
- set_attribute(:attr, :subattr, value) assigns attribute 'attr/subattr' value. Extends to subattributes of arbitrary depth.
Raises a TypeError if some :subattr is not an Array, Hash, or Mash (e.g., a String value).
@tas50
> Extend set_attribute to set sub-attributes.

- lib/ohai/plugins/haskell.rb
- spec/unit/plugins/haskell_spec.rb
splitting fields is fragile. Use a regex instead and add a spec for both
formats.
> Handle the non-git built haskell stack version shellout format

- lib/ohai/plugins/joyent.rb
- spec/unit/plugins/joyent_spec.rb
This builds on the work that @bahamas10 did in #499. It fixes up the specs to provide proper testing of the logic of the plugin and based on those specs makes some additional fixes to the plugin.
> Rework / fix logic in the joyent plugin and improve specs

- lib/ohai/plugins/joyent.rb
- condense code
- touch up style
- don't stat(2) before open(2)
> cleanup joyent.rb

- lib/ohai/plugins/erlang.rb
- spec/unit/plugins/erlang_spec.rb
Pull the complete version string of Erlang
Improve the shellout with help of StackOverflow and srenatus. This requires less fragile work in Ruby by formatting the data in erlang properly.
> Pull the complete version string of Erlang

- lib/ohai/plugins/sysconf.rb
- spec/unit/plugins/sysconf_spec.rb
Add a new plugin to expose system configuration variables. See `man sysconf` and `man getconf` for what this is about, the tl;dr is that it exposes a number of system-level variables that are useful to understand what kind of machine or system we're running on. For example, the `LONG_BIT` variable is the only reliable way to determine whether we're running a 32bit userspace on top of a 64bit kernel. This interface is defined by POSIX and should be available on all UNIX-like OS. I tested this on Linux, but verified the interface is documented as available on AIX, Solaris, Darwin, BSD, IRIX and HP-UX.
Signed-off-by: Davide Cavalca <dcavalca@fb.com>
> Add sysconf plugin to expose system configuration variables

- Gemfile
This version of the changelog generator addresses a few issues with the
upstream one. In addition, it has a less restrictive dependency on
Retriable, which can cause conflict when Ohai is installed in ChefDK.
* ChefDK builds failing
Signed-off-by: Tom Duffield <tom@chef.io>
> Use custom changelog generator

- lib/ohai/mixin/ec2_metadata.rb
- lib/ohai/plugins/ec2.rb
- spec/unit/plugins/ec2_spec.rb
In addition to meta-data and userdata EC2 also provides "dynamic" data (not sure why it's called dynamic though). One extra useful attribute that it has, and that seems to be not available in other sources, is AWS account id (try running curl http://169.254.169.254/latest/dynamic/instance-identity/document). It is possible to fetch account id from the instance that has IAM role attached (by parsing ARN of the role) but for instances without any IAM role this dynamic data is the only way to figure out to which account it belongs to.
> Fetch AWS Account ID from metadata

- lib/ohai/plugins/windows/virtualization.rb
- spec/unit/plugins/windows/virtualization_spec.rb
This change allows Windows guest systems to detect the virtualization platform when running on both Hyper-v and Xen.
#664 
- [ X] New functionality includes tests
- [ X] All tests pass
- [ X] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
Signed-off-by: Bob Dean <radean@hotmail.com>
> Windows guest support on Hyper-v and Xen.

- RELEASE_NOTES.md
- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
Detect cumulus Linux systems if they have /etc/cumulus directory. Use platform of ‘cumulus’ and platform_family debian since it’s Debian 8.5. Parse version from their config directory.
N/A
> Properly detect Cumulus Linux platform / version

- lib/ohai/plugins/azure.rb
- lib/ohai/plugins/c.rb
- lib/ohai/plugins/dmi.rb
- lib/ohai/plugins/groovy.rb
- lib/ohai/plugins/haskell.rb
- lib/ohai/plugins/hostname.rb
- lib/ohai/plugins/ip_scopes.rb
- lib/ohai/plugins/linux/network.rb
- lib/ohai/plugins/linux/sessions.rb
- lib/ohai/plugins/linux/virtualization.rb
- lib/ohai/plugins/lua.rb
- lib/ohai/plugins/network.rb
- lib/ohai/plugins/scala.rb
- lib/ohai/plugins/solaris2/dmi.rb
- lib/ohai/plugins/virtualbox.rb
- lib/ohai/plugins/vmware.rb
- lib/ohai/util/file_helper.rb
- spec/unit/plugins/linux/network_spec.rb
- spec/unit/plugins/network_spec.rb
Gracefully fail in virtual box
Include plugin name in more logs
Be consistent in the log output format
Help figure out how Virtualization systems were detected with logging
> Better debug logging

- .travis.yml
Test ruby 2.2.6 and 2.3.3 and now ruby-head, which is allowed to fail
> Bump ruby versions and test on ruby head

- lib/ohai/plugins/cloud.rb
- spec/unit/plugins/cloud_spec.rb
Updates the cloud plugin to populate the node['cloud']['private'] ip array from the azure mash. 
None created
> updating cloud plugin to populate azure private_ip as it's currently nil

- lib/ohai/application.rb
- lib/ohai/system.rb
- spec/unit/system_spec.rb
When we're running Ohai as a standalone application, we need to fire up
the logger with our desired location, but when we're run from inside
Chef, we're passed the client's loggers.
( https://github.com/chef/chef/blob/master/lib/chef/application/client.rb#L398 )
Fixes: #878
> Only explicitly initialize a logger when needed

- RELEASE_NOTES.md
- lib/ohai/plugins/c.rb
- spec/unit/plugins/c_spec.rb
Builds on the work that @erikng did in #941 
Additions:
Rework the specs to be per platform and remove some the guards that existed for *nix plugins on Windows
Add more useful fields to the gcc data
Use the same logging format everywhere
Add specs for the xcode change and rework other specs to run per platform
> C Plugin: Expand GCC data & only shellout to gcc if Xcode is installed on macOS

- .travis.yml
- Gemfile
- appveyor.yml
- ohai.gemspec
chef/chef already requires Ruby 2.2. We've removed support for Ruby 2.1
in our other projects and community tooling.
I think this is a pretty minor impact, but we can wait till Ohai 13 in April if we want.
> Require Ruby 2.2+

- lib/ohai/plugins/windows/cpu.rb
- spec/unit/plugins/windows/cpu_spec.rb
Use the "name" value for the model_name, and move description to the
description field.
* COOL-626
* Fixes #904 
Signed-off-by: Tom Duffield <tom@chef.io>
> Use name for Windows CPU model_name

- lib/ohai/config.rb
- lib/ohai/system.rb
- spec/functional/application_spec.rb
- spec/unit/config_spec.rb
- spec/unit/system_spec.rb
Start of the deprecation of the old config logic. Removes a ton of confusing duplicate logic and resolves 2 bogus deprecation warnings that were thrown every time Ohai ran. Specs are going to need to be cleaned up still.
Also bonus gift: This adds /etc/chef/ohai/plugins to the plugin path so the ohai_plugin resource will work without configuration mess by the user now. I'll probably port that same 1 line fix over to Ohai 8.X so we can get that in for Chef 12 users.
> Remove deprecated config logic

- .travis.yml
- appveyor.yml
- ohai.gemspec
This same change was made in chef/chef to fix failures
> Update travis/appveyer preinstall to resolve rainbow failures

- spec/unit/plugins/darwin/system_profiler_spec.rb
There’s no need for this and we’re not doing this in the dozen other places we load deps.
> Remove rescue loading plist in the specs as this is a dep

- lib/ohai/system.rb
COOL team found this when using ohai/system directly. It worked in 8.X, but not post deprecation of the old config logic.
> Config is used in system so require it there.

- lib/ohai/mixin/ec2_metadata.rb
- lib/ohai/mixin/gce_metadata.rb
- lib/ohai/mixin/http_helper.rb
- lib/ohai/plugins/ec2.rb
- lib/ohai/plugins/gce.rb
We probably want to use this in a few other places, but we certainly want to encourage people to use this in their plugins vs. reinventing the wheel.
> Move duplicate http logic into a helper

- lib/ohai/application.rb
- lib/ohai/log.rb
- lib/ohai/system.rb
- spec/unit/system_spec.rb
fix ohai logger problems.
i believe this gets the logic correct in that we want to configure the
logger when we're coming from the command line but want to skip it when
we're coming from chef or from other APIs that directly construct an
Ohai::System object.
i suspect this is what thom was trying to do by moving the
Ohai::Log.init call into the Ohai::Application class (which avoids it
being called entirely when Chef creates its Ohai::System object) here:
https://github.com/chef/ohai/pull/942/files
but that change broke the behavior where we were also supposed to skip
the rest of the configure_logging method in Ohai::System when run under
chef client.
I tried going down the route of having the Ohai::Application class
construct the Ohai::System object and then having it be the …
> fix logger issues

- lib/ohai/mixin/do_metadata.rb
- lib/ohai/plugins/cloud.rb
- lib/ohai/plugins/digital_ocean.rb
- spec/unit/plugins/cloud_spec.rb
- spec/unit/plugins/digital_ocean_spec.rb
At the moment we rely on hint data from our digital ocean knife plugin.  Not everyone boostraps with knife though.  Instead of relying on the hint data we should detect digital ocean nodes via DMI or hint file and then fetch all the DO metadata from their API. This builds on the original PR from @GenPage but adds detection of DO droplets via DMI data and updates the cloud plugins.
> Add Digital Ocean metadata from their metadata API

- lib/ohai/plugins/scala.rb
It seems that sometimes scala outputs a bogus line ahead out the version output. Use a match instead of a split to better handle this sort of thing.
> Fix scala detection when version output contains a warning

- lib/ohai/plugins/lua.rb
- spec/unit/plugins/lua_spec.rb
Newer versions of lua output lua -v on stdout while older versions use
stderr. This update will handle both and ensure that we continue to
detect the installed lua version.
> Fix lua detection on new versions of lua

- lib/ohai/plugins/ec2.rb
- spec/unit/plugins/ec2_spec.rb
Include the region and availability zone as information retrieved from the identity document. Since it's already fetching the identity document to retrieve the account id, this just adds the additional info from the same source.
[Other properties](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html?shortFooter=true) could also be included but these were the two I needed most.
None that I know of
> [ec2] Add additional data from identity document

- lib/ohai/common/dmi.rb
These have been added in the last few years it appears
> Add DMI type 40,41, and 42 from the latest man page

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
i think we've finally decided not to move amazon to fedora in #960
i still think everyone is wrong, but i got my `fedora_derived?`
chef-sugar helper so its a mute point now...
https://github.com/chef/chef-rfc/pull/252
> add amazon platform_family

- lib/ohai/system.rb
- spec/unit/system_spec.rb
This both helps avoid weird mutation bugs and saves a bit of RAM. This does not freeze the hashes or arrays so replacement and whatnot should all work the same. Anyone doing in-place mutation of Ohai strings on purpose is getting what they deserve IMO.
Refs https://github.com/chef/chef/issues/4930 for original discussion.
> Freeze all string values coming out of Ohai.

- lib/ohai/plugins/scala.rb
- spec/unit/plugins/scala_spec.rb
30 seconds is way too high here. On my mac the sbt command fails (a whole different issue), but we take 30 seconds to skip the plugin. There’s no reason to wait 30 seconds here for a plugin that doesn’t need that.
> Shorten the sbt shellout timeout period

- lib/ohai/plugins/cloud.rb
- spec/unit/plugins/cloud_spec.rb
This is necessary is someone wants to disable the plugin. They shouldn’t have to use the old name that we’ll be killing off with Chef 14.
> Fully rename the cloud_v2 plugin to cloud

- lib/ohai/loader.rb
- lib/ohai/system.rb
- spec/unit/loader_spec.rb
- spec/unit/system_spec.rb
This is in support of RFC 59, which allows us to add an ohai cookbook
segment and load plugins automatically
cc @chef/maintainers
> Allow ohai to load a plugin path

- .travis.yml
- appveyor.yml
- ohai.gemspec
2.2 just went into security only support mode. Ohai 13 would be the
opportune time to drop support.
> Require Ruby 2.3+ to match Chef itself

- lib/ohai/plugins/scala.rb
- spec/unit/plugins/scala_spec.rb
sbt --version isn't a command anymore and sbt about tries to initialize
a project which downloads files and times out during detection.
> Remove sbt version detect as it's not possible in the current sbt

- lib/ohai/plugins/dmi.rb
This gets us non-exploding output on Linux systems now. This was the
last plugin.
> Rescue exception in DMI plugin

- lib/ohai/plugins/openstack.rb
- spec/unit/plugins/openstack_spec.rb
"can_metadata_connect?" has been renamed to "can_socket_connect?" and
moved into the HttpHelper mixin. (#951)
This patch fixes OpenStack plugin to use the HttpHelper mixin.
N/A
> Fix OpenStack plugin to use the HttpHelper mixin

- lib/ohai/plugins/eucalyptus.rb
"can_metadata_connect?" has been renamed to "can_socket_connect?" and
moved into the HttpHelper mixin. (#951)
See also: #986
N/A
> Fix Eucalyptus plugin to use the HttpHelper mixin

- lib/ohai/plugins/linux/mdadm.rb
- spec/unit/plugins/linux/mdadm_spec.rb
It's useful to actually know the setup of the array.
the mdadm plugin doesn't report member devices... but it should.
Now it does.
> [mdadm] Fill in member devices

- lib/ohai/mixin/command.rb
- spec/unit/mixin/command_spec.rb
Ohai network plugin for Linux fails to collect network related attributes
when networking commands like ip, route, ifconfig and arp are not in the $PATH.
#990
> Inject sane paths into shell_out

- lib/ohai/mixin/ec2_metadata.rb
This adds the following data:
network/interfaces/macs/mac/ipv6s
network/interfaces/macs/mac/subnet-ipv6-cidr-blocks
network/interfaces/macs/mac/vpc-ipv4-cidr-blocks
network/interfaces/macs/mac/vpc-ipv6-cidr-blocks
> Add support for the 2016 EC2 metadata releases

- lib/ohai/mixin/ec2_metadata.rb
- spec/unit/plugins/ec2_spec.rb
- spec/unit/plugins/eucalyptus_spec.rb
- spec/unit/plugins/openstack_spec.rb
There's a few changes here so far.
Better logging when we reject a version that Amazon says they support
Drop our timeouts to a more reasonable time. These APIs are crazy fast there's no need to wait 30 seconds
Only setup the http client object once and use methods that allow connection reuse
Don't parse the best API version 3 times
Add all current EC2 metadata versions
> Improvements to EC2 metadata handling

- CHANGELOG.md
- Gemfile
- lib/ohai/config.rb
- lib/ohai/loader.rb
- lib/ohai/plugins/linux/mdadm.rb
- lib/ohai/version.rb
- spec/unit/loader_spec.rb
- spec/unit/plugins/linux/mdadm_spec.rb
This hand backports chefstyle and the plugin path changes and includes a nice artisanal changelog since the generator falls over in a stable branch sort of situation
> Additional backports + Release 8.24.0

- .gitignore
- Gemfile
people that want pry need to explicitly include it in their own Gemfile.local now.
also creates groups so that we can exclude gems that we don't necessarily need to test
> clean up and prune dev gems

- lib/ohai/plugins/solaris2/zpools.rb
- lib/ohai/plugins/zpools.rb
- spec/unit/plugins/zpools_spec.rb
This plugin works on Linux/BSD for the most part. Let's do the extra work to get there.
Caveats:
The regex is still less than ideal here. Since zpool status for a zpool lists the zlevel and the volume itself along with the drives it's a bit tricky to extract just the drive information. We're relying on the starting characters to identify drives. So we're saying a line that starts with C is a drive on solaris, SD on Linux, and DA/AD on BSD. What happens if my volume is called "crap"? Well that would show up as a drive. That bug has always existed and this doesn't change that. We can use -P on Linux to get the full path which fixes this for Linux, but that doesn't exist on Solaris/BSD (of course).
> Update zpools plugin to work on Linux/BSD

- lib/ohai/plugins/darwin/cpu.rb
- spec/unit/plugins/darwin/cpu_spec.rb
It's 13% slower to do individual shell outs.
> Run sysctl only once on Darwin to determine CPU data

- lib/ohai/plugins/darwin/hardware.rb
- spec/unit/plugins/darwin/hardware_spec.rb
Avoid 2 extra shell_outs by just parsing the fields. This makes the plugin 6% faster
> Only shellout to sw_vers in darwin hardware once

- lib/ohai/plugins/linux/cpu.rb
- spec/unit/plugins/linux/cpu_spec.rb
Signed-off-by: Davide Cavalca <dcavalca@fb.com>
On arm64 the format of `/proc/cpuinfo` is different. This change adds basic support to expose `features` and `bogomips`, which are the most useful fields. Note that these fields are per-processor, while on S390 they're only set once, so we can't really reuse that logic.
None that I could find, though I can file one if needed
- [] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
> cpu: add support for arm64 cpuinfo fields

- lib/ohai/plugins/linux/mdadm.rb
- spec/unit/plugins/linux/mdadm_spec.rb
Read-only and other things can change the output. Be more careful.
The plugin used to crash in a variety of cases and it now does not.
- [X ] New functionality includes tests
- [ X] All tests pass
- [X ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
> fix mdadm plugin when arrays are in interesting states.

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
We're doing something very similar to which in these methods. We should just use which directly and avoid a bit more complexity. This also avoids a few file stats that occurred with the previous setup.
Signed-off-by: Tim Smith <tsmith@chef.io>d
> Find network binaries with the which helper

- lib/ohai/plugins/linux/systemd_paths.rb
- spec/unit/plugins/linux/systemd_paths_spec.rb
Add a simple plugin to expose system and user paths from `systemd-path` (see https://www.freedesktop.org/software/systemd/man/systemd-path.html for details) so they can be consumed from chef.
N/A
> Add systemd_paths plugin for system and user paths

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
as of 6.1.0 clearos is RHEL family-ish. 
https://github.com/chef-cookbooks/chef-client/issues/494
> Add clearos platform to RHEL platform_family

- lib/ohai/plugins/linux/mdadm.rb
- spec/unit/plugins/linux/mdadm_spec.rb
Currently we don't handle inactive arrays correctly, this will do so better.
Tests included.
Inactive arrays reported without members.
> [mdadm] Handle inactive arrays correctly

- Gemfile
- lib/ohai/common/dmi.rb
- lib/ohai/plugins/darwin/platform.rb
- lib/ohai/plugins/dmi.rb
- lib/ohai/plugins/dragonflybsd/network.rb
- lib/ohai/plugins/freebsd/network.rb
- lib/ohai/plugins/linux/network.rb
- lib/ohai/plugins/netbsd/network.rb
- lib/ohai/plugins/openbsd/network.rb
- lib/ohai/plugins/packages.rb
- lib/ohai/plugins/rackspace.rb
- lib/ohai/plugins/solaris2/dmi.rb
- lib/ohai/plugins/solaris2/network.rb
- lib/ohai/plugins/uptime.rb
- lib/ohai/plugins/windows/filesystem.rb
- lib/ohai/plugins/windows/network.rb
- lib/ohai/runner.rb
- lib/ohai/system.rb
- platform_simulation_specs/common/ohai_plugin_common.rb
- spec/unit/plugins/bsd/virtualization_spec.rb
- spec/unit/plugins/netbsd/kernel_spec.rb
- spec/unit/plugins/solaris2/virtualization_spec.rb
This allows us to continue to include recent versions of chef and ohai
in ChefDK 1.x releases, permitting security updates and features.
> Bump up to chefstyle 0.5

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
Set platform and platform_family to 'clearlinux'
on Clear Linux OS nodes.
> Add support for ClearLinux

- lib/ohai/plugins/ip_scopes.rb
2 reasons:
1) It requires a gem we're not installing so no one is actually using this. It's just failing to load during every Ohai run
2) If they do install the gem what they end up if fairly duplicate information to what we already provide in a few of the networking plugins
> Deprecate the IPScopes Plugin

- lib/ohai/plugins/solaris2/network.rb
- spec/unit/plugins/solaris2/network_spec.rb
```# ohai ipaddress ``` returns following warnings and replaces the node IP address with a blank IP
after chef-client run
```
[2017-07-07T20:36:32+00:00] WARN: [inet] no ip address on net0
[2017-07-07T20:36:32+00:00] WARN: unable to detect ipaddress
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.19.1/lib/ohai/system.rb:193:in `attributes_print': I cannot find an attribute named ipaddress! (ArgumentError)
```
Tested this fix on solaris11 client node and verfied IP address was retained after ccr.
Signed-off-by: Jaymala Sinha <jsinha@chef.io>
[Please describe what this change achieves]
> Fix solaris2 ipaddress attribute search

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
They're RHEL + a bunch of secret sauce. Put them in the RHEL platform family, detect the platform properly, and parse the platform version so it doesn't get the RHEL platform version instead.
> Detect F5 Big-IPs as platform bigip

- lib/ohai/plugins/linux/filesystem.rb
- spec/unit/plugins/linux/filesystem_spec.rb
This change increases the default timeout for `lsblk` and `blkid` from 30 seconds to 60 seconds
Ohai was not returning filesystem info for certain machines. After some research/debugging we determined that machines with large amounts of attached LUNs will take longer than 30 seconds to respond with output from `lsblk` and `blkid`. The machines in question here have >1000 LUNs. Bumping the timeout here will ohai to collect the data successfully for machines with these configurations.
> bumping timeout for lsblk and blkid to 60s

- lib/ohai/plugins/linux/cpu.rb
- spec/unit/plugins/linux/cpu_spec.rb
This works around failures to collect core data on SLES <= 12 SP1. We need to support SLES and core counts are used in several of our product cookbooks.
> Handle situations where /proc/cpuinfo lacks core data

- lib/ohai/plugins/aix/uptime.rb
- spec/unit/plugins/aix/uptime_spec.rb
The existing Ohai plugin for returning uptime on AIX machines doesn't account for the year in which the box was booted leading to false positives and negative values
Sample of existing issue
```
Ohai:
--
"uptime_seconds": -4845099,
"uptime": "22 hours 08 minutes 21 seconds",
 
s178 # uptime
09:16AM   up 308 days,  22:10,  4 users,  load average: 7.60, 9.58, 11.85
s178 # who -b
.        system boot Oct 27 11:07
```
> changing method to gather AIX uptime

- lib/ohai/plugins/linux/filesystem.rb
- spec/unit/plugins/linux/filesystem_spec.rb
Add error handling in Linux filesystem plugin for when a command does not exist. 
https://github.com/chef/ohai/issues/1011
> Add error handling in Linux filesystem plugin

- lib/ohai/plugins/ec2.rb
- spec/unit/plugins/ec2_spec.rb
We're currently relying on "amazon" Organization data being present in the Windows installation. This doesn't work if the VM was migrated from VMware and it doesn't work if the org builds their own AMIs that include their organization. Amazon recommends checking UUID data and we're already doing that on Linux. Lets do that on Windows.
> Improve detection of Windows EC2 nodes by using UUID information

- lib/ohai/mixin/azure_metadata.rb
- lib/ohai/plugins/azure.rb
- lib/ohai/plugins/cloud.rb
- spec/unit/mixin/azure_metadata_spec.rb
- spec/unit/mixin/softlayer_metadata_spec.rb
- spec/unit/plugins/azure_spec.rb
- spec/unit/plugins/cloud_spec.rb
- spec/unit/plugins/ec2_spec.rb
The Azure metadata endpoint has gone GA. This pulls instance information straight from the source.
> Add Azure metadata endpoint support

- lib/ohai/plugins/linux/virtualization.rb
- spec/unit/plugins/linux/virtualization_spec.rb
https://github.com/chef/ohai/issues/833
> Detect LXC if LXC and Docker are on the same host

- RELEASE_NOTES.md
- lib/ohai/plugins/packages.rb
- spec/data/plugins/pacman.output
- spec/unit/plugins/packages_spec.rb
This commit adds support for detecting packages on Arch Linux. This is my first time contributing to Ohai or any Chef project, so I'd appreciate any feedback.
I wrote this mainly because I wanted to make some decisions in Chef that involved knowing if one package from a set were already installed. Specifically, I wanted a recipe that installs command line vim, but only if graphical vim isn't already installed.
> Add Arch Linux support to package plugin

- lib/ohai/plugins/linux/network.rb
Removing the ending word boundary in the regex allows is to capture the
:: endings while still properly parsing other routes. I added a rubular
comment as well so we know what this regex is actually trying to
capture.
> Fix the route support for IPV6 routes ending in ::

- lib/ohai/application.rb
- lib/ohai/runner.rb
A reoccurring problem in Ohai is the runs taking too long. It's hard to troubleshoot since you can't tell what plugin is causing the long runs. This simple debug information provides us with the information we need to troubleshoot unusually long ohai run times.
Example output
```
[2017-09-11T09:20:27-07:00] DEBUG: Plugin Ruby took 1.568772 seconds to run.
[2017-09-11T09:20:27-07:00] DEBUG: Plugin Rust: ran 'rustc --version' and returned 0
[2017-09-11T09:20:27-07:00] DEBUG: Plugin Rust took 0.356488 seconds to run.
[2017-09-11T09:20:31-07:00] DEBUG: Plugin Scala: ran 'scala -version' and returned 0
[2017-09-11T09:20:31-07:00] DEBUG: Plugin Scala took 3.216373 seconds to run.
[2017-09-11T09:20:36-07:00] DEBUG: Ohai took 16.940469 total seconds to run.
```
Signed-off-by: Tim Smith …
> Add plugin timing information in debug mode

- lib/ohai/plugins/ec2.rb
This gets required in other places, but it was meant to be uncommented.
> Make sure we require wmi/lite in the ec2 plugin

- RELEASE_NOTES.md
- lib/ohai/config.rb
- lib/ohai/dsl/plugin.rb
- lib/ohai/exception.rb
- lib/ohai/runner.rb
- lib/ohai/system.rb
- spec/unit/system_spec.rb
This adds a new Ohai configuration `critical_plugins` which will cause
Ohai to exit (or `fail` if inside of Chef) if the plugins in the list do
not run successfully.
This feature only supports Ohai 7-style named plugins, not the ancient
Ohai 6-style stuff.
Tests to follow, but:
```
$ cat /home/phild/ohai.rb
ohai.critical_plugins << :Filesystem
$ ./bin/ohai -c /home/phild/ohai.rb
[2017-10-03T13:43:14-07:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
[2017-10-03T13:43:14-07:00] ERROR: The following plugins marked as critical failed: [:Filesystem]
```
And when I run Chef:
```
[2017-10-03T13:44:11-07:00] FATAL: RuntimeError: The following plugins marked as critical failed: [:Filesystem2]. Failing Chef run.
```
This fixes #879.
> Critical Plugins

- lib/ohai/system.rb
- spec/unit/system_spec.rb
PR #1065 broke the 8-stable build... though Travis claimed it passed. There is
no @cli mode in 8.x, so of course that code behaves differently. Cleaning up to
fix tests.
Also, chefstyle
> Fix 8-stable build

- RELEASE_NOTES.md
- lib/ohai/plugins/linux/filesystem.rb
- spec/unit/plugins/linux/filesystem_spec.rb
PR #1047 allows a plugin to return partial data which may be incredibly
dangerous. It's a totally reasonable thing to want, however, so we gate
it behind a plugin config. However, the default behavior reverts to
where it was.
Don't lie to people about their filesystems
> Fix regression in #1047

- Gemfile
- Rakefile
We're not using this anymore in ohai-8 land.
> Remove changelog generator from 8-stable

- lib/ohai/plugins/linux/virtualization.rb
- spec/unit/plugins/linux/virtualization_spec.rb
Signed-off-by: Jose Asuncion <jeunito@gmail.com>
Adds checking of `lxc-start` to `lxc_version_exists?`
https://github.com/chef/ohai/issues/488
> also check for lxc-start

- lib/ohai/plugins/aix/uptime.rb
- spec/unit/plugins/aix/uptime_spec.rb
…er than epoch
Signed-off-by: rmcleod8 <richard.mcleod@gmail.com>
Updated the value returned for `uptime_seconds` on AIX machines to show elapsed seconds from boot rather than returning the data as epoch
https://github.com/chef/ohai/issues/1074
> Updating AIX uptime_seconds to reflect elapsed seconds from boot rather than epoch

- lib/ohai/plugins/rackspace.rb
- spec/unit/plugins/rackspace_spec.rb
This uses the same method we previously used on EC2. It won't poll any data since that requires the xen cli tools, but it will show up as being on rackspace, which is an important first step.
> Detect Rackspace on Windows

- RELEASE_NOTES.md
We're deprecating these in Ohai 14 not 15 as previously planned
> Add a note about the updated OHAI-11/12 deprecations

- .travis.yml
- appveyor.yml
- lib/ohai/plugins/ec2.rb
- spec/unit/plugins/ec2_spec.rb
C5 instances are not Xen based. They use Amazon's own hypervisor so our existing detection methods fail. I suspect we could probably get rid of the old DMI detection, but I get nervous removing detection logic. This checks the bios vendor DMI data. I also removed the depedency on  the DMI plugin since a lot of systems don't have dmidecode. This will catch far more systems.
> Detect new Amazon hypervisor used by the C5 instances

- .travis.yml
- appveyor.yml
Test on Ruby 2.4 in appveyor
Use the latest ruby releases in Travis
Don't update rubygems since 2.7.2 is busted
> Resolve rubygems failures + update ruby versions

- lib/ohai/plugins/linux/mdadm.rb
- spec/unit/plugins/linux/mdadm_spec.rb
Fix mdadm not handling arrays with > 10 members
> [mdadm] Support arrays more than 10 disks

- lib/ohai/plugins/linux/mdadm.rb
- spec/unit/plugins/linux/mdadm_spec.rb
> [mdadm] Support arrays more than 10 disks - backport to 8-stable

- lib/ohai/plugins/linux/mdadm.rb
- spec/unit/plugins/linux/mdadm_spec.rb
Journal and spare devices are important to report clearly. This puts
them in their own arrays.
I'd like to backport this to 12.x - but it's unclear here what
backwards compat here is.
I *could* put *all* devices into `members` and then also specify special
members in their own list... but prior to me fixing this plugin a few
months, ago, spares and journal wouldn't have been reported anyway...
and it is probably incorrect to report them as normal members... so this
feels like a further fix on a previous fix, so I've opted for just
fixing it. However, let me know how you guys feel.
Failing to be able to handle journal or spare devices properly - especially bad for journal devices.
> [mdadm] Handle journal and spare devices properly

- lib/ohai/plugins/linux/virtualization.rb
- spec/unit/plugins/linux/virtualization_spec.rb
`node['virtualization']` should detect when running in a `systemd-nspawn` container.
Previously it would return this, which made it very difficult to tell if running inside an nspawn container:
```
root@archon:~# ohai | jq .virtualization
{
"systems": {
"kvm": "host"
},
"system": "kvm",
"role": "host"
}
```
Now it returns this:
```
root@archon:~# /usr/local/bin/ohai | jq .virtualization
[2017-10-29T14:34:20-07:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
{
"systems": {
"kvm": "host",
"nspawn": "guest"
},
"system": "nspawn",
"role": "guest"
}
```
The behavior on a systemd host is unchanged:
```
zeal@drcid ~/dev/ohai $ sudo ohai | jq .virtualization
[2017-10-29T15:11:09-07:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
{ …
```
> Added systemd-nspawn virtualization detection

- bin/ohai
This is Ruby 1.8 code and also pretty heavily assumes the the user is installing into a system (debian) ruby install. There's no need for any of this with modern ruby releases.
> Remove the rubygems require in the main app

- appveyor.yml
- lib/ohai/plugins/linux/mdadm.rb
- spec/unit/plugins/linux/mdadm_spec.rb
This is a backport of #1094.
Journal and spare devices are important to report clearly. This puts
them in their own arrays.
See #1094 for discussion of this being backported.
> [mdadm] Handle journal and spare devices properly - Ohai 8

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
This gathers extra information on tunnel devices. Unfortunately iproute2 is a
little inconsistent as to how it prints these out, some are booleans some are
key values, but there's no way to tell them apart other than to know, so I parse
the ones I know about (from reading the source), and ignore anything else.
Note that I didn't add any ifconfig support to the tests. This is for a few
reasons:
1. the output in the tests from ifconfig is ancient, ifconfig on linux doesn't
look like that anymore, it looks like this:
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.1.1.2  netmask 255.255.255.0  broadcast 10.1.1.255
inet6 2601:645:c001:56bb::2  prefixlen 64  scopeid 0x0<global>
inet6 fe80::52e5:49ff:fe38:d761  prefixlen 64  scopeid 0x20<link>
ether 50:e5:49:38:d7:61 …
```
> [linux/network] Tunnel info

- .travis.yml
Ruby head and 2.5 have diverged already
> Test on Ruby 2.5

- RELEASE_NOTES.md
- lib/ohai/plugins/linux/lspci.rb
- spec/unit/plugins/linux/lspci_spec.rb
This is based on an original plugin from:
https://github.com/GLOBAL2000/chef-ohai-plugins/
With modifications from the fork here:
https://github.com/GLOBAL2000/chef-ohai-plugins/
> Add a plugin to provide PCI bus information using `lspci`.

- RELEASE_NOTES.md
- lib/ohai/plugins/linux/lspci.rb
- spec/unit/plugins/linux/lspci_spec.rb
This is a backport of https://github.com/chef/ohai/pull/1107 to Ohai 8.
> [Ohai 8] Add a plugin to provide PCI bus information using `lspci`.

- lib/ohai/plugins/linux/virtualization.rb
- spec/unit/plugins/linux/virtualization_spec.rb
This fix will loosen the regex matching pattern against the
pattern that the docker for mac update introduced to /proc/self/cgroup.
Currently ohai is returning an empty virtualization systems object.
> (chef/ohai#1110) Fix for issue introduced by docker for mac update.

- lib/ohai/plugins/cloud.rb
- lib/ohai/plugins/darwin/filesystem.rb
- lib/ohai/plugins/linux/filesystem.rb
- spec/unit/plugins/cloud_spec.rb
- spec/unit/plugins/darwin/filesystem_spec.rb
- spec/unit/plugins/linux/filesystem_spec.rb
We made cloud_v2 and filesystem2 the default cloud and filesystem
plugins in Chef 13. For backwards compatibility we wrote the data out to
both locations, which bloated the node object size significantly. We've
deprecated the legacy attributes and this removes them. Chef servers
everywhere will thank us.
> Remove cloud_v2 and filesystem2 attributes

- .travis.yml
- ohai.gemspec
Support the last 2 major releases.
> Ohai 14: Require Ruby 2.4 or later

- ohai.gemspec
This actually breaks us bumping chef to 14 right now.
> Allow for chef-config 14

- lib/ohai/version.rb
We will tag / ship as 14.0 later, but this allows us to pin to 14.0 in
chef/chef and consume from master.
> Bump the version to 14.0.0 for chef/chef

- lib/ohai/plugins/linux/virtualization.rb
- spec/unit/plugins/linux/virtualization_spec.rb
Signed-off-by: Joe Nuspl <nuspl@nvwls.com>
Backport ohai#1113 to 8-stable
ohai#1110
- [/] New functionality includes tests
- [/] All tests pass
- [/] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [/] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
> Backport ohai#1110 (Recognize docker-ce) to 8-stable

- .expeditor/config.yml
- CHANGELOG.md
* Add the missing `rubygems` config so Expeditor knows which rubygems to build
* Add missing changelog comment block hooks so Expeditor can manage the Changelog
* No Gem builds
* No Changelog management
> Fix Expeditor config as to publish gems and manage changelog

- lib/ohai/plugins/aix/uptime.rb
- spec/unit/plugins/aix/uptime_spec.rb
Adds whitespace stripping for shellout stdout
turns out, ibm intentionally adds whitespace to the output here when the days number is 1-9.
adding .strip cleans up the stdout so the case regex can properly evaluate the data.
> adds whitespace stripping for the shellout stdout

- lib/ohai/loader.rb
- ohai.gemspec
We can safely assume chef-config 12.8+ now.
> Simplify path logic by requiring chef-config 12.8+

- spec/unit/plugins/vmware_spec.rb
It helps to run the plugin before we make sure the attributes aren't there.
> Fix vmware specs to actually run the plugin

- lib/ohai/plugins/darwin/virtualization.rb
- lib/ohai/plugins/docker.rb
- lib/ohai/plugins/linux/virtualization.rb
- spec/unit/plugins/darwin/virtualization_spec.rb
- spec/unit/plugins/docker_spec.rb
- spec/unit/plugins/linux/virtualization_spec.rb
Detect docker hosts by the docker binary and fetch information from Docker for a plugin.
> Docker host detection and information

- lib/ohai/config.rb
- lib/ohai/dsl/plugin.rb
- lib/ohai/dsl/plugin/versionvii.rb
- lib/ohai/plugins/linux/lspci.rb
- lib/ohai/plugins/linux/sessions.rb
- lib/ohai/plugins/passwd.rb
- lib/ohai/runner.rb
- spec/unit/system_spec.rb
Some plugins are useful enough to ship in Ohai, but should be off by
default. Those plugins can be (and are) marked as optional. Implements
RFC 103
> Support optional plugins

- lib/ohai/mixin/scaleway_metadata.rb
- lib/ohai/plugins/scaleway.rb
- spec/unit/plugins/scaleway_spec.rb
Scaleway is a young french cloud provider.
https://www.scaleway.com/
Signed-off-by: Jonathan Amiez <jonathan.amiez@gmail.com>
Adds a new Ohai plugin to expose Scaleway instances metadata.
Heavily inspired by digital_ocean and ec2 plugins (read actually copied).
> Add scaleway plugin

- lib/ohai/plugins/scaleway.rb
- spec/unit/plugins/scaleway_spec.rb
Make sure we mock out the /proc/cmdline so we don't fail on non-Linux
systems and properly expect an empty hash when we're on scaleway, but
metadata fetching fails
> Fix specs failures in the scaleway plugin

- lib/ohai/plugins/root_group.rb
- spec/unit/plugins/root_group_spec.rb
We have a helper that allows us to define specific logic on Windows. We
should use that here.
> Update root_group plugin to use the collect_data helper

- lib/ohai/plugins/shard.rb
This avoids the MD5-on-FIPS problems that people suffer.
> Mark the shard plugin as optional

- lib/ohai/plugins/kernel.rb
- lib/ohai/plugins/windows/network.rb
- spec/unit/plugins/windows/kernel_spec.rb
We're collecting some super useless data here (wmi class names) and some entirely duplicate data. Lets shave a tiny bit of storage space off the node object and make it easier to reason with.
This reduces the uncompressed node object by 1k
> Expand what we blacklist from the kernel/network plugins on Windows

- lib/ohai/mixin/softlayer_metadata.rb
Softlayer is forcing tlsv1_2 for all API calls.  tlsv1 calls will stop working on 3/1/2018
https://softlayer.github.io/release_notes/2018/20180301/
Signed-off-by: S. Cavallo <smcavallo@hotmail.com>
[Please describe what this change achieves]
- [ X] New functionality includes tests
- [X ] All tests pass
- [X ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [X ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
> Softlayer is forcing tlsv1_2 for all API calls

- lib/ohai/mixin/softlayer_metadata.rb
Softlayer is forcing tlsv1_2 for all API calls.  tlsv1 calls will stop working on 3/1/2018
Signed-off-by: S. Cavallo <smcavallo@hotmail.com>
> Backport Fix for Softlayer disabling TLS 1.0/1.1 on 3/1/2018

- lib/ohai/plugins/uptime.rb
- lib/ohai/plugins/windows/cpu.rb
- spec/functional/plugins/windows/uptime_spec.rb
- spec/unit/plugins/windows/uptime_spec.rb
The uptime plugin will break due to this
The CPU plugin will only work if the system is unpatched
EXTENDED support for Windows 2003 ended July 14, 2015
> Remove support for Windows 2003 from uptime/cpu plugins

- lib/ohai/plugins/cloud.rb
- spec/unit/plugins/cloud_spec.rb
Signed-off-by: S.Cavallo <smcavallo@hotmail.com>
Ohai running on softlayer cloud will populate cloud attributes.
This functionality was removed from ohai during cloud_v2 -> cloud refactoring.
See - https://github.com/chef/ohai/commit/effa84d1129c011b2e632aec0908ec401844bd1b#diff-7b665cfb965d9a6bb7e6f0d8bdf43322
latest ohai does not populate node['cloud'] - this is a regression
- [X ] New functionality includes tests
- [X ] All tests pass
- [X ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
> add ohai support for softlayer cloud

- lib/ohai/mixin/azure_metadata.rb
- lib/ohai/plugins/azure.rb
This fixes a bug discovered for the Azure plugin, and updates to the recent azure metadata api date/version.
This fixes a bug I discovered which will crash the azure plugin if it's missing metadata. I discovered, at least on an ND24rs instance I was on, that no network metadata is received.
Also updated to the recent Azure metadata API which gives additional metadata including the resource group name, availability set info, subscription id, and VM scale set info.
> Fix bug in azure plugin/update to recent metadata version.

- Gemfile
Pin chefstyle to 0.6.0 so we don't have to fix all the warnings on our
legacy branch
> Pin Chefstyle and remove github_changelog_generator

- lib/ohai/plugins/chef.rb
- lib/ohai/plugins/ohai.rb
Add some logging when we can't load chef to get chef info and remove a unnecessary require of ohai.
> Minor updates to the Ohai/Chef plugins

- lib/ohai/mixin/azure_metadata.rb
- lib/ohai/plugins/azure.rb
This fixes a bug discovered for the Azure plugin, and updates to the recent azure metadata api date/version.
This fixes a bug I discovered which will crash the azure plugin if it's missing metadata. I discovered, at least on an ND24rs instance I was on, that no network metadata is received.
Also updated to the recent Azure metadata API which gives additional metadata including the resource group name, availability set info, subscription id, and VM scale set info.
> Fix bug in azure plugin/update to recent metadata version. [ backport #1154]

- lib/ohai/plugins/cloud.rb
- spec/unit/plugins/cloud_spec.rb
Signed-off-by: S.Cavallo <smcavallo@hotmail.com>
Ohai running on softlayer cloud will populate cloud attributes.
This functionality was removed from ohai during cloud_v2 -> cloud refactoring.
See - https://github.com/chef/ohai/commit/effa84d1129c011b2e632aec0908ec401844bd1b#diff-7b665cfb965d9a6bb7e6f0d8bdf43322
latest ohai does not populate node['cloud'] - this is a regression
> Backport fix for softlayer not showing up in the node['cloud'] plugin

- lib/ohai/plugins/aix/uptime.rb
- spec/unit/plugins/aix/uptime_spec.rb
Backport from Ohai 14 PR #1132:
Adds whitespace stripping for shellout stdout
turns out, ibm intentionally adds whitespace to the output here when the days number is 1-9.
adding .strip cleans up the stdout so the case regex can properly evaluate the data.
> Properly strip whitespace from shellout in the AIX uptime plugin

- lib/ohai/plugins/scsi.rb
- spec/unit/plugins/scsi_spec.rb
Add a SCSI plugin.
Can know what devices are on the SCSI bus at what address.
> SCSI plugin

- lib/ohai/plugins/shard.rb
- spec/unit/plugins/shard_spec.rb
This makes life easier for most users since there is no reason to disable this plugin by default other than FIPS, and having to set `optional_plugins` is more of a barrier than I think we planned (I couldn't find an implementation of the cookbook-metadata-driven path we had talked about).
> Make the shard plugin work under FIPS by using SHA2 instead of MD5

- lib/ohai/common/dmi.rb
- lib/ohai/plugins/dmi.rb
- lib/ohai/plugins/solaris2/dmi.rb
- spec/unit/plugins/dmi_spec.rb
A lot of people want their OEM / IPMI dmi data. It’s super handy to have.
> Make the DMI IDs we whitelist configurable

- lib/ohai/plugins/bsd/filesystem2.rb
- spec/unit/plugins/bsd/filesystem2_spec.rb
This is partial backport of #1181. Rather than do the merging it simply makes an
additional plugin to be as non-intrusive to 13 as possible, but to provide some
level of upgradability to those who need it.
> [filesystem2] Backport filesystem2 for Ohai 13

- lib/ohai/plugins/shard.rb
So after some repro and research:
```
[centos@ip-10-0-201-37 ~]$ /opt/chef/embedded/bin/irb
irb(main):001:0> require 'openssl'
=> true
irb(main):002:0> OpenSSL.fips_mode = true
=> true
irb(main):004:0> OpenSSL::Digest::SHA256.new
=> #<OpenSSL::Digest::SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855>
irb(main):006:0> (OpenSSL::Digest::SHA256.new << 'asdf').hexdigest
=> "f0e4c2f76c58916ec258f246851bea091d14d4247a2fc3e18694461b1816e13b"
irb(main):009:0> require 'digest/sha2'
=> true
irb(main):011:0> Digest::SHA256.new
sha256.c(34): OpenSSL internal error, assertion failed: Low level API call to digest SHA256 forbidden in FIPS mode!
Aborted
```
or tl;dr we need to use the openssl impl. I chef-config we patch stuff for MD5 and SHA1 …
> Fix shard plugin under FIPS mode because my testing was not sufficient

- lib/ohai/plugins/linux/fips.rb
- lib/ohai/plugins/windows/fips.rb
Until we fix https://github.com/chef/ohai/issues/1185, OpenSSL.fips_mode can only be used as a positive signal, not a negative.
Without this, running via `ohai` and through Chef can return different results.
> Rework FIPS detection to only use the positive of OpenSSL.fips_mode

- lib/ohai/plugins/aix/filesystem.rb
- spec/unit/plugins/aix/filesystem_spec.rb
In cases where the mount point didn't match exactly, this resulted in an incorrect value being returned.
I've updated the test to make it clear as to what the problem is.
I don't know of any issues posted related to this.
- [N/A] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
> Fix an issue caused by using the wrong field in the AIX filesystem plugin.

- lib/ohai/common/dmi.rb
- lib/ohai/plugins/dmi.rb
- lib/ohai/plugins/solaris2/dmi.rb
- spec/unit/plugins/dmi_spec.rb
A lot of people want their OEM / IPMI dmi data (in Ohai 13). It’s super handy to have (in Ohai 13).
Backport of #970
Signed-off-by: Gavin Reynolds <gavin@chef.io>
> Backport "Make the DMI IDs we whitelist configurable" to Ohai 13

- lib/ohai/plugins/aix/filesystem.rb
- spec/unit/plugins/aix/filesystem_spec.rb
Backport of #1191 
In cases where the mount point didn't match exactly, this resulted in an incorrect value being returned.
I've updated the test to make it clear as to what the problem is.
I don't know of any issues posted related to this.
> Fix an issue caused by using the wrong field in the AIX filesystem plugin

- .gitignore
- lib/ohai/mixin/dmi_decode.rb
Backport of #1193 
Replaces #1200
Detects virtualization on AWS instances using the newer "nitro" hypervisor.
Didn't see any.
> Detect virtualization on newer AWS instance types. (m5)

- CHANGELOG.md
We have expeditor on 13-stable now so this is the last time ever!
> Add missing changelog items to 13 stable

- .rubocop.yml
- lib/ohai/plugins/linux/network.rb
Enable the UnneededSort rule so we can continue to identify these.
> Resolve several performance issues identified by Rubocop

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
Make the release substring on RHEL platforms optional This fixes matching the new amazon linux which is entirely different than literally every other RHEL like platform.
>  Properly detect Amazon Linux 2 final release platform version 

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
Make the release substring on RHEL platforms optional This fixes matching the new amazon linux which is entirely different than literally every other RHEL like platform.
> Properly detect Amazon Linux 2 final release platform version

- lib/ohai/plugins/windows/system_enclosure.rb
- spec/unit/plugins/windows/system_enclosure_spec.rb
Signed-off-by: Stuart Preston <stuart@chef.io>
This plugin provides a way to access the hardware information visible to Windows from the win32_systemenclosure class
Example output:
```
C:\projects\chef\ohai [sp/1209]> bundle exec ohai system_enclosure
{
"manufacturer": "Microsoft Corporation",
"serialnumber": "000430775257"
}
```
Fixes #1209
> Add system_enclosure plugin for Windows

- lib/ohai/dsl/plugin/versionvii.rb
- spec/unit/dsl/plugin_spec.rb
- spec/unit/loader_spec.rb
If we happen to load a plugin with the same name twice, we refuse to run #collect_data but we still
load the rest of the plugin, which means you get #collect_data from the first plugin and rest of the
plugin from the last plugin.
This makes it so you get #collect_data from the last plugin as well.
I don't know how to use the logger from the class method so I fell back to `Ohai::Log`. Happy to fix that
if someone knows the magic.
Fixes #1212
Signed-off-by: Bryan McLellan <btm@chef.io>
> Load collect_data() even if we've already seen it

- Rakefile
This project was moved to expeditor. We're no longer generating changelogs using this gem and the gem dependency has been removed already
> Remove the changelog generator task

- .expeditor/config.yml
Cleanup branches post PR merge
Add ability to bump minor via label
Remove the branch config for Ohai 8 (chef 12)
> Update Expeditor to clean branches / bump minors

- RELEASE_NOTES.md
- lib/ohai/application.rb
- lib/ohai/system.rb
- ohai.gemspec
- spec/unit/system_spec.rb
This allows you to run ohai -d /foo/bar,/bar/foo
> Add support for passing multiple plugin directories on CLI/client.rb

- lib/ohai/config.rb
- lib/ohai/mixin/command.rb
This makes the default timeout of 30 seconds configurable
- #1072
> Make the default shell_out timeout of 30 seconds configurable

- .expeditor/config.yml
> Resolve Expeditor config warnings

- .expeditor/config.yml
No need for these anymore now that we've standardized the labels
> Remove old labels from the expeditor config

- lib/ohai/plugins/windows/network.rb
- spec/unit/plugins/windows/network_spec.rb
- Also added a minor fix to select default_interface based on the least metric value
- Added Test cases
- Fixes: MSYS-875
Signed-off-by: Nimesh <nimesh.patni@msystechnologies.com>
According to previous logic, there was an iteration over all the interfaces and the value of `default_gateway`  and `default_interface` was getting reset in each loop. Hence the last interface was chosen as default_interface and so its default_gateway.
`default_gateway` was selected as the first one out from the list of `default_ip_gateway` of an interface, hence there was a possibility that if this list contain IPV6 address at former place, then it was selected.
In case of multiple Interfaces, priority for `default_interface` should be given to the interface with least metric value. Also, we need to prefer …
> Prefer ipv4 for default_gateway over ipv6 on windows

- lib/ohai/plugins/linux/network.rb
- lib/ohai/plugins/windows/network.rb
- spec/unit/plugins/windows/network_spec.rb
Simple fix for now that unbreaks the linux network plugin.
> Uniquely name our network plugin helper methods

- lib/ohai/plugins/windows/filesystem.rb
- spec/unit/plugins/windows/filesystem_spec.rb
- Changes to fetch Encryption Status of a volume
- Fixed cases to handle WMI Exceptions 
- Added test cases
- Minor code cleanup
- Fixes MSYS-894
Signed-off-by: Nimesh <nimesh.patni@msystechnologies.com>
By using `GetConversionStatus` method of  `Win32_EncryptableVolume` class, we may fetch encryption status of a volume
#1226
> Add "EncryptionStatus" to each volume on Windows

- .travis.yml
- Rakefile
Remove the old requires for the github changelog generator
Add the console task
Provide better error handling / messages when the gems aren't there
Make style/specs default and just run the default in Travis
> Use a more standardized Rakefile

- lib/ohai/plugins/openstack.rb
- spec/unit/plugins/openstack_spec.rb
Signed-off-by: sawanoboly <sawanoboriyu@higanworks.com>
This PR replaces #1239 
OpenStack's metadata API is often slow response. So please wait a little more.  So we can override the timeout with the config value.
- Ohai::Config.ohai[:openstack_metadata_timeout]
> override timout by Ohai::Config.ohai[:openstack_metadata_timeout]

- lib/ohai/application.rb
We do an expand_path on the passed config value and we use Dir.pwd with the expand, but before we ever get here we change the directory to /, which means specifying a file in the working directory results in something like /client.rb. This isn't what the user wants. Instead change the working directory right before we run the application instead of before we work out the config situation.
> Fix providing relative paths to the config file

- README.md
- RELEASE_NOTES.md
Adds release note entries for 14.5 + minor readme updates.
> Release Ohai 14.5

- ohai.gemspec
This is always ruby. No need to define it here.
> Remove redundant platform from the gemspec

- lib/ohai/system.rb
This is used several times in this class, but not required.
> Add missing require ffi_yajl in System class

- lib/ohai/mixin/gce_metadata.rb
This reverts commit 192f84944120bed9099a59e42b6fb43155cc0f6c.
Turns out we heavily relied on the DNS name resolving to determine if we were actually on GCE. We're going to need to figure out proper GCE detection before we can use the IP here or it will detect azure/ec2 as gce.
> Revert "Connect to GCE metadata by IP not name"

- lib/ohai/plugins/darwin/cpu.rb
- spec/unit/plugins/darwin/cpu_spec.rb
While it works fine for me @bdausses was seeing chef-client hang
forever on macos 10.14. It turns out running sysctl -a on his VM was causing the
system to hang. Besides this crash it actually takes about 2x longer to
gather the additional data, which we never use. This shaves a whole 0.033255 seconds from
the total runtime of Ohai.
> Avoid gathering all data with sysctl which seems to hang

- appveyor.yml
This will skip commits that only change docs as well as the Expeditor
commits that only change the version (which cause a second identical
test to run).
Signed-off-by: Bryan McLellan <btm@loftninjas.org>
> Skip appveyor on docs/version bump commits

- lib/ohai/plugins/darwin/hardware.rb
- lib/ohai/plugins/darwin/system_profiler.rb
Also there's no need to rescue requiring plist since ohai depends on it. We don't do this for anything else in Ohai. This shaves 8k from the node data. I'm also going to open a PR to deprecate this plugin so we can remove it in Chef 15 since it doesn't actually work on modern systems and we already collect the same data in the hardware plugin.
> Trim out bogus data in system_profile plugin

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
This was a mistake when we introduced it. The system self identifies as SLES, but we need to make that suse to align with SLES 11/12 detection in Ohai.
> Correctly detect SLES 15 systems as "suse" platform

- RELEASE_NOTES.md
1) It's broken
2) It's a huge amount of data on the node
3) It takes 3 seconds to run
4) Hardware plugin does the same thing, but better
> Deprecate the system_profile plugin

- lib/ohai/application.rb
This is a legacy issue that doesn't seem to be a problem in the modern design of ohai. Additionally it's probably breaking minor / subtle things throughout plugins.
> Remove the chdir to / when running ohai

- lib/ohai/application.rb
We do an expand_path on the passed config value and we use Dir.pwd with the expand, but before we ever get here we change the directory to /, which means specifying a file in the working directory results in something like /client.rb. This isn't what the user wants. Instead change the working directory right before we run the application instead of before we work out the config situation.
> Fix provided relative paths to the config file

- lib/ohai/plugins/openstack.rb
- spec/unit/plugins/openstack_spec.rb
Signed-off-by: sawanoboly <sawanoboriyu@higanworks.com>
Due to the handling of OpenStack metadata, the Cloud plugin may crash.
Reproduction procedure
There is no `public-ipv4` key for metadata until Floating IPaddress is given.
1. Give virtualmachine a floating IPaddress
1. Remove the Floating IPaddress.
1. `"public-ipv4"=> ""` remains in the virtualmachine metadata, so crashing with IP address verification.
```
> Ohai::NamedPlugin::Cloud.new(ohai.data, ohai.logger).run
RuntimeError: ERROR: the ohai 'cloud' plugin failed with an IP address of '' : invalid address
from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.6.2/lib/ohai/plugins/cloud.rb:111:in `rescue in validate_ip_addr'
Caused by IPAddr::InvalidAddressError: invalid address
from …
```
> Ignore empty metadata openstack

- RELEASE_NOTES.md
- lib/ohai/mixin/gce_metadata.rb
Setting the User-Agent to `chef-ohai/VERSION` will correctly identify ohai as the application making a request to metadata.google.internal.
The previous User-Agent header was defaulting to
`User-Agent: Ruby`
It is now set to
`chef-ohai/14.6.2` where `14.6.2` is the value of `Ohai::VERSION`
Signed-off-by: Nathen Harvey <nathenharvey@google.com>
> Set User-Agent in HTTP header for GCE plugin

- RELEASE_NOTES.md
- lib/ohai/plugins/gce.rb
Check the system information to determine if this system is running on Google Compute Engine.
See also the Google Cloud Documentation for [detecting if you are running in Compute Engine](https://cloud.google.com/compute/docs/instances/managing-instances#dmi).
Signed-off-by: Nathen Harvey <nathenharvey@google.com>
> Adds more resilient GCE checking

- lib/ohai/plugins/linux/virtualization.rb
- spec/unit/plugins/linux/virtualization_spec.rb
Plugin to load hyper_v hostname from guest, to see on which node the guest is running.
- Issue #1302
> Plugin to load hyper_v hostname from guest

- lib/ohai/mixin/dmi_decode.rb
- spec/unit/plugins/linux/virtualization_spec.rb
- spec/unit/plugins/solaris2/virtualization_spec.rb
This removes support for the following legacy virtualization hypervisors that were based on the VirtualPC tech that Microsoft bought from Connectix and then rebranded. It never worked on Windows 2008 / 7 or later. It's just dead tech that no one is using at this point.
See for release details:
https://en.wikipedia.org/wiki/Microsoft_Virtual_Server
> Remove circa ~2005 virtualization hypervisor detection

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
We need to correctly read in the data in /etc/os-release and do the right thing. We already did this for SLES 15.
Fixes #1289. Thanks for great issue report @megamorf
> Correctly detect openSUSE leap 15+

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
/etc/os-release is the modern way of identifying Linux platforms and versions. It's far more reliable than the brittle regex mess that we have built up over the last decade. It also allows us to easily detect unknown / obscure distros since they have platform IDs in the os-release file.
Changes to call out:
- Platform detection will now default to /etc/os-release if that file is present
- The majority of the legacy logic is retained within a legacy method
- Unless we override the value we just use the platform value from os-release. Going forward for new platforms we'll just use this value. The overrides are just to retain legacy compatibility
- Unless it's missing we just use the version found in the os-release file. If it's not found we grab the kernel version with uname as we did …
> /etc/os-release based OS detection

- lib/ohai/plugins/linux/virtualization.rb
- spec/unit/plugins/linux/virtualization_spec.rb
Plugin to load hyper_v hostname from guest, to see on which node the guest is running.
- Issue #1302
> Linux Virtualization: Load hyper_v hypervsior hostname from guest

- RELEASE_NOTES.md
There may be a few more things, but this is the general list. I took out
the GCE change since that's not visible to end users. That's more for
Google.
> Add Ohai 14.8 release notes

- lib/ohai/plugins/linux/virtualization.rb
Somehow we never updated these for the new format. This means you can end up with data like this which is wrong in both the legacy and the new format.
```json
{
"systems": {
"xen": "guest"
},
"system": "lxd",
"role": "host"
}
```
with this change we get:
```json
{
"systems": {
"xen": "guest",
"lxd": "host"
},
"system": "lxd",
"role": "host"
}
```
[Please describe what this change achieves]
> Linux Virtualization: Use the new nests `systems` format for lxd / lxc

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
mangeia is a popular OS in France. It's a fork of Mandriva which went out of business. There's a few other forks of mandriva so that should probably be the platform_family. It even identifies that as being similar in the os-release file.
> Add mangeia platform with madriva platform_family

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
Modern arista systems include not only /etc/Eos-release, but also /etc/redhat-release and /etc/system-release. Due to the order we did detection with this meant we read /etc/redhat-release first and identified arista as being fedora. Correct the order and wire things up in a way that will fail if we try to refactor the code back in the future.
> Fix arista platform detection

- lib/ohai/plugins/bsd/virtualization.rb
- spec/unit/plugins/bsd/virtualization_spec.rb
Refactor a chunk of code. There's no need to split the sysctl output
since it's just a single line. There's also a ton of repetition in how
we detect guests from sysctl kernel data. Add KVM and amazonec2
detection there.
> bsd virtualization: Detect amazonec2 hypervisor + kvm without dmidecode

- ohai.gemspec
There's no need for the readme in our gem artifact. This also sets the github repo as the website so people clicking the link on rubygems hit our repo.
> Don't ship the readme with ohai

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
After thinking about this remapping SLED to SUSE was wrong. People would want a way to identify SLED and distinguish it from the server variety. This backs out the previous change and instead adds SLED to the suse platform_family.
> Back out SLES -> SUSE remapping and instead fix the platform_family

- .rubocop.yml
- .travis.yml
- appveyor.yml
- lib/ohai/plugins/elixir.rb
- lib/ohai/plugins/filesystem.rb
- lib/ohai/plugins/go.rb
- lib/ohai/plugins/groovy.rb
- lib/ohai/plugins/linux/fips.rb
- lib/ohai/plugins/lua.rb
- lib/ohai/plugins/mono.rb
- lib/ohai/plugins/nodejs.rb
- lib/ohai/plugins/perl.rb
- lib/ohai/plugins/php.rb
- lib/ohai/plugins/powershell.rb
- lib/ohai/plugins/python.rb
- lib/ohai/plugins/rust.rb
- lib/ohai/plugins/virtualbox.rb
- lib/ohai/plugins/windows/fips.rb
- ohai.gemspec
- spec/unit/plugins/abort_spec.rb
- spec/unit/plugins/fail_spec.rb
- spec/unit/plugins/linux/cpu_spec.rb
- spec/unit/plugins/linux/fips_spec.rb
- spec/unit/plugins/network_spec.rb
- spec/unit/plugins/windows/fips_spec.rb
As we do every year Ohai 15 will drop support for the N-2 support of Ruby. In the ~5 weeks Ruby 2.6 comes out so by the time we release this new version of Ohai N-2 will be Ruby 2.4.
Also while we're at it get rid of the begins in rescue blocks. Ruby 2.5 doesn't require this and it's on the path to ruby throwing errors eventually. It's a Ruby < 2.4-ism.
[Please describe what this change achieves]
> Require Ruby 2.5 or later

- .travis.yml
- lib/ohai/mixin/dmi_decode.rb
- lib/ohai/plugins/bsd/virtualization.rb
- lib/ohai/plugins/linux/virtualization.rb
- lib/ohai/plugins/solaris2/virtualization.rb
- lib/ohai/plugins/windows/virtualization.rb
- spec/unit/mixin/dmi_decode.rb
- spec/unit/plugins/linux/virtualization_spec.rb
- spec/unit/plugins/solaris2/dmi_spec.rb
- spec/unit/plugins/solaris2/virtualization_spec.rb
- spec/unit/plugins/windows/cpu_spec.rb
- spec/unit/plugins/windows/virtualization_spec.rb
We've always detected virtualization on *nix using dmidecode data. A few
years ago I unified this with the dmi_decode helper. It parsed out the
text of the dmidecode command. This greatly improved detection on BSD
and Solaris, but there was more that could be done. With this change
we're now passing in the manufacturer, product, and version data from
the dmi data. On the *nix side we'll use the dmi plugins data which has
already been split out nicely and doesn't need to be fetched or parsed
again. On the windows side we can actually get this data via WMI pretty
easily. The field names are different, but under the hood it's just DMI
data. This way if we accept a PR from a windows, solaris, bsd, or linux
user we get improves on all the other platforms.
Signed-off-by: Tim Smith …
> Unify virtualization detection on a single helper

- lib/ohai/plugins/linux/platform.rb
SUSE Linux Enterprise Desktop is SLES with a UI. It's SUSE platform_family.
> Make SLED be part of the suse platform_family

- ohai.gemspec
There's no need for the readme in our gem artifact. This also sets the github repo as the website so people clicking the link on rubygems hit our repo.
> Don't ship the readme with the ohai gemfile

- lib/ohai/plugins/linux/platform.rb
Add antergos linux, which is based on Arch https://github.com/chef/os_release/blob/master/antergos
> Add antergos and manjaro linux to the Arch platform_family

- lib/ohai/plugins/linux/platform.rb
Signed-off-by: Justin Odom <jodom@tripadvisor.com>
Add support for XCP-ng to be classified as rhel. Similar behavior to XenServer.
Issue #1282
> Add support for XCP-ng platform

- lib/ohai/loader.rb
- spec/unit/loader_spec.rb
We built a struct to track plugin file location because we needed both the file and the directory containing the file. We don't need that data anymore with V7 plugins. Instead we can just grab a list of files and then load each of the classes.
> Remove V6 plugin Struct to reduce memory consumption

- lib/ohai/mixin/os.rb
- lib/ohai/plugins/c.rb
- lib/ohai/plugins/hostname.rb
- lib/ohai/plugins/ps.rb
- spec/unit/plugins/c_spec.rb
- spec/unit/plugins/root_group_spec.rb
There hasn't been a working Ruby release for HP-UX for many years. We shouldn't continue to execute this logic and ship it around to all our customers when it's not possible that any of them are running HP-UX.
> Fully remove support for HP-UX

- ohai.gemspec
We support Ruby 2.3+ and mixlib-cli 2.0+ requires Ruby 2.5+
> Pin mixlib-cli to less than 2.0

- lib/ohai/plugins/linux/memory.rb
- spec/unit/plugins/linux/memory_spec.rb
Signed-off-by: Davide Cavalca <dcavalca@fb.com>
Add parsing logic for some relatively new fields in `/proc/meminfo`
N/A
> Parse new /proc/meminfo fields

- .travis.yml
- ohai.gemspec
These new releases just drop support for Ruby 2.1 and 2.2.
> Loosen the mixlib pins to allow for new major releases

- .travis.yml
- Gemfile
- ohai.gemspec
Allow us to bring in the new major releases which just drop Ruby 2.1/2.2
support.
> Loosen the mixlib version dependencies

- lib/ohai/plugins/linux/systemd_paths.rb
This module is already in the mix.
Signed-off-by: Franklin Webber <franklin.webber@gmail.com>
> Ohai::Util::FileHelper does not need to be loaded in this systemd_paths plugin

- README.md
Add some mention of the style task
Update the `rake -T` to include `bundle exec`
> Adds mention of the style task

- lib/ohai/system.rb
This was missed until automate required just ohai system
> Require ohai/version where we use it

- lib/ohai/mixin/azure_metadata.rb
- lib/ohai/mixin/do_metadata.rb
- lib/ohai/mixin/ec2_metadata.rb
- lib/ohai/mixin/gce_metadata.rb
- lib/ohai/mixin/scaleway_metadata.rb
- lib/ohai/mixin/softlayer_metadata.rb
- lib/ohai/plugins/linux/network.rb
- lib/ohai/plugins/linux/platform.rb
- lib/ohai/plugins/packages.rb
- lib/ohai/plugins/windows/filesystem.rb
This is very noisy in DK specs.
> Avoid constant warnings in windows/filesystem plugin

- lib/ohai/plugins/windows/filesystem.rb
Note: This PR targets 14-stable branch, as it is looking at fixing a problem in Chef-14
Closes: https://github.com/chef/ohai/issues/1276
When ohai is reloaded, Ruby warns about `CONVERSION_STATUS` constant being already defined. This PR fixes those warnings.
> Define CONVERSION_STATUS only if it wasn't defined earlier

- lib/ohai/plugins/vbox_host.rb
- lib/ohai/plugins/virtualbox.rb
- spec/unit/plugins/virtualbox_spec.rb
Instead of attempting to shellout on every system we can just check the attributes we already have. This is slightly faster and improves logging since you won't see a failure.
> Use virtualization attributes to run or skip the virtualbox plugin

- lib/ohai/plugins/aix/network.rb
- lib/ohai/plugins/bsd/virtualization.rb
- lib/ohai/plugins/darwin/network.rb
- lib/ohai/plugins/darwin/virtualization.rb
- lib/ohai/plugins/dmi.rb
- lib/ohai/plugins/dragonflybsd/network.rb
- lib/ohai/plugins/filesystem.rb
- lib/ohai/plugins/freebsd/network.rb
- lib/ohai/plugins/linux/network.rb
- lib/ohai/plugins/linux/sessions.rb
- lib/ohai/plugins/linux/virtualization.rb
- lib/ohai/plugins/netbsd/network.rb
- lib/ohai/plugins/network.rb
- lib/ohai/plugins/openbsd/network.rb
- lib/ohai/plugins/solaris2/dmi.rb
- lib/ohai/plugins/solaris2/network.rb
- lib/ohai/plugins/windows/network.rb
- lib/ohai/plugins/windows/virtualization.rb
> Simplify how we create empty mashes in the plugins

- lib/ohai/plugins/shard.rb
- spec/unit/plugins/shard_spec.rb
`collect_os` now returns a string (see `mixin/os.rb`), but the shard plugin still assumed it returns a symbol, so no matter the OS, unless overridden in `client.rb` this plugin will only use the machine name as the shard source.
Signed-off-by: Michel Salim <michel@fb.com>
https://github.com/chef/ohai/issues/1378
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chef/ohai/1379)
> [shard_seed] fix default_sources for linux, darwin and windows

- lib/ohai/plugins/shard.rb
- spec/unit/plugins/shard_spec.rb
`fips` is nil on Macs, and `default_digest_algorithm` did not check for this, causing the shard plugin to throw an exception.
Make it safer by assuming `fips` is not enabled by default.
Signed-off-by: Michel Salim <michel@fb.com>
https://github.com/chef/ohai/issues/1380
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chef/ohai/1381)
> [shard_seed] fix default_digest_algorithm on darwin

- lib/ohai/plugins/linux/network.rb
Plugin fails in parsing the output of this:
```
$ ip -d -s link
```
and thinks that an interface with `stp_state` option is down.
TBD
> Feature - Change regex for detecting interface's state

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
The ARM installer for arch sets this OS identifier, however Chef doesn't
recognize it (e.g. doesn't find a package provider).
Since Chef handles providers by "platform" (and not by platform family),
we should probably make ArchARM seem like Arch
Fixes #1387
> Translating platform "archarm" to "arch"

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
Detection of openSUSE leap and SLES distributions fail with Chef 14 because these distributions satisfy the `if File.exist?('/usr/lib/os-release')` check. However, in that check, we only consider Clear Linux and not anything else, thus causing detection to fail for any other OS.
In my experiments, all the Clear Linux distributions provided  `/etc/os-release` file also. So, moving Clear Linux detection to be based on that file, and using `/usr/lib/os-release` only if `/etc/os-release` is not found (to handle any weird edge cases out there) seems like a safe option to handle Clear Linux, openSUSE Leap and SLES.
https://github.com/chef/ohai/issues/1343
> Fix openSUSE leap and SLES detection in Chef 14

- lib/ohai/runner.rb
The ohai plugin benchmarks show total cputime instead of the real running time (wall time).  
You can see in the output from chef-client below that the Cloud plugin shows it took 20 seconds but based on the log timestamps it actually took 24minutes.
```
[2019-07-31T14:53:15-05:00] TRACE: Plugin Ohai took 0.0002349999999999297 seconds to run.
[2019-07-31T15:17:39-05:00] TRACE: Plugin Cloud took 19.176537999999997 seconds to run.
[2019-07-31T15:17:39-05:00] TRACE: Plugin Command took 8.900000000000574e-05 seconds to run.
```
> Display elapsed real time instead of total cpu time

- lib/ohai/plugins/openstack.rb
- spec/unit/plugins/openstack_spec.rb
Signed-off-by: Joshua Justice <jjustice6@bloomberg.net>
If you are using Windows on openstack, the openstack plugin fails to detect that it is using openstack unless you use hints due to the lack of `dmi` on Windows.
It is possible to work around this using `'wmi-lite'` via data contained in `wmi.first_of('Win32_ComputerSystem')`, specifically, the 'manufacturer' and 'model' fields, or data already collected by Ohai elsewhere.
https://github.com/chef/ohai/issues/1390
> Use virtualization plugin to detect if we're on openstack on Windows.

- lib/ohai/plugins/openstack.rb
- spec/unit/plugins/openstack_spec.rb
Since we rely on the Virtualization plugin now there's no reason to also poll the DMI plugin data. That's a waste of time since we'll have already matched if virtualization came back Openstack. I didn't move the manufacturer = Openstack detection since that seems wrong on all modern Openstack installs which identify product field: https://cloudinit.readthedocs.io/en/latest/topics/datasources/openstack.html
> Simplify the Openstack plugin by not polling DMI data

- lib/ohai/plugins/linux/platform.rb
- lib/ohai/provides_map.rb
- lib/ohai/system.rb
package resource fails on rawhide. The updated regex - https://rubular.com/r/3JaKsAeOMLbszj , to only return the version string.
package resource fails on fedora rawhide with the below message. 
```
ArgumentError
-------------
Malformed version number string 31 (rawhide)
Cookbook Trace:
---------------
/var/chef/cache/XXX/recipes/main.rb:37:in `from_file'
Relevant File Content:
----------------------
/var/chef/cache/XXX/main.rb:
36:  if node.linux?
37>>   package 'dmidecode' do
38:      action :nothing
39:    end.run_action(:install)
40:  end
System Info:
------------
chef_version=14.10.9
platform=fedora
platform_version=31 (rawhide)   <-- this bit is trouble
```
the section which fails
```
$ vi .chef/lib/chef/node_map.rb
269     def filters_match?(node, filters)
270 …
```
> Fix platform_version detection on Fedora rawhide

- lib/ohai/application.rb
We probably want this in both locations
> Use Benchmark.realtime for the main application time as well

- lib/ohai/plugins/linux/sysctl.rb
This way we avoid further bloating node data
> Make the new sysctl plugin optional

- lib/ohai/mixin/dmi_decode.rb
- lib/ohai/plugins/linux/virtualization.rb
- lib/ohai/plugins/openstack.rb
- lib/ohai/plugins/passwd.rb
- spec/unit/mixin/dmi_decode.rb
- spec/unit/plugins/openstack_spec.rb
- spec/unit/plugins/passwd_spec.rb
Don't require the Etc plugin for detection of Dreamhost which was causing this plugin to run on all hosts and make Ohai take several minutes on large AD domains.
Fix detection of openstack on non-Redhat based Openstack setups.
> Simplify and fix Openstack detection on Linux

- .expeditor/run_linux_tests.sh
- .expeditor/verify.pipeline.yml
- Rakefile
This brings in our script from Chef-DK
> Use s3 caching / smaller conntainers in BK & add Ruby 2.7 testing

- lib/ohai/mixin/network_helper.rb
- lib/ohai/plugins/aix/network.rb
- lib/ohai/plugins/darwin/network.rb
- lib/ohai/plugins/network.rb
- lib/ohai/plugins/solaris2/network.rb
- spec/unit/mixin/network_helper_spec.rb
- spec/unit/plugins/aix/network_spec.rb
Ruby 2.7 removes the scanf library which is used in the network plugins for darwin and solaris to parse the hex netmask into a dotted decimal
Replaced the scanf library with simple regex and to_i(16) calls
Pull #1410 added ruby 2.7 to the testing matrix which is now causing failures
> Fix failures under Ruby 2.7

- lib/ohai/plugins/filesystem.rb
require_relative is significantly faster and should be used when available.
> Substitute require for require_relative

- lib/ohai/plugins/filesystem.rb
- spec/unit/plugins/windows/filesystem_spec.rb
Fix volume name and add drive type to filesystem plugin (windows-specific).
1. Fix the volume name, which previously was always empty due to a misnamed field in Win32_LogicalDisk.
2. Re-implement PR #1403 to add drive type.  That PR had conflicts due to PR #1267.  This PR fixes that and includes a few more specs.
Fixes #1418.  Replaces #1403.
Before:
```
"filesystem": {
"C:": {
"kb_size": 104849207,
"kb_available": 15268880,
"kb_used": 89580327,
"percent_used": 85,
"fs_type": "ntfs",
"volume_name": ""
}
},
```
After:
```
"filesystem": {
"C:": {
"kb_size": 104849207,
"kb_available": 16072687,
"kb_used": 88776520,
"percent_used": 84,
"fs_type": "ntfs",
"drive_type": 3,
"drive_type_string": "local",
"drive_type_human": "Local Fixed Disk",
"volume_name": "Windows8_OS"
}
```
Before:
``` …
```
> Fix missing volume name and re-implement adding drivetype to filesystem plugin

- lib/ohai/common/dmi.rb
- lib/ohai/plugins/solaris2/dmi.rb
We broke this when we added chef-utils to chef-client. Thanks for digging into this @zmscwx and @Sliim
> Use is_a? to check the class in the DMI plugin

- lib/ohai/config.rb
updated the ohai configuration declaration to ensure that values written to ohai[:optional_plugins] are always an array of symbols. 
fixes #1406
> fix [#1406]: ensure optional_plugins to be array of symbols

- lib/ohai/plugins/filesystem.rb
- spec/unit/plugins/aix/filesystem_spec.rb
- spec/unit/plugins/bsd/filesystem_spec.rb
We added filesystem2 plugin data mid way through the Chef 14 release
cycle. This converts the filesystem plugin to write data in the
filesystem2 format. In Chef 17 we'll remove those filesystem2 namespaces
and just write the data out in the filesystem2 format.
> Replace filesystem with filesystem2 on aix/solaris/bsd

- lib/ohai/plugins/c.rb
- lib/ohai/plugins/docker.rb
- lib/ohai/plugins/ec2.rb
- lib/ohai/plugins/eucalyptus.rb
- lib/ohai/plugins/gce.rb
- lib/ohai/plugins/rackspace.rb
This gets us ready for the engine upgrade later.
> Chefstyle fixes from Rubocop 0.80

- .expeditor/run_linux_tests.sh
- .rubocop.yml
- Gemfile
Update the buildkite script to pass vars correctly
Remove the CI group in the gemfile, which isn't being used anywhere
Remove the legacy Performance/RegexpMatch cop from .rubocop.yml since the Performance cops are in rubocop (or Chefstyle) anymore.
> Minor testing updates

- lib/ohai/plugins/openstack.rb
- spec/unit/plugins/openstack_spec.rb
For problem #1433 , I don't know the cause, but it is a segmentation fault. This change worked.
Once this change is allowed, I'd like to make a backport PR for 15 branches as well.
- #1433
> use bool instead of raise/rescue to detect linux user is exists

- lib/ohai/config.rb
Backport of #1436 
Signed-off-by: Ben Rexin <ben@rexin.at>
> fix: ensure optional_plugins to be array of symbols

- lib/ohai/mixin/azure_metadata.rb
- lib/ohai/mixin/ec2_metadata.rb
- lib/ohai/mixin/gce_metadata.rb
- spec/unit/mixin/azure_metadata_spec.rb
This is inspired by the way we do this in EC2, but it's different in
many ways since Azure presents the latest version in a different way.
Additional values exposed by this:
```json
"azEnvironment": "AzurePublicCloud",
"customData": "",
"plan": {
"name": "",
"product": "",
"publisher": ""
},
"provider": "Microsoft.Compute",
"publicKeys": [
{
"keyData": "ssh-rsa 123",
"path": "/home/tsmith/.ssh/authorized_keys"
}
],
"resourceId": "/subscriptions/123/resourceGroups/tsmith/providers/Microsoft.Compute/virtualMachines/timtest",
"storageProfile": {
"dataDisks": [
],
"imageReference": {
"id": "",
"offer": "UbuntuServer",
"publisher": "Canonical",
"sku": "18.04-LTS",
"version": "latest"
},
"osDisk": {
"caching": "ReadWrite",
"createOption": "FromImage",
"diffDiskSettings": {
"option": ""
}, …
```
> Add logic to fetch the latest azure metadata version

- lib/ohai/plugins/linux/interrupts.rb
- lib/ohai/plugins/linux/irq.rb
- spec/functional/plugins/linux/interrupts_spec.rb
- spec/unit/plugins/linux/interrupts_spec.rb
Add a new plugin to expose data from `/proc/interrupts` and `/proc/irq`. Specifically, we need this to detect SMP affinity settings for NICs, but it could be extended to cover anything in `/proc/irq`.
N/A
> Add a new interrupts plugin for Linux

- lib/ohai/plugins/linux/ipc.rb
- spec/unit/plugins/linux/ipc_spec.rb
Add a basic plugin to expose SysV IPC shmem information. This could be easily extended to cover other SysV IPC types as well. This plugin was originally written by @jsvana in 2016.
N/A
> Add a new ipc plugin for Linux

- lib/ohai/plugins/filesystem.rb
Running the tests in a Windows 2019 vm I saw several failures like this:
```
1) Ohai::System Windows Filesystem Plugin the plugin when there are no volume names returns space information
Failure/Error: encryption_keys_used = Set.new
NameError:
uninitialized constant Set
Did you mean?  Net
```
> Fix test failure from missing require.

- lib/ohai/plugins/shard.rb
- spec/unit/plugins/shard_spec.rb
* Catch a variety of problems and Ohai::Log.error about them. Since this
is an optional plugin, if we're hitting these, someone specifically
requested this plugin, so an error is warranted.
* We raise anyway, so that you don't spew further errors
Fixes #1385
> Make shard plugin more resilient and throw better errors

- .rubocop.yml
- lib/ohai/plugins/linux/virtualization.rb
- spec/unit/plugins/linux/virtualization_spec.rb
I discovered that ohai was incorrectly detecting our OpenStack guests showing
the following output:
```json
{
"systems": {
}
}
```
With this change, it correctly shows the following output:
```json
{
"systems": {
"openstack": "guest"
},
"system": "openstack",
"role": "guest"
}
```
The problem was the fact that ``dmi/system/product`` was the incorrect attribute and
should be ``dmi/system/product_name`` instead.
Signed-off-by: Lance Albertson <lance@osuosl.org>
> Use correct DMI attribute name for product name

- .rubocop.yml
- lib/ohai/plugins/linux/virtualization.rb
- spec/unit/plugins/linux/virtualization_spec.rb
> Use correct DMI attribute name for product name to fix Openstack detection

- lib/ohai/plugins/windows/dmi.rb
```
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ohai-16.0.19/lib/ohai/plugins/windows/dmi.rb:23: warning: previous definition of DMI_TO_WIN32OLE was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ohai-16.0.19/lib/ohai/plugins/windows/dmi.rb:39: warning: already initialized constant SPLIT_REGEX
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ohai-16.0.19/lib/ohai/plugins/windows/dmi.rb:39: warning: previous definition of SPLIT_REGEX was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ohai-16.0.19/lib/ohai/plugins/windows/dmi.rb:41: warning: already initialized constant WINDOWS_TO_UNIX_KEYS
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ohai-16.0.19/lib/ohai/plugins/windows/dmi.rb:41: warning: previous definition of WINDOWS_TO_UNIX_KEYS was here
```
> Avoid constant warnings when reloading ohai plugins

- lib/ohai/plugins/linux/selinux.rb
- spec/unit/plugins/linux/selinux_spec.rb
Add a basic plugin to expose SELinux status information. FYI, I have very little experience with SELinux and I'm definitely open for better ways to do this. We mostly need this for `current_mode` and `loaded_policy_name`, but I figured covering everything reported by `sestatus` could be useful.
> Add new selinux plugin for Linux

- Gemfile
- lib/ohai/plugins/kernel.rb
It's past time for this term to go away, even when it's just the name of
a method.
> Remove an internal reference to blacklist

- lib/ohai/plugins/darwin/hardware.rb
- lib/ohai/plugins/darwin/platform.rb
- spec/unit/plugins/darwin/platform_spec.rb
mac_os_x_server isn't a thing anymore and no third party darwin based
operating systems ever took off. Fix this detectio and speed things up
a tiny bit by assuming darwin == mac_os_x just like we already do with
the platform_family
> Make sure Darwin hosts are always mac_os_x

- lib/ohai/plugins/linux/virtualization.rb
We ran into an issue where when running in docker containers on GH
Actions (which is on azure which is on HyperV), we were getting detected
as being run on a hyperv guest... which is indirectly true, but not
really the most correct answer.
It turns out we were being a bit too strict in this regex. I think.
So here's the `/proc/self/cgroup`:
```
12:blkio:/actions_job/4ab5ebdc794956d804d03db04557c8b79fa985cbf54bc25f51f2b0848e3f58bd
11:devices:/actions_job/4ab5ebdc794956d804d03db04557c8b79fa985cbf54bc25f51f2b0848e3f58bd
10:memory:/actions_job/4ab5ebdc794956d804d03db04557c8b79fa985cbf54bc25f51f2b0848e3f58bd
9:freezer:/actions_job/4ab5ebdc794956d804d03db04557c8b79fa985cbf54bc25f51f2b0848e3f58bd
8:cpuset:/actions_job/4ab5ebdc794956d804d03db04557c8b79fa985cbf54bc25f51f2b0848e3f58bd …
```
> Fix docker detection in ohai virtualization

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
- Add handling for `via` where the inet6 address family is specified
- Add rspec test to show working
I suspect this only fixes part of the issue for #1474 
Issue: https://github.com/chef/ohai/issues/1474
- [x ] Bug fix (non-breaking change which fixes an issue)
Signed-off-by: Cooper Lees <me@cooperlees.com>
> Linux network plugin: Handle IPv6 next hops for IPv4 routes

- lib/ohai/dsl/plugin.rb
- lib/ohai/mixin/command.rb
- lib/ohai/mixin/dmi_decode.rb
- lib/ohai/plugins/aix/virtualization.rb
- lib/ohai/plugins/azure.rb
- lib/ohai/plugins/bsd/virtualization.rb
- lib/ohai/plugins/cpu.rb
- lib/ohai/plugins/darwin/network.rb
- lib/ohai/plugins/darwin/virtualization.rb
- lib/ohai/plugins/ec2.rb
- lib/ohai/plugins/eucalyptus.rb
- lib/ohai/plugins/gce.rb
- lib/ohai/plugins/hostname.rb
- lib/ohai/plugins/linux/interrupts.rb
- lib/ohai/plugins/linux/network.rb
- lib/ohai/plugins/linux/platform.rb
- lib/ohai/plugins/linux/virtualization.rb
- lib/ohai/plugins/openstack.rb
- lib/ohai/plugins/rackspace.rb
- lib/ohai/plugins/solaris2/virtualization.rb
- lib/ohai/plugins/ssh_host_key.rb
- lib/ohai/plugins/vmware.rb
- lib/ohai/plugins/windows/network.rb
- lib/ohai/provides_map.rb
- lib/ohai/util/win32.rb
Avoid creating a bunch of match objects when we're not going to use the match results.
> Use .match? when we don't need the result

- lib/ohai/plugins/network.rb
- IPv4 can have IPv6 next hops, so we could use the wrong `.to_u*` method
- Lets try both before throwing on int conversions for sorting purposes
Addresses more for #1474
Signed-off-by: Cooper Lees <me@cooperlees.com>
> Handle IP to int conversion for inet + inet6

- spec/unit/mixin/command_spec.rb
In Ruby 2+ this is the default.
> Remove redundant file encoding in spec

- RELEASE_NOTES.md
- bin/ohai
- lib/ohai/mixin/dmi_decode.rb
- lib/ohai/plugins/aix/memory.rb
- lib/ohai/plugins/c.rb
- lib/ohai/plugins/filesystem.rb
- lib/ohai/plugins/hostname.rb
- lib/ohai/plugins/vmware.rb
- lib/ohai/plugins/windows/network.rb
- lib/ohai/plugins/windows/platform.rb
- tasks/spellcheck.rb
Pull in the latest rake task, fix some variable names, fix a few legit typos.
> Spelling fixes

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
- We can now have IPv6 next hops for IPv4 routes in Linux
- We don't have enough information to validate the route as valid if they are differen address families
Test:
- Add an rspec test to show it returning false like we'd hoped
- Have also tested on Facebook servers internally
Signed-off-by: Cooper Lees <me@cooperlees.com>
Fixes #1474
> Add Address Family Check to route_is_valid_default_route?

- lib/ohai/plugins/scaleway.rb
- spec/unit/plugins/scaleway_spec.rb
> Use match? instead of =~ when MatchData is not used

- lib/ohai/plugins/fips.rb
- spec/unit/plugins/fips_spec.rb
Don't rely on fips being enabled by chef-config. Pull the system status instead.
> Simplify FIPS plugin and use system fips status

- spec/unit/plugins/azure_spec.rb
- spec/unit/plugins/chef_spec.rb
- spec/unit/plugins/cloud_spec.rb
- spec/unit/plugins/ec2_spec.rb
- spec/unit/plugins/hostname_spec.rb
- spec/unit/plugins/windows/network_spec.rb
- spec/unit/util/ip_helper_spec.rb
The plugins should require everything they need unless we're using those libraries to mock out objects as we do in some Windows specs. This way we rely on the requires in the plugins and specs fail if those requires are removed.
> Remove non-Ohai requires from specs to prevent false positives

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
This broke because we never actually required ipaddress in the plugin, but the specs passed because we required it there.
> Update network plugin to use ipaddr not ipaddress gem

- Gemfile
This causes bundle install issues on windows
> Remove profile gemfile group for now

- .rubocop.yml
- Gemfile
I've already fixed all the warnings. This will keep it that way.
> Use rubocop-performance to enforce some best practices

- lib/ohai/plugins/filesystem.rb
- lib/ohai/plugins/windows/dmi.rb
Only include set if we need to and use require_relative which is faster
> Optimize 2 of our requires

- lib/ohai/plugins/windows/network.rb
This was missed since the windows network plugin just mocks out the IP
data. I'll see what I can do to make these more real world tests in a
followup PR
> Add missing require for windows network plugin

- lib/ohai/plugins/ec2.rb
- lib/ohai/plugins/linux/network.rb
- lib/ohai/plugins/shard.rb
- lib/ohai/plugins/softlayer.rb
- lib/ohai/plugins/solaris2/network.rb
We can avoid some duplicate checks by using &. in places
> Resolve new chefstyle warnings & use safe navigators

- spec/unit/mixin/shell_out_spec.rb
No impact to users here, but the new mixlib-shellout changed the log
level of streaming from debug to trace so we need to update this stub.
> Fix spec stub for the latest mixlib-shellout

- bin/ohai
- lib/ohai/config.rb
- lib/ohai/version.rb
- ohai.gemspec
- spec/spec_helper.rb
- spec/unit/plugins/linux/systemd_paths_spec.rb
This avoids some File.dirname calls
> Prefer __dir__ to __FILE__ used to get the dir

- spec/unit/plugins/aix/filesystem_spec.rb
- spec/unit/plugins/aix/hostname_spec.rb
- spec/unit/plugins/aix/kernel_spec.rb
- spec/unit/plugins/aix/network_spec.rb
- spec/unit/plugins/aix/uptime_spec.rb
- spec/unit/plugins/aix/virtualization_spec.rb
Mock out #resolve_fqdn like we do in all the other plugins to avoid actually checking the fqdn on the host running the specs.
This was our #2 slowest spec:
```
Ohai::System AIX hostname plugin sets the machinename
0.85031 seconds ./spec/unit/plugins/aix/hostname_spec.rb:30
```
> Speed up the AIX hostname spec

- lib/ohai/plugins/azure.rb
- spec/unit/plugins/azure_spec.rb
This will detect that a node is on Azure if DHCP option 15 is set to `reddog.microsoft.com` which Microsoft does in Azure for all customers.
> When you are using Azure-provided name resolution, Azure Dynamic Host Configuration Protocol (DHCP) provides an internal DNS suffix (.internal.cloudapp.net) to each VM. This suffix enables host name resolution because the host name records are in the internal.cloudapp.net zone. When you are using your own name resolution solution, this suffix is not supplied to VMs because it interferes with other DNS architectures (like domain-joined scenarios). Instead, Azure provides a non-functioning placeholder (reddog.microsoft.com).
Reference: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances
- …
> Detect Azure when DHCP domain is set to reddog.microsoft.com

- RELEASE_NOTES.md
- lib/ohai/plugins/passwd.rb
- spec/unit/plugins/passwd_spec.rb
This adds Windows support for the passwd plugin.
It's not fast, but I did work to improve the performance dropping it
from 20 seconds to 8 seconds on a VM with only a few users and groups.
The `get-localgroupmember` is the slow part (you have to run it one
group at a time), so the more groups you have, the slower this will go.
Note that unlike the Linux/Mac variety which will pick up nonlocal users
and groups this one does not (yet). It isn't hard to add, there are the
`get-aduser` and `get-adgroup` commands (if you have joined a domain),
but this is a good start.
And yes, I'll add tests when I have a moment.
> Windows support for Passwd plugin

- .expeditor/verify.pipeline.yml
Signed-off-by: Pete Higgins <pete@peterhiggins.org>
Infra client does not support ruby 2.5 so this CI job will never pass. chef/chef#10463
> Remove ruby 2.5 from CI.

- lib/ohai/common/dmi.rb
- lib/ohai/plugins/dmi.rb
- lib/ohai/plugins/solaris2/dmi.rb
Deprecate `whitelist` and replace with `allowlist`. Use the deprecation syntax to keep the old method alive - but marked as deprecated.
Fixes #1458
> Renamed 'whitelist' to 'allowlist' in DMI plugin

- lib/ohai/plugins/ec2.rb
- spec/unit/plugins/ec2_spec.rb
Currently the ohai ec2 plugin reads from the AWS metadata service but strips out all IAM data to prevent leaking security credentials. Change modifies this filtering slightly to still include the IAM role-name which is part of the metadata at:
iam/security-credentials/role-name
see: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-categories.html
Don't include the data returned in the document under role-name as that includes actually includes credentials, but the name part isn't a security concern and is useful to people to know the IAM identity of the instance where chef is running.
In the solution i'm being fairly paranoid checking explicitly for the security-credentials key and that it has exactly 1 key below it. As far as I can tell 'security-credentials' will …
> Include IAM role in ec2 data (issue #1524)

- Gemfile
- README.md
- Rakefile
If someone wants to generate docs they can just run yard against the
repo. This is overengineered
> Remove the yard task for generating docs

- lib/ohai/plugins/solaris2/platform.rb
OpenSolaris is beyond dead at this point and there's no reason to
continue running checks to see if we're on it.
> Remove detection of opensolaris platform

- lib/ohai/plugins/solaris2/platform.rb
This was EOL'd October 31, 2012
> Remove detection of EOL NexentaCore

- lib/ohai/plugins/solaris2/platform.rb
- spec/unit/plugins/solaris2/platform_spec.rb
1) Our regexes for the most part here were more complex than they needed to be
2) OpenIndiana's is now called OpenIndiana Hipster so the old regex was not working
3) Even the old regex only detected the major release instead of the full 3 point version
I doubt anyone is using the non-Hipster release at this point, but we detect it properly now and we have specs in place.
NOTE: Feel free to leave regex improvements here. I'm sure this could be better. I left the Solaris/Oracle Solaris one repetitive on purpose to make it easy to read what we were going for there. Realistically there we could probably squash that down to just "Oracle Linux" since that gets mid-Solaris 10 onwards.
> Properly detect OpenIndiana and its version numbers

- lib/ohai/plugins/zpools.rb
- spec/unit/plugins/zpools_spec.rb
We were expecting the disk name for each device in the pool, but it's
actually better to add them by disk id or guid. That entirely breaks out
regex so use -L on linux to make sure we get the underlying disk.
> Gather zpool disks even if zpools uses disk labels/guids

- lib/ohai/plugins/aix/uptime.rb
- lib/ohai/plugins/solaris2/virtualization.rb
This is just over 3x faster than using the regex.
> Split on strings intead of regex for 3x speedup

- lib/ohai/plugins/zpools.rb
- spec/unit/plugins/zpools_spec.rb
Add another match in the zpool status regex and then update the existing unit test to have some NVME/XVD devices in it.
> Properly detect NVME/XVD devices in ZFS zpools

- lib/ohai/plugins/linux/platform.rb
Adding pop_os to `platform_family` detection. Currently it is set as null since `/etc/os-release` `ID=pop`.
#1554
> pop_os is a derivative of ubuntu

- lib/ohai/runner.rb
Some of it was being printed in scientific notation depending on the elapsed time. Always print as a float and only show 6 digits. This makes it easier to sort and to reason with.
> Better format the elapsed plugin time

- spec/unit/system_spec.rb
This spec runs the entire Ohai suite, which can take a bit of time. let's disable the slowest stuff to speed it up a bit.
> Speedup the slowest spec by running fewer plugins

- lib/ohai/plugins/linux/hostnamectl.rb
- spec/unit/plugins/linux/hostnamectl_spec.rb
This is probably faster too since we don't have to lstrip each result.
> Fix parsing of hostnamectl to support values with colons

- lib/ohai/plugins/linux/memory.rb
We're trying to match all everything here so we don't care about the end
of the line.
> Remove regex anchors in the Linux Memory plugin

- lib/ohai/plugins/linux/lsb.rb
- spec/unit/plugins/linux/lsb_spec.rb
This was something we did for legacy Debian < 7. Seems like we're good to nuke this at this point since we don't ship on anything less than 9 now.
> Remove Linux LSB support for systems without lsb-release CLI

- lib/ohai/plugins/linux/lsb.rb
These are 1 line at a time matches and we want everything until the end. There's no point in doing it this way.
> Remove the line anchor from the LSB plugin matches

- spec/unit/mixin/shell_out_spec.rb
Signed-off-by: Pete Higgins <pete@peterhiggins.org>
Fix the busted specs. Example: https://buildkite.com/chef-oss/chef-ohai-master-verify/builds/757#_
> Update mock logger to fix shellout specs.

- lib/ohai/plugins/cpu.rb
- lib/ohai/plugins/darwin/network.rb
- lib/ohai/plugins/joyent.rb
- lib/ohai/plugins/linux/network.rb
- lib/ohai/plugins/packages.rb
- lib/ohai/plugins/uptime.rb
As Pete pointed out there's no need to split on whitespace when that's
the default
> Simplify all our splits

- .expeditor/run_linux_tests.sh
- .expeditor/verify.pipeline.yml
Since we're pulling chef/chef from git now we're basically updating the
cache each and every time this runs, which is very slow. It's possibly
faster to just do it from scratch each time.
> Disable gem caching / rubygems updates in Buildkite

- lib/ohai/plugins/aix/network.rb
There's a few different things going on here.
- more descriptive variable names. Variables like splat were not very useful and others like iface actually held more than 1 value
- replace a gsub and split with just a split on a regex from @phiggins
- avoid the whole weird splat thing and ranges and instead just split each interface into the name and all the data. This makes the variables more clear when we use them throughout
- avoid some positional math and just use shift to simply pop off the leading values to build the mash
> Refactor how we parse ifconfig in AIX

- lib/ohai/plugins/aix/memory.rb
- spec/unit/plugins/aix/memory_spec.rb
The grep needs to get refactored away, but at least this way we avoid doing math on all the values we gather.
> Simplify how we gather memory on AIX

- lib/ohai/plugins/aix/network.rb
- spec/unit/plugins/aix/network_spec.rb
Don't try to set the arp mash once for each line of the shellout
Convert grep in the shell to pure ruby, which is significantly faster
> More refactoring of the AIX network plugin

- lib/ohai/plugins/aix/platform.rb
- spec/unit/plugins/aix/platform_spec.rb
If we're in a collect block for aix then we're on aix.
> Simplify aix platform / platform_family detection

- lib/ohai/plugins/aix/virtualization.rb
- spec/unit/plugins/aix/virtualization_spec.rb
This is a pretty important bit of information on the wpar.
> Gather WPAR state in the AIX virtualization plugin

- lib/ohai/plugins/aix/kernel.rb
- spec/unit/plugins/aix/kernel_spec.rb
There's no point in querying that we're on aix when we only execute this collect on aix. Just hard code it to aix for historic reasons.
> Simplify the aix kernel plugin

- lib/ohai/plugins/aix/virtualization.rb
- lib/ohai/plugins/bsd/virtualization.rb
- lib/ohai/plugins/cpu.rb
- lib/ohai/plugins/dragonflybsd/memory.rb
- lib/ohai/plugins/dragonflybsd/platform.rb
- lib/ohai/plugins/freebsd/memory.rb
- lib/ohai/plugins/freebsd/platform.rb
- lib/ohai/plugins/hostname.rb
- lib/ohai/plugins/kernel.rb
- lib/ohai/plugins/netbsd/platform.rb
- lib/ohai/plugins/openbsd/platform.rb
- lib/ohai/plugins/os.rb
- lib/ohai/plugins/vmware.rb
- spec/spec_helper.rb
```
irb(main):008:0> "something\n ".split($/)[0]
=> "something"
```
```
irb(main):009:0> "something\n ".strip
=> "something"
```
Calculating -------------------------------------
split_stuff   120.000  memsize (     0.000  retained)
3.000  objects (     0.000  retained)
2.000  strings (     0.000  retained)
strip_stuff    80.000  memsize (     0.000  retained)
2.000  objects (     0.000  retained)
2.000  strings (     0.000  retained)
Comparison:
strip_stuff:         80 allocated
split_stuff:        120 allocated - 1.50x more
Warming up --------------------------------------
split_stuff   328.234k i/100ms
strip_stuff   604.612k i/100ms
Calculating -------------------------------------
split_stuff      3.648M (± 3.2%) i/s -     18.381M in   5.044570s
strip_stuff      5.993M (± 2.8%) i/s - …
> Use strip instead of split($/) to cleanup shellout

- lib/ohai/plugins/aix/virtualization.rb
- spec/unit/plugins/aix/virtualization_spec.rb
LPAR partition names can have spaces in them, which is problematic with our previous split method which would throw away anything past the space. On our internal AIX cluster "virtlpar03 - 7.1 testers" became just "virtlpar03".
> aix virtualization: Fix lpar name detection

- lib/ohai/plugins/digital_ocean.rb
- lib/ohai/plugins/libvirt.rb
- lib/ohai/plugins/linode.rb
- lib/ohai/plugins/scaleway.rb
- lib/ohai/plugins/virtualbox.rb
- spec/unit/plugins/digital_ocean_spec.rb
- spec/unit/plugins/linode_spec.rb
- spec/unit/plugins/scaleway_spec.rb
Running these on platforms these hypervisors / clouds don't support is pointless and in the case of scaleway it crashes on at least AIX. I went off the list of platforms these clouds / hypervisors support.
> Limit several of the Cloud/VM plugins to certain platforms

- lib/ohai/plugins/docker.rb
- spec/unit/plugins/docker_spec.rb
AIX lacks node['virtualization']['systems'] like every other OS so we
need to be a bit more defensive here. This doesn't impact the actual
run, but will make the verbose log output a bit nicer to read.
> Prevent docker plugin crashes on AIX

- lib/ohai/plugins/c.rb
- spec/unit/plugins/c_spec.rb
Add a spec with the newer XLC output from our build systems.
I'm sure @phiggins can tell me a better regex to use here
> Fix XLC compiler detection to support 3 part version numbers

- lib/ohai/plugins/linux/lspci.rb
- lib/ohai/plugins/scsi.rb
These aren't being used in these plugins.
> Remove platform dependencies that aren't needed

- lib/ohai/plugins/linode.rb
- spec/unit/plugins/linode_spec.rb
The current Linode plugin doesn't work at all. They no longer roll custom kernels so the kernel name detection doesn't ever fire. Instead we can look at the domain to see if it includes linode on RHEL boxes on check the apt sources on Debian/Ubuntu boxes.
> Update Linode plugin to use domain / apt data to detect Linode 

- lib/ohai/plugins/grub2.rb
- spec/unit/plugins/grub2_spec.rb
Add a basic plugin to expose GRUB2 environment variables. This is useful for example if one needs to manage the default kernel and/or its options on modern systems using EFI and BLS, but it will also work properly (and return useful data) on older systems.
> grub2: add plugin to expose GRUB2 environment variables

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
Query via ethtool and populate information whether the node 
has pause frames enabled or not.
To be able to configure pause parameters its useful to have access
to current settings.
> network: populate pause frame config

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
If you have more than 10 interfaces, `eth10` ended up at `:type => eth1` and `:number => 0`. This fixes it on our test host.
Signed-off-by: Olivier Raginel <babar@fb.com>
If you have more than 10 interfaces, `eth10` ended up at `:type => eth1` and `:number => 0`. This fixes it on our test host.
This was originally done in #1428 but I forgot to sign it, and then never took the time to do it again properly. This one is signed.
> Support more than 10 interfaces

- .expeditor/verify.pipeline.yml
- .rubocop.yml
- ohai.gemspec
We support N-1 and Ohai will support Ruby 3 and 2.7
> Require Ruby 2.7 or later

- Gemfile
Ohai 16 needs to pin to chef 16 and not master (17)
> Pin chef-utils and chef-config to chef 16.x

- lib/ohai/plugins/eucalyptus.rb
mostly just cleans up output in chef/chef rspec tests that reload ohai plugins
> suppress constant redefinition warning

- lib/ohai/mixin/ec2_metadata.rb
- spec/unit/mixin/ec2_metadata_spec.rb
- spec/unit/plugins/ec2_spec.rb
- spec/unit/plugins/eucalyptus_spec.rb
- spec/unit/plugins/openstack_spec.rb
Update all service calls to EC2 metadata to use IMDSV2 spec:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
EC2 metadata service IMDSV1 introduced quite a few vulnerabilities: https://hackerone.com/reports/508459
Add v2 token generation for each `NET::HTTP::Get` request.
Closes issue https://github.com/chef/ohai/issues/1411
> Update ec2_metadata to use IMDSV2

- lib/ohai/mixin/ec2_metadata.rb
- lib/ohai/plugins/rackspace.rb
They're not going to have a IMDSv2 token to fetch and they were failing hard.
> Fix fetching metadata on AWS compatible clouds

- lib/ohai/plugins/linux/platform.rb
We just needed to map the platform into the family. This is a Redhat
clone similar to CentOS.
> Detect Alma Linux with platform_family of rhel

- lib/ohai/plugins/ec2.rb
When I bumped the aws metadata versions we support it brought in some
new sensitive data we don't want on nodes. This skips accesskeyid /
secretaccesskey storage.
> Don't track sensitive new ec2 metadata

- lib/ohai/mixin/ec2_metadata.rb
- lib/ohai/plugins/rackspace.rb
- spec/unit/mixin/ec2_metadata_spec.rb
- spec/unit/plugins/ec2_spec.rb
- spec/unit/plugins/eucalyptus_spec.rb
- spec/unit/plugins/openstack_spec.rb
Reflected the comments on the pull request in #1457.
I have confirmed that this works with an EC2 instance with IMDSv2 only enabled.
Here's a quote from the original PR by @wilkosz
> Update all service calls to EC2 metadata to use IMDSV2 spec:
> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
>
> EC2 metadata service IMDSV1 introduced quite a few vulnerabilities: https://hackerone.com/reports/508459
> Add v2 token generation for each NET::HTTP::Get request.
> Closes issue #1411
- https://github.com/chef/ohai/pull/1457
- https://github.com/chef/ohai/issues/1411
This also backports https://github.com/chef/ohai/pull/1599 which fixes this to not break openstack/euca
> Update ec2_metadata to use IMDSV2 (Continued from #1457)

- lib/ohai/plugins/linux/platform.rb
We just needed to map the platform into the family. This is a Redhat
clone similar to CentOS.
Backports https://github.com/chef/ohai/pull/1604
> Detect Alam Linux with platform_family of rhel

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
When this plugin is updated to use `/etc/os-release`, it introduces a regression
on Debian testing and unstable, where the `VERSION_ID` field is not set.
In the legacy code path, `platform_version` is set on Debian by reading
`/etc/debian_version`; this is still needed on Debian testing and unstable.
Add a special case for Debian, falling back to reading this file rather than
to using `uname -r`, and update the spec to cover this.
Signed-off-by: Michel Alexandre Salim <michel@fb.com>
#1612
- xx] I have read the **CONTRIBUTING** document.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chef/ohai/1613)
> [linux/platform] fix platform_version on Debian testing and unstable

- spec/unit/plugins/hostname_spec.rb
- spec/unit/plugins/windows/filesystem_spec.rb
Ideally we should track down the actual class of the object
being returned here and `instance_double()` it properly (but
there's a thousand other specs that need it more than this
does)
> Remove stubbing mock methods onto the frozen `true` value

- lib/ohai/plugins/packages.rb
Per the [docs](https://docs.chef.io/resources/windows_package/), there
are three locations packages can be registered, but we only look in 2,
this adds all 3.
Now packages show up that were otherwise missing.
> Update `packages` for Windows to be complete.

- lib/ohai/plugins/linux/platform.rb
Remap the OS provided alinux to alibabalinux (matching our amazon structure)
Add this to RHEL since it's just CentOS 7.9 with additional packages and some services tweaked to boot faster
> Add platform / platform_family detection for Alibaba Cloud Linux

- lib/ohai/mixin/alibaba_metadata.rb
- lib/ohai/plugins/alibaba.rb
- lib/ohai/plugins/cloud.rb
- spec/unit/plugins/alibaba_spec.rb
- spec/unit/plugins/cloud_spec.rb
Detects Alibaba on Linux boxes and fetches metadata
> Add Alibaba cloud plugin

- lib/ohai/plugins/chef.rb
- spec/unit/plugins/chef_spec.rb
Signed-off-by: Collin McNeese <cmcneese@chef.io>
Adds check for Effortless pattern under `chef` plugin to populate if it is determined to be running as Effortless.  Will populate as `true` if found and `nil` if not matched.
`node['chef']['chef_effortless'] = true`
> Adds chef_effortless collection to chef plugin

- lib/ohai/plugins/habitat.rb
Returning in an ohai collect block stops the ohai run entirely without
any data being returned.
> Don't return in the hab plugin

- Gemfile
- lib/ohai/plugins/network.rb
Looks like this comparison is 2x faster on average according to docs
> Resolve new rubocop-performance warning

- Gemfile
- lib/ohai/plugins/network.rb
> Update rubocop-performance to 1.10.1 and revert optimization

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
This distro is now discontinued with the last release having shipped in
2019
> Remove support for discontinued antergos distro

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
Pidora is Fedora 18 and hasn't been updated since 2014.
> Remove support for Pidora which is discontinued

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
- All supported releases have an /etc/os-release file so nuke the legacy detection
- The platform ID in the os-release file is XCP-ng in 7 and xenserver in 8 (this is a bug IMO) so update the XCP match
- Downcase platform IDs. It seems like everyone makes these lowercase, but XCP-ng. There may be others and ohai platforms need to be lowercase
> Update the XCP-ng Linux Detection

- lib/ohai/plugins/linux/platform.rb
Nothing super scientific here, but it's about 10% faster to match if the data is hit sooner. Stick the super obscure stuff last.
> Stick the common matched platforms first

- lib/ohai/plugins/linux/virtualization.rb
- spec/unit/plugins/linux/virtualization_spec.rb
Docker is docker even if it is within other things.
Closes #1626
> Detect docker properly even if it's within virtualization

- lib/ohai/plugins/c.rb
- spec/unit/plugins/c_spec.rb
It's not safe to directly execute "libc.so.6" to determine glibc version.
This can lead to segfaults when other shared libraries are preloaded using
LD_PRELOAD or /etc/ld.so.preload due to circular relocation dependencies.
Replace this version detection with "ldd --version" as "ldd" is a core part
of glibc and reports the same version.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I have read the **CONTRIBUTING** document.
- [ x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
> Ohai: Change C language plugin for glibc version detection

- lib/ohai/plugins/linux/os_release.rb
- spec/unit/plugins/linux/os_release_spec.rb
On newer Linux systems which use systemd, they should include `/etc/os-release` [1] which includes a lot of platform information that can be useful downstream.
[1] https://www.freedesktop.org/software/systemd/man/os-release.html
NOTE: If accepted, I'll make a separate PR which will update linux/platform to depend on this plugin and optimize the use of reading `/etc/os-release` in multiple places. This can also be useful in chef/chef#11296 in case `lsb_release` isn't available. I didn't want to include this in this PR in case we could back port this to 16.
Signed-off-by: Lance Albertson <lance@osuosl.org>
> Create os_release plugin for parsing data from /etc/os-release

- lib/ohai/plugins/aix/virtualization.rb
- spec/unit/plugins/aix/virtualization_spec.rb
These don't make sense as strings. We should make them ints. This is a
breaking change.
> lpar_no and wpar_no in AIX Virtualizatin plugin should be Integers

- lib/ohai/plugins/linux/virtualization.rb
Dead link fixed, If you need other revisions of the link you can get that from https://web.archive.org/ . You just need to search by the link and choose available revisions according to date.
> Dead links fixed

- ohai.gemspec
Related to #1653 (earlier versions of chef-config required mixlib-shellout ~> 2.0)
> Update minimum version of chef-config

- lib/ohai/plugins/filesystem.rb
- spec/unit/plugins/windows/filesystem_spec.rb
For every platform we've had to go through these steps:
* add fs2
* make fs match fs2
* remove fs2
We've completed this on all platforms except windows which was at step 1. This moves Windows to step 2.
> Chef 17: Set 'filesystem' to be new-style data on Windows

- lib/ohai/plugins/linux/platform.rb
It's another RHEL clone
Thanks @kmf 
https://github.com/chef/os_release/blob/master/rocky_8
> Add Rocky Linux as RHEL platform_family

- lib/ohai/plugins/linux/livepatch.rb
- spec/unit/plugins/linux/livepatch_spec.rb
This plugin gets "enabled" and "transition" for each livepatch
in /sys/kernel/livepatch/*.
Signed-off-by: Song Liu <song@kernel.org>
> Add plugin for linux livepatch

- CHANGELOG.md
- lib/ohai/plugins/linux/tc.rb
- spec/unit/plugins/linux/tc_spec.rb
This plugin exposes the tc qdisc settings to chef.  For each interface a an array of qdiscs is created.
Each entry has the qdisc name, and a spot to places parameters for that particular qdisc.
The only parameter populated right now is the "buckets" values for fq discs.
Signed-off-by: Matthew Massey <matthewmassey@fb.com>
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have run the pre-merge tests locally and they pass.
> tc qdisc plugin

- lib/ohai/plugins/packages.rb
Change order of collect_programs_from_registry_key
move collection of Wos6432Node before HKEY_CURRENT_USER
When located last, ohai packages does not report Wow6432 software
Found when updating from Chef 15 to Chef 16
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have read the **CONTRIBUTING** document.
Signed-off-by: Wade Peacock <knightorc@xqqme.com>
> ohai/plugins/packages.rb - order change - present in both ohai 16 and 17 - impact chef 16/17

- lib/ohai/runner.rb
This is a potential fix for https://github.com/chef/ohai/issues/1598
If a plugin throws an exception it should be logged at a higher level to boost visibility.
https://github.com/chef/ohai/issues/1598
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have run the pre-merge tests locally and they pass.
- [ -] I have updated the documentation accordingly.
- [? ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
- [ x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
> log plugin exception at warn level

- lib/ohai/plugins/vmware.rb
- spec/unit/plugins/vmware_spec.rb
Currently, `vmware` only collects data on Linux systems.
Extended this to work on Windows as well and added keys on distinguishing VMware Desktop platforms (Fusion/Player/Workstation) from server platforms (vSphere aka ESX). Includes VMware Tools version as well.
Contents of `vmware` on VMware Workstation and Windows 2019:
```json
{
"host": {
"type": "vmware_desktop"
},
"guest": {
"vmware_tools_version": "11.2.6.28747"
},
"hosttime": "09 Dec 2021 10:57:20",
"speed": "1992 MHz",
"sessionid": "",
"balloon": "",
"swap": "",
"memlimit": "",
"memres": "",
"cpures": "",
"cpulimit": "",
"upgrade": "VMware Tools are up-to-date.",
"timesync": "Enabled"
}
```
Contents of `vmware` on VMware Workstation and Ubuntu 18.04:
```json
{
"host": {
"type": "vmware_desktop"
},
"guest": { …
```
> Add support for VMware detection on Windows and details

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
Recording the xdp data - mode, id and tag from the ip link output.
This data is recorded within the iface hash while gathering link statistics.
Added unit tests under network_spec.rb for all cases.
Signed-off-by: Zeeshan Lokhandwala <zeeshanl@fb.com>
Currently we do not have access to the XDP information contained in the ip link output. This patch records the xdp mode, id and tag. This will allow chef to know whether xdp is enabled and in which mode allowing the user to define specific network settings.
https://github.com/chef/ohai/issues/1729
> Network: Record xdp data from ip link.

- lib/ohai/plugins/filesystem.rb
- spec/unit/plugins/linux/filesystem_spec.rb
Collect data exported by btrfs to /sys/fs/btrfs/<uuid>/ and store it in
[:btrfs] for each btrfs filesystem. The current focus is on allocation
data, grouped by block_group type (data, metadata, system), but could be
easily extended in the future.
N.B. it doesn't currently detect any raid mode besides "single" and
"dup", since the main motivation is analyzing metadata usage.
Signed-off-by: Boris Burkov <boris@bur.io>
description in the commit.
https://github.com/chef/ohai/issues/1731
> Add btrfs specific data to filesystem plugin

- lib/ohai/plugins/linux/network.rb
- spec/unit/plugins/linux/network_spec.rb
Signed-off-by: Anita Zhang <the.anitazha@gmail.com>
We have some hosts using multipath routing and the network plugin is failing to set any interface information for the interfaces with such multipath configuration. This PR updates `check_routing_table()` in the network plugin to support multipath routing.
> Network: Add support for parsing multipath routing

- lib/ohai/plugins/ec2.rb
Comparing the names is much less efficient than comparing the instance directly.
It may also change in the future: https://bugs.ruby-lang.org/issues/18576
> Stop checking encoding names

- lib/ohai/plugins/linux/mdadm.rb
- spec/unit/plugins/linux/mdadm_spec.rb
Useful to have the UUID of the arrays to assemble them when the need arises
Signed-off-by: Saravanan D <saravanand@fb.com>
> [mdadm] Record array UUID

- .github/workflows/exec.yml
- .github/workflows/unit.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> Set permissions for GitHub actions

- lib/ohai/common/dmi.rb
- lib/ohai/mixin/network_helper.rb
- lib/ohai/plugins/rpm.rb
- lib/ohai/util/ip_helper.rb
ChefSpec invokes Ohai in its functionality. In situations where Ohai is already invoked before ChefSpec starts (for example, to detect the OS platform/version to configure Fauxhai), this will cause warnings about constants being already defined. This PR avoids those warnings by initializing constants only if they haven't been initialized earlier.
We did something similar in https://github.com/chef/ohai/pull/1628
> Do not attempt to reinitialize constants

- lib/ohai/plugins/fips.rb
- spec/unit/plugins/fips_spec.rb
Previously FIPS detection relied on the `OpenSSL::OPENSSL_FIPS`
constant being defined. However, on RedHat operating systems, this
constant is always defined in
`/usr/include/openssl/opensslconf-x86_64.h`. As a result, on such
operating systems FIPS mode would erroneously be labeled as enabled.
This constant is a necessary but not sufficient condition to determine
whether FIPS is actually enabled.
OpenSSL has a runtime `fips_mode` check
(https://wiki.openssl.org/index.php/FIPS_mode()) that should be used
instead. Ruby will use this if the `OPENSSL_FIPS` compile-time
constant is available:
https://github.com/ruby/ruby/blob/685efac05983dee44ce2d96c24f2fcb96a0aebe2/ext/openssl/ossl.c#L413-L428
> Fix FIPS mode detection

- lib/ohai/plugins/linux/platform.rb
- spec/unit/plugins/linux/platform_spec.rb
Add additional platforms.
- [x ] New feature (non-breaking change which adds functionality)
> Add additional SUSE and openSUSE platforms - micro, hpc

- lib/ohai/plugins/cpu.rb
https://github.com/chef/ohai/pull/1454 made `lscpu` the primary way Ohai gathers CPU data, but the parser doesn't handle the output from a Raspberry Pi 4 Cortex-A72. For example, an ARM cluster has the output `Core(s) per cluster` instead of `Core(s) per socket`.
We should fall back to `/proc/cpuinfo` if we don't get reasonable data back. It's not enough just to have `lscpu` output.
* https://github.com/chef/ohai/issues/1760
* https://github.com/chef/ohai/issues/1755
> Fall back to /proc/cpuinfo if lscpu doesn't have CPU totals

- lib/ohai/plugins/cpu.rb
- spec/data/plugins/cpuinfo-x86-guest-vtx.output
- spec/data/plugins/lscpu-x86-guest-vtx-cores.output
- spec/data/plugins/lscpu-x86-guest-vtx.output
- spec/unit/plugins/linux/cpu_spec.rb
In some LXD containers running with VT-x hardware virtualization, it appears that threads per core is 0, resulting in a total number of CPUs of 0. Add a test case and handle some quirks with the `lscpu` output.
This pull request also makes the default CPU configurable in the tests. Normally CPU 0 is the default, but on some virtualized hosts this is not the case.
Closes https://github.com/chef/ohai/issues/1755
> Use a minimum of 1 thread per core for CPU total calculation

- lib/ohai/plugins/ec2.rb
Makes this function a one-liner too, because the return is implicit and the evaluation of the conditionals will yield true or false.
Signed-off-by: Marc A. Paradise <marc.paradise@gmail.com>
> Fix linter error

- Gemfile
Signed-off-by: Vikram Karve <vikram.karve@progress.com>
Ohai 17.x should be in sync with Chef 17.x. The `chef-util` and `chef-config` gem dependencies should refer the `chef-17` branch of github.com/chef/chef
Doesn't fix https://github.com/chef/ohai/issues/1771 but perhaps related.
> Update chef gems need to refer chef-17

- lib/ohai/plugins/darwin/virtualization.rb
- spec/unit/plugins/darwin/virtualization_spec.rb
Currently, a machine can be miscategorized as a physical machine. This can happen if a VM happens to have Parallels installed on it. This can be fixed by inverting the if-else statement, thereby checking if the machine is a VM before checking if the machine has Parallels installed on it.
#1775
> Darwin virtualization plugin: fix potential for false positive

- lib/ohai/plugins/linux/network.rb
- lib/ohai/plugins/packages.rb
- spec/unit/plugins/linux/network_spec.rb
Signed-off-by: John McCrae <john.mccrae@progress.com>
Signed-off-by: Neha Pansare <neha.pansare@progress.com>
- This PR backports https://github.com/chef/ohai/pull/1741
- This PR also fixes windows unit test CI failures for `16-stable` branch. 
```
Failures:
1) Ohai::System plugin packages when on windows on 32 bit ruby behaves like windows_package_plugin gets package info
Failure/Error:
repo.open(key_path, reg_type) do |reg|
reg.each_key do |key, _wtime|
pkg = reg.open(key)
name = pkg["DisplayName"] rescue nil
next if name.nil?
package = packages[name] = Mash.new
WINDOWS_ATTRIBUTE_ALIASES.each do |registry_attr, package_attr|
C:/hostedtoolcache/windows/Ruby/2.7.7/x64/bin/ruby.exe -I'D:/a/ohai/ohai/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib';'D:/a/ohai/ohai/vendor/bundle/ruby/2.7. …
```
> [Bacport #1741 to 16] networking/linux: Map src only default routes accordingly

- lib/ohai/plugins/timezone.rb
- lib/ohai/plugins/vmware.rb
Windows with German language display returns Windows-1252 encoded time zone descriptor in German which does not cleanly convert to Ruby's standard UTF-8, in part because it is described as IBM437 encoding.
* [Code Page 437/IBM437](https://en.wikipedia.org/wiki/Code_page_437)
* [ISO/IEC 8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1)
* [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252)
[INFC-402](https://chefio.atlassian.net/browse/INFC-402) - Chef Infra Client: Due to german characters like "ä", "ö", "ü" the JSON convert of the audit results fails in the chef infra client.
[INFC-402]: https://chefio.atlassian.net/browse/INFC-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Force encoding with timezones that include umlauts if zone encoding is IBM437

- .github/workflows/exec.yml
- lib/ohai/mixin/oci_metadata.rb
- lib/ohai/plugins/cloud.rb
- lib/ohai/plugins/oci.rb
- spec/unit/mixin/oci_metadata_spec.rb
- spec/unit/plugins/cloud_spec.rb
- spec/unit/plugins/oci_spec.rb
`ohai cloud` fail if the vm is in Oracle Cloud Infrastructure (OCI). This PR add support to this cloud provider to cloud plugin.
Ohai don't detect OCI has a cloud provider, so for cookbook thats require some changes related to the cloud provider, this is a issue.
Following the [OCI Metadata Documentation](https://docs.oracle.com/en-us/iaas/Content/Compute/Tasks/gettingmetadata.htm) I build this change.
#1779
> Add cloud provider oci

- lib/ohai/mixin/alibaba_metadata.rb
- lib/ohai/mixin/azure_metadata.rb
- lib/ohai/mixin/ec2_metadata.rb
- lib/ohai/mixin/gce_metadata.rb
- lib/ohai/mixin/json_helper.rb
- lib/ohai/mixin/oci_metadata.rb
- spec/unit/mixin/oci_metadata_spec.rb
In some plugins, YAJL parser is called twice. That's really inefficient.
We definitely shouldn't fire off the YAJL parser twice if we don't need to.
_Originally posted by @jaymzh in https://github.com/chef/ohai/pull/1780#pullrequestreview-1288003393_
Add cloud provider oci #1780
> Calling yajl parser only once

- lib/ohai/plugins/linux/block_device.rb
- spec/unit/plugins/linux/block_device_spec.rb
Enhancing the plugin to record the firmware of nvme block devices
The sysfs end point for firmware in nvme block device differs from HDD. Added firmware_rev to the plugin check list to collect this information on servers with nvme block devices.
> [block_device] Record firmware revision of nvme block devices

- lib/ohai/plugins/darwin/platform.rb
- spec/unit/plugins/darwin/platform_spec.rb
Apple is adding a new update type to macOS called Rapid Security Responses. These updates change the build version, but not the OS version reported by `sw_vers`. Instead, a new `ProductVersionExtra` key is returned to denote a specific supplemental version only when a RSR is installed. If no RSR is installed the key is not present. 
```
$ sw_vers
ProductName: macOS
ProductVersion: 13.3
ProductVersionExtra: (a)
BuildVersion: 22E7752300f
```
https://support.apple.com/guide/deployment/rapid-security-responses-dep93ff7ea78/web
This PR adds support for reporting on the RSR version when a patch is installed. The information is important to Mac admins since it gives a full picture of current OS build, whether a security vulnerability has been patched, and, depending on Apple's future plans, if …
> Add support for macOS Rapid Security Response updates

- lib/ohai/mixin/gce_metadata.rb
Only append `?recursive=true` is the generated url is a directory.
Previously the api calls would be:
/computeMetadata/v1/?recursive=true/
/computeMetadata/v1/?recursive=true/instance/
/computeMetadata/v1/?recursive=true/instance/instance/
until #<SystemStackError: stack level too deep>
#1796
> Fix gce metadata recursion issue #1796

- lib/ohai/mixin/alibaba_metadata.rb
- spec/unit/mixin/alibaba_metadata_spec.rb
- spec/unit/plugins/alibaba_spec.rb
do the same thing of #1802 , but this will merge into the `main` branch. ( I think it will be `18-stable` )
Previous PR: #1766
On Alibaba Cloud, the response of user-data metadata API is not processed properly.
And, modified the unit tests to align with the actual response data.
#1765
> Fetch the user-data on Alibaba Cloud correctly

- lib/ohai/plugins/linux/network.rb
Adjusting IPROUTE_INT_REGEX to match interfaces with an underscore and/or dash after the arobase
This would now match: 11: mgmt_team.73@mgmt_team: ...
- Bug fix (non-breaking change which fixes an issue)
> fp/Adjusting IPROUTE_INT_REGEX to match interfaces with an underscore

- lib/ohai/mixin/network_helper.rb
- spec/unit/mixin/network_helper_spec.rb
node['fqdn'] missing the DNS Suffix on windows nodes
If `canonname` includes multiple parts (`'.'`), then assume that that is a FQDN and return.
Otherwise, use `getnameinfo` as a fallback. If that return value is not an IP, return it.
If all else fails, just return what we originally received as an argument.
Internal issue: CHEF-605
Broken in PR [#1705](https://github.com/chef/ohai/pull/1705)
Fixes [#1733](https://github.com/chef/ohai/issues/1733)
> Add getnameinfo as a fall through case for fqdn resolution

- ohai.gemspec
Ohai gem has an unbounded FFI version which causes issues on macOS when ffi is used after app bundler install.
> ffi less than 1.16.0

- README.md
- lib/ohai/plugins/darwin/virtualization.rb
- spec/unit/plugins/darwin/virtualization_spec.rb
This PR adds a check for whether a Darwin machine is running as a QEMU guest.
Apple added a [Virtualization Framework](https://developer.apple.com/documentation/virtualization) based on QEMU to recent releases of macOS. This has resulted in many more options, such as [UTM](https://github.com/utmapp/UTM) for organizations looking to run virtual macOS machines on Apple hardware.
One such organization appears to be Github, which seems to be adding Veertu VMs to their Github Actions runners. Unfortunately, Chef's `virtual?` helper fails to detect these machines as guests, since `ohai` isn't setting the role for QEMU VMs.
The XNU kernel added an Object ID named [kern.hv_vmm_present](https://github.com/apple/darwin-xnu/blob/main/bsd/kern/kern_sysctl.c#L4652), which returns 0 for physical …
> Detect QEMU virtualization on Darwin.

- lib/ohai/plugins/darwin/virtualization.rb
- spec/unit/plugins/darwin/virtualization_spec.rb
Determine if we are an Apple Virtualization Framework guest based on `machine_model` data.
Apple provides a virtualization framework that supports arm64 and x86_64 guests depending on the host hardware. The `virtual?` method does not work if we are outside the Vagrant paradigm, so this change looks for the specific substring Apple sets in `machine_model` when creating guest hardware.
> determine if we are an Apple Virtualization Framework guest

- lib/ohai/mixin/network_helper.rb
- ohai.gemspec
- spec/unit/mixin/network_helper_spec.rb
Updating FQDN details for Windows nodes. The don't properly show a domain suffix which is confounding customers who need the details
> Updating FQDN details for Windows nodes

- .github/workflows/exec.yml
- .github/workflows/lint.yml
- .github/workflows/unit.yml
We are now longer supporting Ruby 2.7. Removing the tests as they are causing issues
> Removing Ruby 2.7 testing

- lib/ohai/plugins/linux/lspci.rb
- spec/unit/plugins/linux/lspci_spec.rb
(sorry, I'm using domain and root port interchangeably. Maybe domain is more correct, if so I can update the code to use that instead of `root_port`)
I'm guessing most machines only have one PCIe root port, but things like ARM hosts tend to have more, and that breaks as it creates collisions.
As we want to keep backwards compatibility, and `lspci` is run with the defaults that doesn't show the root port if it's `0000`, only add it when it's non-zero, and also add it as a new extra field called `root_port` to denote the fact that there is one (useful when using the BDF to find files on disk, as when there is no `root_port`, one needs to add the extra `0000:`.
More detailed explanation I wrote on the slack channel: On Linux, we run `lspci -vnnmk`, which will show the BDF in the first …
> [lspci] Fix handling of more than one PCIe domain

- lib/ohai/plugins/cpu.rb
- spec/data/plugins/cpuinfo-aarch64-guest-kvm-rhel9.output
- spec/data/plugins/cpuinfo-ppc64le-p9-guest-kvm-rhel9.output
- spec/data/plugins/cpuinfo-x86-guest-kvm-nested-rhel9.output
- spec/data/plugins/lscpu-aarch64-guest-kvm-cores-rhel9.output
- spec/data/plugins/lscpu-aarch64-guest-kvm-rhel9.output
- spec/data/plugins/lscpu-aarch64-host-rhel9.output
- spec/data/plugins/lscpu-ppc64le-p8-host-debian12.output
- spec/data/plugins/lscpu-ppc64le-p9-guest-kvm-cores-rhel9.output
- spec/data/plugins/lscpu-ppc64le-p9-guest-kvm-rhel9.output
- spec/data/plugins/lscpu-ppc64le-p9-host-rhel9.output
- spec/data/plugins/lscpu-x86-guest-kvm-nested-cores-rhel9.output
- spec/data/plugins/lscpu-x86-guest-kvm-nested-rhel9.output
- spec/data/plugins/lscpu-x86-host-rhel9.output
- spec/unit/plugins/linux/cpu_spec.rb
Starting in util-linux v2.36, the output of lscpu changed which introduced some
bugs in some platforms. To work around this, the previous output can be retained
if the lscpu command is piped to something else. To work around that, this just
pipes the output to cat.
This fixes #1805
Signed-off-by: Lance Albertson <lance@osuosl.org>
> cpu: Fix issues with newer versions of lscpu

- lib/ohai/plugins/filesystem.rb
- spec/unit/plugins/linux/filesystem_spec.rb
Checks that the sysfs directory even exists for btrfs partitions before attempting reads and failing.
> [#1830] Check that sysfs directory exists before reading

- .github/workflows/lint.yml
- Gemfile
- README.md
- Rakefile
> [18-stable] Migrate from Chefstyle to Cookstyle gem

- lib/ohai/plugins/freebsd/network.rb
> FreeBSD: Permit underscores in interface names

- lib/ohai/plugins/freebsd/network.rb
- spec/unit/plugins/freebsd/network_spec.rb
This adds unittests for the FreeBSD network plugin. It also fixes
various issues:
* It now running on modern freebsd which has extra columns in netstat output.
* It now properly reports encapuslation, MTU, and metric
It also includes a test case with `::1` on `lo1` to start building out
support for sorting out #1838
> Unit tests for freebsd network plugin; plus fixes

- .expeditor/buildkite/artifact.habitat.test.ps1
- .expeditor/buildkite/artifact.habitat.test.sh
- .expeditor/config.yml
- .expeditor/habitat-test.pipeline.yml
- habitat/plan.sh
- habitat/tests/test.sh
> Testing pipeline

- .github/workflows/exec.yml
- .github/workflows/unit.yml
- Gemfile
- ohai.gemspec
Per https://github.com/ffi/ffi/issues/1139#issuecomment-2632381142
```shell
$ bundle update --conservative ffi
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Resolving dependencies...
Bundler attempted to update ffi but its version stayed the same
Bundle updated!
```
> Update ffi lock

- .github/workflows/exec.yml
- .github/workflows/lint.yml
- .github/workflows/unit.yml
- lib/ohai/plugins/ec2.rb
- ohai.gemspec
- spec/unit/mixin/shell_out_spec.rb
Update the pipelines to use ruby 3.4.x for testing, drop ruby 2.7, 3.0. Update tests accordingly to support ruby 3.4
> Ruby bump 3.4.x

- lib/ohai/plugins/filesystem.rb
- spec/unit/plugins/windows/filesystem_spec.rb
In 2015, I wrote a new filesystem plugin (#559), because the original
one used non-unique keys and so the data was not only incomplete but
inconsistent. Since it was backwards incompatible, we called it
`filesystem2`, and agreed to a migration path.
That original PR only implemented it for linux, however, and it shortly
followed with #564 for Darwin/OSX.
The plan was, at that time to keep both for one major version (give
people the chance to migrate to fs2), then for one major version make
both names (`filesystem` and `filesystem2`) so that people could move
back to the name `filesystem`, and then we'd finally drop the
`filesystem2` name.
Unfortunately, other platforms never got FS2 support, so this got hairy.
In 2018 I wrote #181 which unified the various platforms' plugins so it
was …
> The filesystem plugin transition is finally over
