chef/ohai

.travis.yml, appveyor.yml, lib/ohai/plugins/digital_ocean.rb, lib/ohai/util/ip_helper.rb
Part one of fix: make sure CI fails
Part two of fix: fixit
=> Ohai 8.1 is broken

lib/ohai/plugins/kernel.rb
This is a technically a breaking change. I'm ok with that.
cc  @adamedx @btm @juliandunn @smurawski
=> OEM logo is large and completely useless. Remove

lib/ohai/plugins/dmi.rb, spec/unit/plugins/dmi_spec.rb
=> Correctly ignore unwanted DMI data

lib/ohai/plugins/solaris2/dmi.rb, spec/unit/plugins/solaris2/dmi_spec.rb
Fixes #539 
cc @chef/client-core
=> make DMI work on solaris

lib/ohai/plugins/solaris2/network.rb
We're failing to detect non intel ethernet drivers, which means that on some solaris nodes we don't get a mac address or a default IP. 
Closes #549
=> Update list of solaris ethernet drivers

.travis.yml
=> drop ruby 2.0 on travis in line with chef

CHANGELOG.md, lib/ohai/version.rb
=> Release Ohai 8.5.0

lib/ohai/plugins/linux/filesystem.rb, spec/unit/plugins/linux/filesystem_spec.rb
=> Change lsblk usage in linux filesystem plugin

CHANGELOG.md, RELEASE_NOTES.md, lib/ohai/plugins/darwin/filesystem2.rb, spec/unit/plugins/darwin/filesystem2_spec.rb
This is just a port of #559 to Darwin. See that PR for the details.
=> Port new filesystem2 plugin to darwin.

RELEASE_NOTES.md, lib/ohai/plugins/darwin/filesystem2.rb, lib/ohai/plugins/linux/filesystem2.rb, spec/unit/plugins/darwin/filesystem2_spec.rb, spec/unit/plugins/darwin/filesystem_spec.rb, spec/unit/plugins/linux/filesystem2_spec.rb, spec/unit/plugins/linux/filesystem_spec.rb
Only because @mcquin is so awesome.
Currently based ontop of #567
=> Move filesystem-related specs to use `let`

lib/ohai/util/ip_helper.rb, spec/unit/util/ip_helper_spec.rb
=> fixes #545 (IPv6 bug in detecting link-local addresses)

lib/ohai/plugins/linux/virtualization.rb, spec/unit/plugins/linux/virtualization_spec.rb
Resolves https://github.com/chef/ohai/issues/590
=> Detect KVM guest from dmidecode

lib/ohai/plugins/vmware.rb, spec/unit/plugins/vmware_spec.rb
This pulls in @drobinson440 's work from #414 on the vmware plugin  and adds tests for it.
=> add vmware plugin

lib/ohai/plugins/aix/memory.rb, spec/unit/plugins/aix/memory_spec.rb
This PR adds swap space attributes for AIX as found in memory plugins for other platforms
=> Add swap space attributes for AIX

Rakefile
=> use bundle rake tasks

lib/ohai/version.rb
=> Bump revision to 8.7.0

ohai.gemspec
=> Add gemspec files to allow bundler to run from the gem

lib/ohai/plugins/solaris2/filesystem.rb, spec/unit/plugins/solaris2/filesystem.rb
Resolves https://github.com/chef/ohai/issues/629.
=> Configurable filesystem properties collected for Solaris2.x

lib/ohai/application.rb, lib/ohai/loader.rb, lib/ohai/system.rb, spec/functional/loader_spec.rb, spec/unit/loader_spec.rb
Resolves https://github.com/chef/ohai/issues/636 for @pburkholder 
=> Escape plugin directories for globbing

lib/ohai/plugins/aix/kernel.rb, spec/unit/plugins/aix/kernel_spec.rb
(Yes, there is 32-bit AIX, and yes, this command does return "32" on it.)
=> Provide AIX kernel bittiness

lib/ohai/mixin/os.rb, lib/ohai/plugins/dragonflybsd/cpu.rb, lib/ohai/plugins/dragonflybsd/filesystem.rb, lib/ohai/plugins/dragonflybsd/memory.rb, lib/ohai/plugins/dragonflybsd/network.rb, lib/ohai/plugins/dragonflybsd/os.rb, lib/ohai/plugins/dragonflybsd/platform.rb, lib/ohai/plugins/hostname.rb, lib/ohai/plugins/kernel.rb, lib/ohai/plugins/uptime.rb
This PR adds basic support for DragonFly BSD
=> Initial support for DragonFly BSD

lib/ohai/plugins/windows/virtualization.rb, spec/unit/plugins/windows/virtualization_spec.rb
Fetch WMI data within Ruby vs. shelling out to Powershell.  This should
be WAY faster.
=> Detect vbox/vmware/kvm on Windows and speed up runs

CHANGELOG.md
Minor - fix changelog version back to 8.8.0
@tas50 @lamont-granquist @btm
=> Fix CHANGELOG version

spec/unit/plugins/linux/cpu_spec.rb
actually tests more than a single socket/core/threaded scenario
=> better tests for /proc/cpuinfo

CHANGELOG.md, RELEASE_NOTES.md, lib/ohai/version.rb
Getting ready to release ohai 8.8.1
@chef/client-core @jaym @tas50
=> Rev version to 8.8.1, update changelog and release notes

.rubocop.yml, .travis.yml, Gemfile, Rakefile, spec/unit/plugins/darwin/system_profiler_output.rb
=> Enable ChefStyle per RFC 64

lib/ohai/plugins/darwin/memory.rb, spec/unit/plugins/aix/memory_spec.rb, spec/unit/plugins/ruby_spec.rb, spec/unit/plugins/solaris2/cpu_spec.rb
1 Lint/EndAlignment
3 Lint/BlockAlignment
=> Fix some lint cops:

lib/ohai/plugins/linux/platform.rb, spec/unit/plugins/linux/platform_spec.rb
=> Adding a new "alpine" platform and platform_family

CHANGELOG.md, lib/ohai/version.rb
@chef/client-maintainers @tas50 @jkeiser
=> Prep for release 8.9.0

lib/ohai/mixin/dmi_decode.rb, lib/ohai/plugins/bsd/virtualization.rb, lib/ohai/plugins/linux/virtualization.rb, spec/unit/plugins/linux/virtualization_spec.rb
Method rename and a few minor style cleanups
=> Linux virtualization plugin style cleanup

CHANGELOG.md, lib/ohai/version.rb
Prep for release of Ohai 8.9.1
@chef/client-core @tas50 @danielsdeleo @jaym
=> Update changelog, bump version

lib/ohai/plugins/digital_ocean.rb, lib/ohai/plugins/eucalyptus.rb, lib/ohai/plugins/gce.rb, lib/ohai/plugins/linode.rb, lib/ohai/plugins/rackspace.rb, lib/ohai/plugins/softlayer.rb
Add debug for hints / mac detection to a few plugins
Fixed the eucalyptus plugin to not spam debug with mac detection false warnings for each interface
=> Improved debug logging for cloud plugins

lib/ohai/mixin/ec2_metadata.rb
This gives us "services_domain": "amazonaws.com" and a new value for
termination time on spot instances.  I also fixed some rubocop warnings
and added a breadcrumb to the debug
=> Add support for the last 2 EC2 metadata versions

Gemfile, ohai.gemspec
=> have a proper dependency on plist

lib/ohai/plugins/azure.rb, spec/unit/plugins/azure_spec.rb
The presence of a DHCP lease file was enough to match as Azure.  Fix that and add a test with an Openstack DHCP lease so this doesn't happen again.
=> Fix false detection of Linux hosts with a DHCP lease as being azure

ohai.gemspec
=> Add back the pin to github changelog generator

lib/ohai/plugins/aix/os.rb, spec/unit/plugins/aix/os_spec.rb
=> Set os_version to match the output of oslevel -s

CHANGELOG.md, lib/ohai/version.rb
This is needed for incoming changes to chef-client related to the FIPS plugin
=> release 8.15.0

CHANGELOG.md, lib/ohai/version.rb
Want to get this in before merging https://github.com/chef/chef/pull/4841 and also to make reading travis logs easier.
=> release 8.15.1

lib/ohai/dsl/plugin/versionvii.rb, lib/ohai/mixin/command.rb, lib/ohai/mixin/gce_metadata.rb, lib/ohai/plugins/bsd/virtualization.rb, lib/ohai/plugins/digital_ocean.rb, lib/ohai/plugins/ec2.rb, lib/ohai/plugins/eucalyptus.rb, lib/ohai/plugins/gce.rb, lib/ohai/plugins/ip_scopes.rb, lib/ohai/plugins/linode.rb, lib/ohai/plugins/softlayer.rb, lib/ohai/plugins/virtualization.rb, spec/unit/mixin/command_spec.rb
This makes it a lot easier to read things
=> Consistent plugin debug logging

lib/ohai/plugins/packages.rb
include pld linux as platform with rpm support
=> Update packages plugin to support PLD Linux as an RPM distro

CHANGELOG.md, DOC_CHANGES.md, OHAI_MVPS.md, RELEASE_NOTES.md, lib/ohai/version.rb
Time to get this into our nightlies
=> Release 8.16.0

lib/ohai/plugins/linux/network.rb, spec/unit/plugins/linux/network_spec.rb
I'd like to know if addresses are dynamic or not, for example.
=> Add additional info to networking interfaces/addresses

CHANGELOG.md, RELEASE_NOTES.md, lib/ohai/version.rb
Let's make sure we get our recent changes into the next Chef release.
=> Release 8.17.0

lib/ohai/plugins/linux/memory.rb, spec/unit/plugins/linux/memory_spec.rb
Read the HugePages[0] information from `/proc/meminfo`.
[0]: https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt
=> Add support for Linux HugePages

lib/ohai/plugins/darwin/virtualization.rb, spec/unit/plugins/darwin/virtualization_spec.rb
=> Add detection of Virtualbox and VMware Fusion on OS X

.travis.yml, appveyor.yml
Also remove the builds of stable branches we don't use. We're never releasing 7 stable again.
=> Update Ruby version + branches we build

CHANGELOG.md, lib/ohai/version.rb
=> Release 8.18

CHANGELOG.md, lib/ohai/version.rb
=> Release 8.19.0

CHANGELOG.md, lib/ohai/version.rb
=> Release 8.19.2

DOC_CHANGES.md
Can someone double check that that's the right config syntax? Haven't played much with configurable plugins.
=> Doc changes for #877

CHANGELOG.md, lib/ohai/version.rb
=> Release 8.21

OHAI_MVPS.md
Get @johnbellone @davide125 @natewalck @jaymzh and @jerearista on here
=> Add new MVPs for the last few releases

RELEASE_NOTES.md
=> Wipe the release notes

lib/ohai/plugins/haskell.rb, spec/unit/plugins/haskell_spec.rb
Detects whether ghc, ghci, cabal, or stack are installed
=> Added haskell language plugin for ohai

.github/PULL_REQUEST_TEMPLATE.md
=> Add a github pull request template

Rakefile
=> Match github changelog config with chef/chef

appveyor.yml
=> Test on 2012 R2 in appveyer

CHANGELOG.md, OHAI_MVPS.md, RELEASE_NOTES.md, lib/ohai/version.rb
=> Release 8.22.0

lib/ohai/mixin/dmi_decode.rb, lib/ohai/plugins/windows/virtualization.rb, spec/unit/plugins/linux/virtualization_spec.rb, spec/unit/plugins/windows/virtualization_spec.rb
Hypervisor for OS that runs Linux and WIndows
https://veertu.com/
=> Detect guests running on Veertu hypervisor

CHANGELOG.md, RELEASE_NOTES.md, lib/ohai/version.rb
=> Release 8.23.0

lib/ohai/mixin/gce_metadata.rb, lib/ohai/plugins/linux/virtualization.rb, spec/unit/plugins/linux/virtualization_spec.rb
Identified with unused and confirmed with good old search.
=> Remove a bit of dead code

lib/ohai/common/dmi.rb, lib/ohai/plugins/darwin/platform.rb, lib/ohai/plugins/dmi.rb, lib/ohai/plugins/dragonflybsd/network.rb, lib/ohai/plugins/freebsd/network.rb, lib/ohai/plugins/linux/network.rb, lib/ohai/plugins/netbsd/network.rb, lib/ohai/plugins/openbsd/network.rb, lib/ohai/plugins/packages.rb, lib/ohai/plugins/rackspace.rb, lib/ohai/plugins/solaris2/dmi.rb, lib/ohai/plugins/solaris2/network.rb, lib/ohai/plugins/uptime.rb, lib/ohai/plugins/windows/filesystem.rb, lib/ohai/plugins/windows/network.rb, lib/ohai/runner.rb, lib/ohai/system.rb, platform_simulation_specs/common/ohai_plugin_common.rb, spec/unit/plugins/bsd/virtualization_spec.rb, spec/unit/plugins/netbsd/kernel_spec.rb, spec/unit/plugins/solaris2/virtualization_spec.rb
prep for chefstyle 0.5.0 release to not break master
=> autofixing new chefstyle issues

spec/unit/system_spec.rb
=> Fix a chefstyle warning

lib/ohai/plugins/cloud.rb, lib/ohai/plugins/cloud_v2.rb, spec/unit/plugins/cloud_spec.rb, spec/unit/plugins/cloud_v2_spec.rb
The cloud plugins were not properly updated for the new data format returned in the digital ocean plugin.
=> Fix the cloud plugins to properly report values on DO

lib/ohai/loader.rb, spec/unit/loader_spec.rb
=> The secondary plugin path not existing should be info not warn level

.travis.yml
=> Bump Ruby versions in Travis to the latest

RELEASE_NOTES.md
I wrote this quickly before heading to the doctor, so there's bound to be some typos. I'd like to get all the breaking changes (minus ruby) documented on the deprecations page before we add these release notes to the docs page. This is a first good stab though.
=> Update Ohai 13 release notes

CHANGELOG.md, Gemfile, Rakefile, lib/ohai/version.rb
The rake task needed to be updated for the new tags
=> Fix changelog rake task and release 13.0.1

CHANGELOG.md, RELEASE_NOTES.md, lib/ohai/loader.rb, lib/ohai/version.rb
=> Release Ohai 13.1.0

lib/ohai/mixin/ec2_metadata.rb, lib/ohai/mixin/softlayer_metadata.rb, lib/ohai/plugins/darwin/hardware.rb, lib/ohai/plugins/elixir.rb, lib/ohai/plugins/erlang.rb, lib/ohai/plugins/go.rb, lib/ohai/plugins/hostname.rb, lib/ohai/plugins/java.rb, lib/ohai/plugins/linux/lsb.rb, lib/ohai/plugins/mono.rb, lib/ohai/plugins/nodejs.rb, lib/ohai/plugins/perl.rb, lib/ohai/plugins/php.rb, lib/ohai/plugins/powershell.rb, lib/ohai/plugins/python.rb, lib/ohai/plugins/rackspace.rb, lib/ohai/plugins/rust.rb, lib/ohai/plugins/solaris2/dmi.rb, lib/ohai/plugins/solaris2/network.rb, lib/ohai/plugins/ssh_host_key.rb, spec/unit/plugins/rackspace_spec.rb
I think this is the last of it.
=> More consistent debug messaging

lib/ohai/plugins/linux/filesystem.rb, spec/unit/plugins/linux/filesystem_spec.rb
Today lsblk and blkid each have their various shortcomings. Various hacks
and workarounds have been added and changed as we migrated to using lsblk
over blkid, but we can do better.
We run over both and combine the data.
This was caught when we noticed that somne of our AOE-type filesystems were
not recognized by lsblk when not mounted, but blkid did notice them. This meant
we thought the devices were not formatted and wanted to format them. That's bad.
Mega bad.
Missing FS information
=> Make filesystem more resilient

lib/ohai/common/dmi.rb, lib/ohai/dsl/plugin.rb, lib/ohai/dsl/plugin/versionvi.rb, lib/ohai/dsl/plugin/versionvii.rb, lib/ohai/mash.rb, lib/ohai/mixin/command.rb, lib/ohai/mixin/dmi_decode.rb, lib/ohai/mixin/os.rb, lib/ohai/mixin/string.rb, lib/ohai/plugins/azure.rb, lib/ohai/plugins/c.rb, lib/ohai/plugins/digital_ocean.rb, lib/ohai/plugins/ec2.rb, lib/ohai/plugins/eucalyptus.rb, lib/ohai/plugins/hostname.rb, lib/ohai/plugins/java.rb, lib/ohai/plugins/kernel.rb, lib/ohai/plugins/linux/filesystem.rb, lib/ohai/plugins/openstack.rb, lib/ohai/plugins/uptime.rb, lib/ohai/util/file_helper.rb, platform_simulation_specs/common/ohai_plugin_common.rb
=> autofixing cops for chefstyle 0.5.0

lib/ohai/plugins/packages.rb, spec/data/plugins/lslpp.output, spec/unit/plugins/packages_spec.rb
Adding a test and chefstyle fix
=> PR #1016 with updates

RELEASE_NOTES.md, lib/ohai/version.rb
=> Release 13.2

.travis.yml, Gemfile
=> Update Travis config

.travis.yml
Similar to what I did on the 8-stable branch
=> Test on Trusty in Travis

RELEASE_NOTES.md
=> Add f5 detection to the release notes

RELEASE_NOTES.md, lib/ohai/version.rb
=> Release 13.3

lib/ohai/plugins/linux/filesystem.rb, spec/unit/plugins/linux/filesystem_spec.rb
=> Use standard logging in Filesystem

lib/ohai/plugins/digital_ocean.rb, lib/ohai/plugins/dragonflybsd/os.rb, lib/ohai/plugins/ec2.rb, lib/ohai/plugins/eucalyptus.rb, lib/ohai/plugins/freebsd/os.rb, lib/ohai/plugins/gce.rb, lib/ohai/plugins/hostname.rb, lib/ohai/plugins/linux/systemd_paths.rb, lib/ohai/plugins/linux/virtualization.rb, lib/ohai/plugins/network.rb, lib/ohai/plugins/openstack.rb, lib/ohai/plugins/os.rb, lib/ohai/plugins/passwd.rb, lib/ohai/plugins/rackspace.rb, lib/ohai/plugins/shard.rb, lib/ohai/plugins/softlayer.rb, lib/ohai/plugins/solaris2/virtualization.rb, lib/ohai/plugins/uptime.rb
Avoid requiring all these things if we're skipping these plugins
=> Move all requires into the plugin definitions

CHANGELOG.md, RELEASE_NOTES.md, lib/ohai/version.rb
=> Release Ohai 13.4

lib/ohai/config.rb, lib/ohai/dsl/plugin.rb, lib/ohai/exception.rb, lib/ohai/runner.rb, lib/ohai/system.rb, spec/unit/system_spec.rb
This is a backport of #1064 to Ohai 8
This fixes #879.
=> Critical Plugins - backport to Ohai 8

CHANGELOG.md, Gemfile.local, lib/ohai/version.rb
Make sure this is waiting for the next Chef 12 release so we get the solaris fix out
=> Release 8.25.0

lib/ohai/plugins/packages.rb
=> Gather packages on Amazon Linux

.travis.yml
=> Properly allow ruby-head to fail in Travis

CHANGELOG.md, RELEASE_NOTES.md, lib/ohai/version.rb
=> Release 13.6

lib/ohai/plugins/linux/memory.rb, spec/unit/plugins/linux/memory_spec.rb
Add support for Linux MemAvailable value
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773
=> Add support for Linux MemAvailable value

appveyor.yml
We missed this when we started the stable branch
=> Test the 8-stable branch in Appveyor

CHANGELOG.md, lib/ohai/version.rb
=> Release Ohai 8.25.1

appveyor.yml
also remove ruby 2.3 since we don't use it with 13
=> Fix appveyor by no longer dancing around bundler

lib/ohai/mixin/azure_metadata.rb, lib/ohai/mixin/do_metadata.rb, lib/ohai/mixin/ec2_metadata.rb
=> Fix a few typos in log messages

lib/ohai/plugins/cloud.rb, lib/ohai/plugins/linux/platform.rb, lib/ohai/system.rb, spec/unit/plugins/cloud_spec.rb, spec/unit/plugins/powershell_spec.rb, spec/unit/system_spec.rb
=> Remove extra ()s on methods

lib/ohai/plugins/c.rb
=> Add missing debug log message for xlc missing on AIX

CHANGELOG.md, RELEASE_NOTES.md, lib/ohai/version.rb
We need this before we can release a candidate for Chef.
=> Release 13.7.0

lib/ohai/plugins/linux/network.rb, spec/unit/plugins/linux/network_spec.rb
This is a backport of #1104 to Ohai 8.
=> [linux/network] [ohai 8] Tunnel information

lib/ohai/plugins/ec2.rb, spec/unit/plugins/ec2_spec.rb
=> Backport support for new EC2 instance types

CHANGELOG.md, RELEASE_NOTES.md, lib/ohai/version.rb
=> Release 13.7.1

CHANGELOG.md, RELEASE_NOTES.md, lib/ohai/version.rb
=> Release 8.26.0

.travis.yml, appveyor.yml
We're branching 13-stable off and that becomes our previous release.
=> Swap 8-stable testing for 13-stable testing

lib/ohai/mixin/ec2_metadata.rb
=> Treat local_ipv4 as an array

CHANGELOG.md, lib/ohai/version.rb
=> Release 8.26.1

lib/ohai/plugins/libvirt.rb
We enabled a new rule between the time I opened that PR and now
=> Chefstyle fix for libvirt plugin

lib/ohai/plugins/kernel.rb
Speed up some of the windows kernel helpers methods and remove the duplicate dragonfly plugin that was just a copy of freebsd.
=> Simplify & optimize the kernel plugin

CHANGELOG.md, RELEASE_NOTES.md, lib/ohai/version.rb
=> Release 13.8.0

lib/ohai/plugins/darwin/virtualization.rb, spec/unit/plugins/darwin/virtualization_spec.rb
This is something we'll want when managing macs with Chef.
=> Detect virtualbox and vmware guests on Macs

lib/ohai/plugins/zpools.rb
=> Don't stacktrace if we can't shell_out to zpool

RELEASE_NOTES.md
=> Add Ohai 14 release notes

CHANGELOG.md, lib/ohai/version.rb
=> Release 13.9

lib/ohai/common/dmi.rb, lib/ohai/dsl/plugin.rb, lib/ohai/dsl/plugin/versionvii.rb, lib/ohai/hints.rb, lib/ohai/mash.rb, lib/ohai/mixin/ec2_metadata.rb, lib/ohai/mixin/gce_metadata.rb, lib/ohai/mixin/http_helper.rb, lib/ohai/mixin/os.rb, lib/ohai/mixin/scaleway_metadata.rb, lib/ohai/mixin/seconds_to_human.rb, lib/ohai/mixin/softlayer_metadata.rb, lib/ohai/mixin/string.rb
Fix yard parsing errors in the Mash class and add comments to Hints and Plugin
=> Fix yard parsing issues & add more commments

lib/ohai/mixin/seconds_to_human.rb, lib/ohai/plugins/linux/lspci.rb, lib/ohai/plugins/solaris2/cpu.rb, spec/unit/system_spec.rb
A few things that Rubymine identified
=> Misc minor cleanup

lib/ohai/plugins/openstack.rb, spec/unit/plugins/openstack_spec.rb
=> Detect Red Hat OpenStack clusters

.travis.yml
Test on what Ohai should be used on.
=> Test on the latest ruby releases in Travis

CHANGELOG.md
Expeditor is smarter than I am. Add these back one more time. After this
we're done with the hand edits forever since things are wired up in both
branches.
=> Add back missing changelog entries

RELEASE_NOTES.md
=> Add 14.2 release notes

RELEASE_NOTES.md
=> Add release notes for 13.9 and 13.9.2

lib/ohai/plugins/openstack.rb, spec/unit/plugins/openstack_spec.rb
Signed-off-by: Thom May <thom@chef.io>
=> Detect Redhat Openstack clusters

RELEASE_NOTES.md
=> Prep 13.10 release

RELEASE_NOTES.md
=> Add release notes for 14.4

.travis.yml, Gemfile, README.md
Add the gem groups, speed up Travis installs, update the readme tasks
documentation.
=> More rake / Travis updates

lib/ohai/dsl/plugin.rb, lib/ohai/hints.rb, lib/ohai/loader.rb, lib/ohai/log.rb, lib/ohai/system.rb
=> Add additional yard comments

.github/CODEOWNERS
Lets get input from the docs team when we edit documentation like the readme or release notes
=> Update the codeowners

RELEASE_NOTES.md
Signed-off-by: Mary Jinglewski (mjinglewski@chef.io)
Review of Release Notes as request with minor copyediting.
Minor copyediting details have now been included.
=> Review and copyediting of RELEASE_NOTES

lib/ohai/application.rb, lib/ohai/exception.rb, lib/ohai/hints.rb, lib/ohai/log.rb, lib/ohai/system.rb
Filling out the missing bits here.
=> Add more yard comments

appveyor.yml
Straight copy of https://github.com/chef/chef/pull/3015 to Ohai.
Appveyer fails bundle install sometimes. :/
=> [appveyer] make appveyor retry bundle install

RELEASE_NOTES.md
=> Add release notes for Ohai 14.6

lib/ohai/plugins/linux/platform.rb, spec/unit/plugins/linux/platform_spec.rb
This combines https://github.com/chef/ohai/pull/1272 and https://github.com/chef/ohai/pull/1140
=> Add support for SLES 15

.expeditor/config.yml
=> Fix expeditor config for the 14-stable branch

lib/ohai/plugins/hostname.rb, spec/unit/plugins/hostname_spec.rb
cherry-picked #1053 
Closes #1053
Added Specs
#1053
=> Windows: Fix for fqdn is being set as the machine name instead of fqdn

CODE_OF_CONDUCT.md
This way it shows up in Github when you open a PR or issue.
=> Add Chef code of conduct link

lib/ohai/plugins/linux/platform.rb, spec/unit/plugins/linux/platform_spec.rb
=> Add support for SUSE Linux Enterprise Desktop

.travis.yml
=> Test on Ubuntu Xenial in Travis

lib/ohai/plugins/linux/platform.rb
=> Add support for XCP-NG platform

RELEASE_NOTES.md
=> Add final notes for Ohai 14.8

.expeditor/config.yml, .github/lock.yml, .travis.yml, appveyor.yml
=> Update appveyor / travis configs and add lockbot

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/BUG_TEMPLATE.md, .github/ISSUE_TEMPLATE/DESIGN_PROPOSAL.md, .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST_TEMPLATE.md, .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md, README.md
This project is now part of the chef-infra project. This updates the
codeowners and adds information to the readme.
=> Update the repo for the new governance

.expeditor/config.yml, .expeditor/verify.pipeline.yml
First step in getting testing on multiple platforms on each PR. For now this will be just Linux based tests similar to what we have with Travis.
=> Add testing in buildkite

.expeditor/verify.pipeline.yml
=> Run ohai in Buildkite

lib/ohai/mixin/command.rb, lib/ohai/plugins/scsi.rb, lib/ohai/system.rb
=> fix shellout require idempotency

.expeditor/config.yml, .expeditor/verify.pipeline.yml
Test with the rake tasks and normalize the expeditor config against other repos.
=> Minor tweaks to our expeditor / build kite config

RELEASE_NOTES.md, lib/ohai/plugins/vbox_host.rb, spec/unit/plugins/vbox_host_spec.rb
Adds ohai plugin to support VirtualBox as a virtualization host.
=> Add VboxHost plugin to support VirtualBox as a virtualization host

lib/ohai/plugins/linux/sysctl.rb, spec/unit/plugins/linux/sysctl_spec.rb
Add sysctl ohai plugin
This exposes current sysctl values in effect on a Linux system 
https://github.com/chef/ohai/issues/1400
Signed-off-by: Joshua Miller <joshmiller@fb.com>
=> Add sysctl ohai plugin

spec/functional/plugins/powershell_spec.rb, spec/unit/config_spec.rb, spec/unit/dsl/plugin_spec.rb, spec/unit/loader_spec.rb, spec/unit/mixin/command_spec.rb, spec/unit/mixin/dmi_decode_spec.rb, spec/unit/mixin/ec2_metadata_spec.rb, spec/unit/mixin/network_helper_spec.rb, spec/unit/mixin/softlayer_metadata_spec.rb, spec/unit/plugins/aix/virtualization_spec.rb, spec/unit/plugins/c_spec.rb, spec/unit/plugins/dmi_spec.rb, spec/unit/plugins/docker_spec.rb, spec/unit/plugins/haskell_spec.rb, spec/unit/plugins/linux/kernel_spec.rb, spec/unit/plugins/linux/platform_spec.rb, spec/unit/plugins/linux/sysctl_spec.rb, spec/unit/plugins/linux/virtualization_spec.rb, spec/unit/plugins/openstack_spec.rb, spec/unit/plugins/packages_spec.rb, spec/unit/plugins/scala_spec.rb, spec/unit/plugins/solaris2/cpu_spec.rb, spec/unit/plugins/virtualbox_spec.rb, spec/unit/plugins/vmware_spec.rb, spec/unit/plugins/windows/network_spec.rb, spec/unit/plugins/zpools_spec.rb, spec/unit/provides_map_spec.rb, spec/unit/runner_spec.rb
It detected some very simple to fix issues with our specs
=> Minor spec cleanup from rubocop-rspec project

ohai.gemspec
=> Allow chef-config 16

.expeditor/config.yml
=> Test the 15-stable branch in expeditor

lib/ohai/plugins/openstack.rb, spec/unit/plugins/openstack_spec.rb
=> backport #1434 for 15 stable

.expeditor/run_linux_tests.sh, .expeditor/verify.pipeline.yml, .github/CODEOWNERS
=> Use native Expeditor gem caching & fix code owners

.expeditor/verify.pipeline.yml
=> Cache gem installs in Buildkite on Windows as well

.expeditor/run_linux_tests.sh, .expeditor/verify.pipeline.yml, lib/ohai/config.rb
Backport #1408
Signed-off-by: Ben Rexin <ben@rexin.at>
=> fix: ensure optional_plugins to be array of symbols

spec/unit/plugins/linux/interrupts_spec.rb, spec/unit/plugins/linux/ipc_spec.rb
These were chefstyle violations on master.
Signed-off-by: Pete Higgins <pete@peterhiggins.org>
=> Fix chefstyle violations.

Gemfile, lib/ohai/plugins/kernel.rb
=> Remove an internal reference to blacklist

lib/ohai/plugins/ruby.rb
This drops two additional shell outs to run ruby.
=> Faster ruby language plugin

lib/ohai/plugins/linux/network.rb, lib/ohai/plugins/network.rb
Avoid creating and object we don't need.
=> Use .find instead of .select.first

ohai.gemspec
I can't see a place where we're using this.
=> Remove unused systemu dependency

lib/ohai/mixin/do_metadata.rb, lib/ohai/mixin/scaleway_metadata.rb, lib/ohai/plugins/aix/memory.rb, lib/ohai/plugins/bsd/virtualization.rb, lib/ohai/plugins/cloud.rb, lib/ohai/plugins/cpu.rb, lib/ohai/plugins/darwin/platform.rb, lib/ohai/plugins/kernel.rb, lib/ohai/plugins/linux/network.rb, spec/unit/mixin/dmi_decode_spec.rb, spec/unit/plugins/bsd/virtualization_spec.rb, spec/unit/plugins/netbsd/kernel_spec.rb
Simplify the code so it's easier to read
=> Resolve RuboCop Style/RedundantParentheses warnings

lib/ohai/plugins/packages.rb, spec/data/plugins/system_profiler_spapplicationsdatatype.output, spec/unit/plugins/packages_spec.rb
Tested with MacOS 10.14.6 and 10.15.6
Signed-off-by: Matt Ray <github@mattray.dev>
=> Add MacOS packages support

Gemfile, ohai.gemspec
Makes it a tiny bit easier on the eyes to find stuff
=> Order the gems in the gemspec and gemfile

spec/unit/plugins/linux/sysctl_spec.rb, spec/unit/plugins/linux/systemd_paths_spec.rb, spec/unit/plugins/shells_spec.rb, spec/unit/plugins/solaris2/filesystem.rb
=> Spec cleanup

lib/ohai/mixin/ec2_metadata.rb, lib/ohai/plugins/linux/ipc.rb, lib/ohai/plugins/linux/network.rb, lib/ohai/plugins/rackspace.rb
=> chefstyle fixes

spec/unit/plugins/solaris2/platform_spec.rb
Make sure this actually works and act as a reference for what the output
actually looks like.
=> Add unit testing for omnios platform detection

lib/ohai/plugins/aix/network.rb, lib/ohai/plugins/aix/uptime.rb, lib/ohai/plugins/kernel.rb, lib/ohai/plugins/windows/network.rb, spec/functional/plugins/powershell_spec.rb
We're working harder here than we need to. Let's simplify these and make
them easier to figure out for the humans involved.
=> Simplify regexes by removing extra character classes

lib/ohai/plugins/elixir.rb, lib/ohai/plugins/eucalyptus.rb, lib/ohai/plugins/filesystem.rb, lib/ohai/plugins/go.rb, lib/ohai/plugins/groovy.rb, lib/ohai/plugins/lua.rb, lib/ohai/plugins/mono.rb, lib/ohai/plugins/nodejs.rb, lib/ohai/plugins/perl.rb, lib/ohai/plugins/php.rb, lib/ohai/plugins/powershell.rb, lib/ohai/plugins/python.rb, lib/ohai/plugins/rackspace.rb, lib/ohai/plugins/ruby.rb, lib/ohai/plugins/rust.rb, lib/ohai/plugins/shard.rb
Shave a bit more memory usage off Ohai
=> Minor memory optimizations

lib/ohai/plugins/cpu.rb, lib/ohai/plugins/darwin/memory.rb, lib/ohai/runner.rb
=> Collapse duplicate branches in case statements

Gemfile
=> Update rubocop-performance to 1.9

lib/ohai/plugins/aix/network.rb, spec/unit/plugins/aix/network_spec.rb
=> Minor performance optimizations in AIX Network plugin

lib/ohai/plugins/aix/kernel.rb, spec/unit/plugins/aix/kernel_spec.rb
Just get all the data we need and then split it.
=> Avoid calling uname 4 times on aix

lib/ohai/plugins/filesystem.rb, spec/unit/plugins/aix/filesystem_spec.rb, spec/unit/plugins/bsd/filesystem_spec.rb, spec/unit/plugins/solaris2/filesystem_spec.rb
This was planned to end in Ohai 17
=> Stop gathering filesystem2 data on BSD/Solaris/AIX

Gemfile
=> Fetch chef-utils and chef-config from chef-16 branch

Gemfile
I opened the previous PR against the wrong branch
=> Update master ohai to pull from master chef

Gemfile
Ride master only on master of Ohai
=> Pin chefstyle for Ohai 16 to a known version

lib/ohai/plugins/linux/virtualization.rb, spec/unit/plugins/linux/virtualization_spec.rb
This provides proper support for detecting Podman hosts and guests which is now the default container system on Fedora and RHEL 8+.
In addition, this works around a problem when running containers on Github Actions. They apparently configure the docker on their runs in a non-standard way which renames the cgroup mounts to `actions_job`.
It also shows `/system.slice/containerd.service` as a cgroup mount point and should be a safe assumption this is running inside a docker container. This should be checked last in the logic order since it would be triggered in the first check if it were added there.
You can see an example of this not working here:
https://github.com/sous-chefs/resolver/pull/47/checks?check_run_id=1840420956
Signed-off-by: Lance Albertson <lance@osuosl.org>
=> Add support for Podman and fix docker guest detection on Github Actions

lib/ohai/plugins/habitat.rb, spec/unit/plugins/habitat_spec.rb
Signed-off-by: Collin McNeese <cmcneese@chef.io>
Adds collection of installed Habitat version, packages and services:
__node['habitat']['version']__ : String
__node['habitat']['packages']__ : Array of package identities
__node['habitat']['services']__ : Array of service names
=> adds Habitat plugin

lib/ohai/plugins/linux/virtualization.rb, spec/unit/plugins/linux/virtualization_spec.rb
Docker is docker even if it is within other things.
Closes #1626
=> Detect docker properly even if it's within virtualization

lib/ohai/plugins/linux/network.rb, spec/unit/plugins/linux/network_spec.rb
Populate node with offload features information queried via ethtool -k.
=> network: Add offload features to node.

lib/ohai/plugins/chef.rb, spec/unit/plugins/chef_spec.rb
=> Identify effortless installs in the Chef plugin

lib/ohai/plugins/linux/platform.rb
=> Add support for Sangoma Linux

Gemfile
=> Update rubocop-performance to 1.10.2

lib/ohai/plugins/hostname.rb
Handle the case where we have either v4- or v6-specific configuration
or network issues that causes gethostaddr() to fail
Note this was found due to a specific case: On OSX - and possibly others
(freebsd), if you have a linklocal address for your hostname in
/etc/hosts then `getaddrinfo` for your hostname will raise an exception.
=> Fall back to v4-only getaddrinfo if we get socket errors

ohai.gemspec
=> Update minimum version of mixlib-shellout

ohai.gemspec
Related to #1653 (earlier versions of chef-config required mixlib-shellout ~> 2.0)
=> Update minimum version of chef-config

lib/ohai/plugins/cloud.rb, lib/ohai/plugins/linux/network.rb
We only support Ruby 2.7+ and this takes less memory
=> Use filter_map where we can

README.md
=> Update the readme copyright

lib/ohai/plugins/linux/platform.rb
Signed-off-by: Robert Masztalerz <robertmasztalerz@gmail.com>
Add Virtuozzo as RHEL platform_family.
=> Add Virtuozzo as RHEL platform_family

lib/ohai/plugins/linux/platform.rb
=> Backport 947a97d47daa1dce6aa7b91f2057b15451805b25

.github/workflows/exec.yml, .github/workflows/lint.yml, .github/workflows/unit.yml
=> Run the github actions test on 16-stable too

.expeditor/config.yml, .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
Make sure all the workflows are configured here as well.
=> Backport the expeditor updates to 16-stable

.github/workflows/lint.yml
=> Add linting testing to 16-stable branch

.github/workflows/unit.yml, spec/unit/application_spec.rb, spec/unit/plugins/windows/filesystem_spec.rb
=> Run unit tests in GitHub Actions

lib/ohai/plugins/linux/platform.rb, spec/unit/plugins/linux/platform_spec.rb
https://github.com/chef/ohai/pull/1632
https://github.com/chef/ohai/pull/1635
https://github.com/chef/ohai/pull/1670
=> Backport Linux OS detection improvements from Chef 17

lib/ohai/plugins/chef.rb
This wasn't actually rescuing.
=> Fix the exception handling in the chef plugin

CHANGELOG.md
Signed-off-by: Neha Pansare <neha.pansare@progress.com>
Update changelog.md manually to include previously merged PR when expeditor version bump wasn't working
=> Update changelog.md manually to include previously merged PR

spec/data/plugins/pkg-query.output
Updating Proxifier dependencies to reflect the move to Proxifier2
=> Updating files to account for Proxifier2

.github/workflows/sonarqube.yml, sonar-project.properties
Adding `sonar-project.properties` and `.github/workflows/sonarqube.yml` for sonarQube integration.
=> Adding files for onboarding the project to SonarQubes

.github/workflows/exec.yml, .github/workflows/unit.yml
Adds 3.2 to the list of Ruby CI versions to run tests against Ruby 3.2
=> Add 3.2 to the list of Ruby CI versions

lib/ohai/common/dmi.rb, lib/ohai/mixin/network_helper.rb, lib/ohai/plugins/rpm.rb, lib/ohai/util/ip_helper.rb
Backport of PR 1758 to the 17-Stable branch
=> [backport] PR1758

lib/ohai/plugins/platform.rb
Enable Chef to detect if a node is managed in Target Mode vs agent mode
=> Add platform_backend attribute for Target Mode

Gemfile
Fixing the GH CI for Chef 18 branch
=> [Chef18] Use Chef 18 branches of chef/chef

lib/ohai/plugins/filesystem.rb, spec/unit/plugins/linux/filesystem_spec.rb
Backport of #1831 to 18-stable branch
=> [#1830][18-stable] Check that sysfs directory exists before reading

.expeditor/config.yml, habitat/tests/test.sh
=> Publish test pipeline

.expeditor/config.yml
Adding publish to hab  dev channel
=> Adding dev channel publish hab channel

.expeditor/config.yml
=> Adding release branch

.expeditor/config.yml, .expeditor/verify.pipeline.yml
Just a test pr to verify the pipeline creation by expeditor
=> test verify pipeline creation by expeditor

habitat/plan.ps1
Adding the builder channel to **LTS-2024**
=> added the channel variable

ohai.gemspec
=> updating ffi for Ohai

habitat/plan.ps1, habitat/plan.sh
Hab pkg size issue removed cache and bundler folder
=> Hab pkg size issue removed cache and bundler folder

.expeditor/config.yml
=> Make `buildkite/chef-ohai-main-habitat-test` public

.expeditor/run_linux_tests.sh, .github/workflows/exec.yml, .github/workflows/lint.yml, .github/workflows/unit.yml, .rubocop.yml, Gemfile, Rakefile, ohai.gemspec
Formally moving away from chefstyle to cookstyle
=> upgrading to cookstyle
